$dialog show @s \
{\
  "type":"minecraft:confirmation",\
  "body":[\
    {\
      "type":"minecraft:item",\
      "item":{\
        "id":"minecraft:command_block",\
        "components":{\
          "minecraft:tooltip_display":{\
            "hide_tooltip":true\
          }\
        }\
      },\
      "description":{\
        "translate":"menu.mob_manager.gamerules.description",\
        "fallback":"Configure Vanilla Gamerules:"\
      }\
    }\
  ],\
  "inputs":[\
    {\
      "type":"minecraft:single_option",\
      "key":"cmdfeedback",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.commandfeedback",\
        "fallback":"Send Command Feedback"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(cmdfeedback_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"insomnia",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.insomnia",\
        "fallback":"Phantom Spawning"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(insomnia_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"warden",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.warden",\
        "fallback":"Warden Spawning"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(warden_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"raids",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.raids",\
        "fallback":"Raids"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(raids_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"mobloot",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.mobloot",\
        "fallback":"Mob Loot"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(mobloot_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"patrols",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.patrols",\
        "fallback":"Patrol Spawning"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(patrols_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"trader",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.trader",\
        "fallback":"Wandering Trader Spawning"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(trader_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"griefing",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.griefing",\
        "fallback":"Mob Griefing"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(griefing_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"locatorbar",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.locatorbar",\
        "fallback":"Locator Bar"\
      },\
      "options":[\
        {\
          "id":"tru",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"fals",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(locatorbar_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"cramming",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.cramming",\
        "fallback":"Max Entity Cramming"\
      },\
      "start":1,\
      "end":1024,\
      "step":1,\
      "initial":$(cramming)\
    }\
  ],\
  "can_close_with_escape":true,\
  "pause":true,\
  "after_action":"close",\
  "external_title":{\
    "translate":"menu.mob_manager.gamerule.title",\
    "fallback":"Vanilla Gamerules"\
  },\
  "title":{\
    "translate":"menu.mob_manager.main.title",\
    "fallback":"Nice Mob Settings"\
  },\
  "yes":{\
    "label":{\
      "translate":"option.mob_manager.confirm",\
      "fallback":"Confirm"\
    },\
    "action":{\
      "type":"minecraft:dynamic/run_command",\
      "template":"$(command_template)"\
    }\
  },\
  "no":{\
    "label":{\
      "translate":"gui.back"\
    },\
    "action":{\
      "type":"minecraft:show_dialog",\
      "dialog":"mob_manager:main"\
    }\
  }\
}