$dialog show @s \
{\
  "type":"minecraft:confirmation",\
  "body":[\
    {\
      "type":"minecraft:item",\
      "item":{\
        "id":"minecraft:command_block",\
        "components":{\
          "minecraft:tooltip_display":{\
            "hide_tooltip":true\
          }\
        }\
      },\
      "description":{\
        "translate":"menu.mob_manager.misc.description",\
        "fallback":"Configure Miscellaneous Settings:"\
      }\
    }\
  ],\
  "inputs":[\
    {\
      "type":"minecraft:single_option",\
      "key":"locator_assets",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.locator_assets",\
        "fallback":"Spawn Egg Locator Bar Icons"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(locator_assets_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"mobs_on_locator_bar",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.mobs_on_locator_bar",\
        "fallback":"Mobs Show On Locator Bar"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(mobs_on_locator_bar_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"need_sky",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.need_sky",\
        "fallback":"Scaling/Rarity Only On Surface"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(need_sky_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"skeletonhorsetrap",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.skeletonhorsetrap",\
        "fallback":"Skeleton Horse Traps"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(skeletonhorsetrap_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"shulkercolor",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.shulkercolor",\
        "fallback":"Random Shulker Color"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(shulkercolor_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"irongolemanger",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.irongolemanger",\
        "fallback":"Iron Golem Angry At Player"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(irongolemanger_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"egglay",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.egglay",\
        "fallback":"Chickens Lay Eggs"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(egglay_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"creeperfuse",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.creeperfuse",\
        "fallback":"Size Relative Creeper Fuse"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(creeperfuse_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"snifferbrain",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.snifferbrain",\
        "fallback":"Sniffers Track Digs"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(snifferbrain_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"rabbitcarrot",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.rabbitcarrot",\
        "fallback":"Rabbits Eat Carrot Plants"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(rabbitcarrot_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"jebcolor",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.jebcolor",\
        "fallback":"Random Jeb Sheep Wool Color"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(jebcolor_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"jebspawning",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.jebspawning",\
        "fallback":"Jeb Sheep Spawn Chance"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(jebspawning_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"killerrabbitspawning",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.killerrabbit",\
        "fallback":"Killer Rabbit Spawn Chance"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(killerrabbitspawning_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"babymountspawning",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.babymountspawning",\
        "fallback":"Baby Mount Spawn Chance"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(babymountspawning_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"illusionerspawning",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.illusionerspawning",\
        "fallback":"Evoker To Illusioner Chance"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(illusionerspawning_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"immunezombie",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.immunezombie",\
        "fallback":"Immune To Zombification Chance"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(immunezombie_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"brownmoospawning",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.brownmoospawning",\
        "fallback":"Brown Mooshroom Spawn Chance"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(brownmoospawning_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"lefthanded",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.lefthanded",\
        "fallback":"Chance For Mobs To Be Left Handed"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(lefthanded_initial)\
    }\
  ],\
  "can_close_with_escape":true,\
  "pause":true,\
  "after_action":"close",\
  "external_title":{\
    "translate":"menu.mob_manager.misc_settings.title",\
    "fallback":"Miscellaneous"\
  },\
  "title":{\
    "translate":"menu.mob_manager.main.title",\
    "fallback":"Nice Mob Manager"\
  },\
  "yes":{\
    "label":{\
      "translate":"option.mob_manager.confirm",\
      "fallback":"Confirm"\
    },\
    "action":{\
      "type":"minecraft:dynamic/run_command",\
      "template":"$(command_template)"\
    }\
  },\
  "no":{\
    "label":{\
      "translate":"gui.back"\
    },\
    "action":{\
      "type":"minecraft:show_dialog",\
      "dialog":"mob_manager:main"\
    }\
  }\
}