  data modify storage eden:database names.village.desert.name.1 set value "Sandstone Oasis"
  data modify storage eden:database names.village.desert.name.2 set value "Dunehaven"
  data modify storage eden:database names.village.desert.name.3 set value "Scorched Sands"
  data modify storage eden:database names.village.desert.name.4 set value "Desert's Edge"
  data modify storage eden:database names.village.desert.name.5 set value "Suncrest"
  data modify storage eden:database names.village.desert.name.6 set value "Cactus Valley"
  data modify storage eden:database names.village.desert.name.7 set value "Dry Gulch"
  data modify storage eden:database names.village.desert.name.8 set value "Sunstone Village"
  data modify storage eden:database names.village.desert.name.9 set value "Mirage Hollow"
 data modify storage eden:database names.village.desert.name.10 set value "Sandspire"
 data modify storage eden:database names.village.desert.name.11 set value "Dusty Ridge"
 data modify storage eden:database names.village.desert.name.12 set value "Oasis Springs"
 data modify storage eden:database names.village.desert.name.13 set value "Heatwave Hamlet"
 data modify storage eden:database names.village.desert.name.14 set value "Sandy Shores"
 data modify storage eden:database names.village.desert.name.15 set value "Redrock"
 data modify storage eden:database names.village.desert.name.16 set value "Dustveil"
 data modify storage eden:database names.village.desert.name.17 set value "Sandbluff"
 data modify storage eden:database names.village.desert.name.18 set value "Golden Dunes"
 data modify storage eden:database names.village.desert.name.19 set value "Mirage Point"
 data modify storage eden:database names.village.desert.name.20 set value "Drywind"
 data modify storage eden:database names.village.desert.name.21 set value "Sunburnt Sands"
 data modify storage eden:database names.village.desert.name.22 set value "Sandstone Ridge"
 data modify storage eden:database names.village.desert.name.23 set value "Dunecrest"
 data modify storage eden:database names.village.desert.name.24 set value "Windswept"
 data modify storage eden:database names.village.desert.name.25 set value "Sandy Plains"
 data modify storage eden:database names.village.desert.name.26 set value "Sunchaser"
 data modify storage eden:database names.village.desert.name.27 set value "Desert Rose"
 data modify storage eden:database names.village.desert.name.28 set value "Dustfall"
 data modify storage eden:database names.village.desert.name.29 set value "Golden Mirage"
 data modify storage eden:database names.village.desert.name.30 set value "Sun's Reach"
 data modify storage eden:database names.village.desert.name.31 set value "Scorchvale"
 data modify storage eden:database names.village.desert.name.32 set value "Mesa Mirage"
 data modify storage eden:database names.village.desert.name.33 set value "Redcliff"
 data modify storage eden:database names.village.desert.name.34 set value "Oasis Ridge"
 data modify storage eden:database names.village.desert.name.35 set value "Sandshadow"
 data modify storage eden:database names.village.desert.name.36 set value "Sunburnt Valley"
 data modify storage eden:database names.village.desert.name.37 set value "Dusthill"
 data modify storage eden:database names.village.desert.name.38 set value "Sandbreeze"
 data modify storage eden:database names.village.desert.name.39 set value "Oasis Refuge"
 data modify storage eden:database names.village.desert.name.40 set value "Sunrock Village"
 data modify storage eden:database names.village.desert.name.41 set value "Dustbowl"
 data modify storage eden:database names.village.desert.name.42 set value "Dryvale"
 data modify storage eden:database names.village.desert.name.43 set value "Sandstone Flats"
 data modify storage eden:database names.village.desert.name.44 set value "Solstice Springs"
 data modify storage eden:database names.village.desert.name.45 set value "Desert Jewel"
 data modify storage eden:database names.village.desert.name.46 set value "Scorchstone"
 data modify storage eden:database names.village.desert.name.47 set value "Golden Sands"
 data modify storage eden:database names.village.desert.name.48 set value "Mirage Wells"
 data modify storage eden:database names.village.desert.name.49 set value "Heatwave Haven"
 data modify storage eden:database names.village.desert.name.50 set value "Sandshade"
 data modify storage eden:database names.village.desert.name.51 set value "Sunsear"
 data modify storage eden:database names.village.desert.name.52 set value "Dustspire"
 data modify storage eden:database names.village.desert.name.53 set value "Parched Plains"
 data modify storage eden:database names.village.desert.name.54 set value "Desert Winds"
 data modify storage eden:database names.village.desert.name.55 set value "Sandy Summit"
 data modify storage eden:database names.village.desert.name.56 set value "Golden Mirage"
 data modify storage eden:database names.village.desert.name.57 set value "Oasis Hollow"
 data modify storage eden:database names.village.desert.name.58 set value "Sunpeak"
 data modify storage eden:database names.village.desert.name.59 set value "Sandveil"
 data modify storage eden:database names.village.desert.name.60 set value "Dryrock"
 data modify storage eden:database names.village.desert.name.61 set value "Cactus Hollow"
 data modify storage eden:database names.village.desert.name.62 set value "Sunridge"
 data modify storage eden:database names.village.desert.name.63 set value "Desert Drift"
 data modify storage eden:database names.village.desert.name.64 set value "Redstone Oasis"
 data modify storage eden:database names.village.desert.name.65 set value "Dustshade"
 data modify storage eden:database names.village.desert.name.66 set value "Dune Hollow"
 data modify storage eden:database names.village.desert.name.67 set value "Heatwave Hills"
 data modify storage eden:database names.village.desert.name.68 set value "Sandstone Canyon"
 data modify storage eden:database names.village.desert.name.69 set value "Scorched Vale"
 data modify storage eden:database names.village.desert.name.70 set value "Sunlit Sands"
 data modify storage eden:database names.village.desert.name.71 set value "Dunecliff"
 data modify storage eden:database names.village.desert.name.72 set value "Mirage Meadow"
 data modify storage eden:database names.village.desert.name.73 set value "Golden Mesa"
 data modify storage eden:database names.village.desert.name.74 set value "Sunshadow"
 data modify storage eden:database names.village.desert.name.75 set value "Arid Ridge"
 data modify storage eden:database names.village.desert.name.76 set value "Drywater"
 data modify storage eden:database names.village.desert.name.77 set value "Sandy Ridge"
 data modify storage eden:database names.village.desert.name.78 set value "Heatstone"
 data modify storage eden:database names.village.desert.name.79 set value "Desert Breeze"
 data modify storage eden:database names.village.desert.name.80 set value "Oasis Flats"
 data modify storage eden:database names.village.desert.name.81 set value "Sunscar"
 data modify storage eden:database names.village.desert.name.82 set value "Sandstorm Village"
 data modify storage eden:database names.village.desert.name.83 set value "Cactus Grove"
 data modify storage eden:database names.village.desert.name.84 set value "Windstone"
 data modify storage eden:database names.village.desert.name.85 set value "Dusty Haven"
 data modify storage eden:database names.village.desert.name.86 set value "Golden Dune"
 data modify storage eden:database names.village.desert.name.87 set value "Sunveil"
 data modify storage eden:database names.village.desert.name.88 set value "Mirage Sands"
 data modify storage eden:database names.village.desert.name.89 set value "Scorched Peaks"
 data modify storage eden:database names.village.desert.name.90 set value "Sandstone Summit"
 data modify storage eden:database names.village.desert.name.91 set value "Red Dunes"
 data modify storage eden:database names.village.desert.name.92 set value "Sandtrail"
 data modify storage eden:database names.village.desert.name.93 set value "Dustrock"
 data modify storage eden:database names.village.desert.name.94 set value "Golden Oasis"
 data modify storage eden:database names.village.desert.name.95 set value "Sunburnt Bluff"
 data modify storage eden:database names.village.desert.name.96 set value "Dry Creek"
 data modify storage eden:database names.village.desert.name.97 set value "Dunepeak"
 data modify storage eden:database names.village.desert.name.98 set value "Sandcrag"
 data modify storage eden:database names.village.desert.name.99 set value "Mirage Ridge"
data modify storage eden:database names.village.desert.name.100 set value "Redstone Ravine"