  data modify storage eden:database names.village.jungle.name.1 set value "Vinehaven"
  data modify storage eden:database names.village.jungle.name.2 set value "Emerald Grove"
  data modify storage eden:database names.village.jungle.name.3 set value "Jungle's Edge"
  data modify storage eden:database names.village.jungle.name.4 set value "Wildwood"
  data modify storage eden:database names.village.jungle.name.5 set value "Canopy Crest"
  data modify storage eden:database names.village.jungle.name.6 set value "Shadowleaf"
  data modify storage eden:database names.village.jungle.name.7 set value "Vinecliff"
  data modify storage eden:database names.village.jungle.name.8 set value "Greenheart Village"
  data modify storage eden:database names.village.jungle.name.9 set value "Rainfall Ridge"
 data modify storage eden:database names.village.jungle.name.10 set value "Lushgrove"
 data modify storage eden:database names.village.jungle.name.11 set value "Treehaven"
 data modify storage eden:database names.village.jungle.name.12 set value "Jungle Hollow"
 data modify storage eden:database names.village.jungle.name.13 set value "Mossy Vale"
 data modify storage eden:database names.village.jungle.name.14 set value "Wildvine"
 data modify storage eden:database names.village.jungle.name.15 set value "Rainforest Retreat"
 data modify storage eden:database names.village.jungle.name.16 set value "Canopy Cove"
 data modify storage eden:database names.village.jungle.name.17 set value "Deepwood"
 data modify storage eden:database names.village.jungle.name.18 set value "Leafshade"
 data modify storage eden:database names.village.jungle.name.19 set value "Greenstone Village"
 data modify storage eden:database names.village.jungle.name.20 set value "Emerald Forest"
 data modify storage eden:database names.village.jungle.name.21 set value "Wildleaf"
 data modify storage eden:database names.village.jungle.name.22 set value "Junglebrook"
 data modify storage eden:database names.village.jungle.name.23 set value "Misty Canopy"
 data modify storage eden:database names.village.jungle.name.24 set value "Vinewood"
 data modify storage eden:database names.village.jungle.name.25 set value "Overgrown Hollow"
 data modify storage eden:database names.village.jungle.name.26 set value "Fernshade"
 data modify storage eden:database names.village.jungle.name.27 set value "Rainfall Hollow"
 data modify storage eden:database names.village.jungle.name.28 set value "Wildgrove"
 data modify storage eden:database names.village.jungle.name.29 set value "Leafcrest"
 data modify storage eden:database names.village.jungle.name.30 set value "Vineyard"
 data modify storage eden:database names.village.jungle.name.31 set value "Mossy Haven"
 data modify storage eden:database names.village.jungle.name.32 set value "Shaded Grove"
 data modify storage eden:database names.village.jungle.name.33 set value "Rainforest Refuge"
 data modify storage eden:database names.village.jungle.name.34 set value "Greencrest"
 data modify storage eden:database names.village.jungle.name.35 set value "Jungle Falls"
 data modify storage eden:database names.village.jungle.name.36 set value "Overgrowth"
 data modify storage eden:database names.village.jungle.name.37 set value "Misty Hollow"
 data modify storage eden:database names.village.jungle.name.38 set value "Lush Haven"
 data modify storage eden:database names.village.jungle.name.39 set value "Wildshade"
 data modify storage eden:database names.village.jungle.name.40 set value "Canopy Ridge"
 data modify storage eden:database names.village.jungle.name.41 set value "Deepgrove"
 data modify storage eden:database names.village.jungle.name.42 set value "Leaffall"
 data modify storage eden:database names.village.jungle.name.43 set value "Mosswood"
 data modify storage eden:database names.village.jungle.name.44 set value "Greenleaf Village"
 data modify storage eden:database names.village.jungle.name.45 set value "Rainshadow"
 data modify storage eden:database names.village.jungle.name.46 set value "Fernhill"
 data modify storage eden:database names.village.jungle.name.47 set value "Jungleveil"
 data modify storage eden:database names.village.jungle.name.48 set value "Vinecrest"
 data modify storage eden:database names.village.jungle.name.49 set value "Emerald Falls"
 data modify storage eden:database names.village.jungle.name.50 set value "Overgrown Vale"
 data modify storage eden:database names.village.jungle.name.51 set value "Leafy Hollow"
 data modify storage eden:database names.village.jungle.name.52 set value "Shadowvine"
 data modify storage eden:database names.village.jungle.name.53 set value "Lushwood"
 data modify storage eden:database names.village.jungle.name.54 set value "Junglebrook"
 data modify storage eden:database names.village.jungle.name.55 set value "Greenstone Hollow"
 data modify storage eden:database names.village.jungle.name.56 set value "Mossy Glen"
 data modify storage eden:database names.village.jungle.name.57 set value "Wildwood Hollow"
 data modify storage eden:database names.village.jungle.name.58 set value "Rainwood"
 data modify storage eden:database names.village.jungle.name.59 set value "Deepshade"
 data modify storage eden:database names.village.jungle.name.60 set value "Canopy Falls"
 data modify storage eden:database names.village.jungle.name.61 set value "Jungle Ridge"
 data modify storage eden:database names.village.jungle.name.62 set value "Greenvale"
 data modify storage eden:database names.village.jungle.name.63 set value "Overgrown Grove"
 data modify storage eden:database names.village.jungle.name.64 set value "Viney Hollow"
 data modify storage eden:database names.village.jungle.name.65 set value "Mistveil"
 data modify storage eden:database names.village.jungle.name.66 set value "Leafstone Village"
 data modify storage eden:database names.village.jungle.name.67 set value "Rainforest Hollow"
 data modify storage eden:database names.village.jungle.name.68 set value "Wildhaven"
 data modify storage eden:database names.village.jungle.name.69 set value "Mosscliff"
 data modify storage eden:database names.village.jungle.name.70 set value "Greenstone"
 data modify storage eden:database names.village.jungle.name.71 set value "Fernshade Village"
 data modify storage eden:database names.village.jungle.name.72 set value "Vineglen"
 data modify storage eden:database names.village.jungle.name.73 set value "Jungle Heart"
 data modify storage eden:database names.village.jungle.name.74 set value "Lushcrest"
 data modify storage eden:database names.village.jungle.name.75 set value "Leafhaven"
 data modify storage eden:database names.village.jungle.name.76 set value "Rainy Vale"
 data modify storage eden:database names.village.jungle.name.77 set value "Wildleaf Village"
 data modify storage eden:database names.village.jungle.name.78 set value "Shadow Falls"
 data modify storage eden:database names.village.jungle.name.79 set value "Canopy Haven"
 data modify storage eden:database names.village.jungle.name.80 set value "Greenstone Ridge"
 data modify storage eden:database names.village.jungle.name.81 set value "Overgrown Refuge"
 data modify storage eden:database names.village.jungle.name.82 set value "Vinehaven"
 data modify storage eden:database names.village.jungle.name.83 set value "Mossy Ridge"
 data modify storage eden:database names.village.jungle.name.84 set value "Rainforest Vale"
 data modify storage eden:database names.village.jungle.name.85 set value "Deepwood Village"
 data modify storage eden:database names.village.jungle.name.86 set value "Wildgrove Hollow"
 data modify storage eden:database names.village.jungle.name.87 set value "Leafstone Hollow"
 data modify storage eden:database names.village.jungle.name.88 set value "Jungle Crest"
 data modify storage eden:database names.village.jungle.name.89 set value "Vinehill"
 data modify storage eden:database names.village.jungle.name.90 set value "Fernshade Ridge"
 data modify storage eden:database names.village.jungle.name.91 set value "Misty Vale"
 data modify storage eden:database names.village.jungle.name.92 set value "Lushleaf"
 data modify storage eden:database names.village.jungle.name.93 set value "Greenstone Glen"
 data modify storage eden:database names.village.jungle.name.94 set value "Overgrown Hollow"
 data modify storage eden:database names.village.jungle.name.95 set value "Rainy Hollow"
 data modify storage eden:database names.village.jungle.name.96 set value "Wildvine Village"
 data modify storage eden:database names.village.jungle.name.97 set value "Canopy Glen"
 data modify storage eden:database names.village.jungle.name.98 set value "Mossy Vale Village"
 data modify storage eden:database names.village.jungle.name.99 set value "Shadowleaf Ridge"
data modify storage eden:database names.village.jungle.name.100 set value "Junglewood"
data modify storage eden:database names.village.jungle.name.101 set value "Verdure"