  data modify storage eden:database names.village.savanna.name.1 set value "Lion's Den"
  data modify storage eden:database names.village.savanna.name.2 set value "Acacia Grove"
  data modify storage eden:database names.village.savanna.name.3 set value "Sunspire"
  data modify storage eden:database names.village.savanna.name.4 set value "Savannah Ridge"
  data modify storage eden:database names.village.savanna.name.5 set value "Golden Sands"
  data modify storage eden:database names.village.savanna.name.6 set value "Thornwood"
  data modify storage eden:database names.village.savanna.name.7 set value "Embergrass"
  data modify storage eden:database names.village.savanna.name.8 set value "Sunset Plains"
  data modify storage eden:database names.village.savanna.name.9 set value "Redstone Village"
 data modify storage eden:database names.village.savanna.name.10 set value "Wildfire"
 data modify storage eden:database names.village.savanna.name.11 set value "Dryleaf"
 data modify storage eden:database names.village.savanna.name.12 set value "Acacia Falls"
 data modify storage eden:database names.village.savanna.name.13 set value "Windthorn"
 data modify storage eden:database names.village.savanna.name.14 set value "Cinderwood"
 data modify storage eden:database names.village.savanna.name.15 set value "Goldenbush"
 data modify storage eden:database names.village.savanna.name.16 set value "Sunflare"
 data modify storage eden:database names.village.savanna.name.17 set value "Lionheart Village"
 data modify storage eden:database names.village.savanna.name.18 set value "Savannah's Edge"
 data modify storage eden:database names.village.savanna.name.19 set value "Dustwind"
 data modify storage eden:database names.village.savanna.name.20 set value "Acacia Hollow"
 data modify storage eden:database names.village.savanna.name.21 set value "Scorchwood"
 data modify storage eden:database names.village.savanna.name.22 set value "Firethorn"
 data modify storage eden:database names.village.savanna.name.23 set value "Droughtland"
 data modify storage eden:database names.village.savanna.name.24 set value "Sunpeak"
 data modify storage eden:database names.village.savanna.name.25 set value "Wildgrass"
 data modify storage eden:database names.village.savanna.name.26 set value "Dusty Mesa"
 data modify storage eden:database names.village.savanna.name.27 set value "Ember Ridge"
 data modify storage eden:database names.village.savanna.name.28 set value "Acacia Springs"
 data modify storage eden:database names.village.savanna.name.29 set value "Goldenthorn"
 data modify storage eden:database names.village.savanna.name.30 set value "Sunset Valley"
 data modify storage eden:database names.village.savanna.name.31 set value "Windy Mesa"
 data modify storage eden:database names.village.savanna.name.32 set value "Firegrass"
 data modify storage eden:database names.village.savanna.name.33 set value "Lionstone"
 data modify storage eden:database names.village.savanna.name.34 set value "Dusty Hollow"
 data modify storage eden:database names.village.savanna.name.35 set value "Redclay Village"
 data modify storage eden:database names.village.savanna.name.36 set value "Golden Ridge"
 data modify storage eden:database names.village.savanna.name.37 set value "Acacia Vale"
 data modify storage eden:database names.village.savanna.name.38 set value "Scorch Plains"
 data modify storage eden:database names.village.savanna.name.39 set value "Cinderbush"
 data modify storage eden:database names.village.savanna.name.40 set value "Savanna Heights"
 data modify storage eden:database names.village.savanna.name.41 set value "Dustveil"
 data modify storage eden:database names.village.savanna.name.42 set value "Embercliff"
 data modify storage eden:database names.village.savanna.name.43 set value "Sunstone Village"
 data modify storage eden:database names.village.savanna.name.44 set value "Wildthorn"
 data modify storage eden:database names.village.savanna.name.45 set value "Firestone"
 data modify storage eden:database names.village.savanna.name.46 set value "Savannah Hollow"
 data modify storage eden:database names.village.savanna.name.47 set value "Thornfield"
 data modify storage eden:database names.village.savanna.name.48 set value "Dusty Ridge"
 data modify storage eden:database names.village.savanna.name.49 set value "Lion's Roar"
 data modify storage eden:database names.village.savanna.name.50 set value "Redleaf"
 data modify storage eden:database names.village.savanna.name.51 set value "Golden Mesa"
 data modify storage eden:database names.village.savanna.name.52 set value "Emberfall"
 data modify storage eden:database names.village.savanna.name.53 set value "Windcliff"
 data modify storage eden:database names.village.savanna.name.54 set value "Acacia Mesa"
 data modify storage eden:database names.village.savanna.name.55 set value "Scorched Earth"
 data modify storage eden:database names.village.savanna.name.56 set value "Firevale"
 data modify storage eden:database names.village.savanna.name.57 set value "Sunridge"
 data modify storage eden:database names.village.savanna.name.58 set value "Wildfire Village"
 data modify storage eden:database names.village.savanna.name.59 set value "Dusty Vale"
 data modify storage eden:database names.village.savanna.name.60 set value "Lion's Crest"
 data modify storage eden:database names.village.savanna.name.61 set value "Thornshade"
 data modify storage eden:database names.village.savanna.name.62 set value "Golden Plains"
 data modify storage eden:database names.village.savanna.name.63 set value "Acacia Ridge"
 data modify storage eden:database names.village.savanna.name.64 set value "Cinderthorn"
 data modify storage eden:database names.village.savanna.name.65 set value "Savannah Breeze"
 data modify storage eden:database names.village.savanna.name.66 set value "Sunstone Hollow"
 data modify storage eden:database names.village.savanna.name.67 set value "Wildmane"
 data modify storage eden:database names.village.savanna.name.68 set value "Firecrest"
 data modify storage eden:database names.village.savanna.name.69 set value "Dustfire"
 data modify storage eden:database names.village.savanna.name.70 set value "Redstone Ridge"
 data modify storage eden:database names.village.savanna.name.71 set value "Golden Acacia"
 data modify storage eden:database names.village.savanna.name.72 set value "Ember Hollow"
 data modify storage eden:database names.village.savanna.name.73 set value "Lion's Gate"
 data modify storage eden:database names.village.savanna.name.74 set value "Windthorn Village"
 data modify storage eden:database names.village.savanna.name.75 set value "Scorched Ridge"
 data modify storage eden:database names.village.savanna.name.76 set value "Acacia Grove"
 data modify storage eden:database names.village.savanna.name.77 set value "Firepeak"
 data modify storage eden:database names.village.savanna.name.78 set value "Sunset Ridge"
 data modify storage eden:database names.village.savanna.name.79 set value "Dusty Grove"
 data modify storage eden:database names.village.savanna.name.80 set value "Thornvale"
 data modify storage eden:database names.village.savanna.name.81 set value "Golden Horizon"
 data modify storage eden:database names.village.savanna.name.82 set value "Acacia Bluff"
 data modify storage eden:database names.village.savanna.name.83 set value "Emberstone"
 data modify storage eden:database names.village.savanna.name.84 set value "Wild Savannah"
 data modify storage eden:database names.village.savanna.name.85 set value "Suncliff"
 data modify storage eden:database names.village.savanna.name.86 set value "Lion's Bluff"
 data modify storage eden:database names.village.savanna.name.87 set value "Dusty Trail"
 data modify storage eden:database names.village.savanna.name.88 set value "Goldenridge"
 data modify storage eden:database names.village.savanna.name.89 set value "Scorchbush"
 data modify storage eden:database names.village.savanna.name.90 set value "Firethorn Hollow"
 data modify storage eden:database names.village.savanna.name.91 set value "Acacia Rise"
 data modify storage eden:database names.village.savanna.name.92 set value "Ember Vale"
 data modify storage eden:database names.village.savanna.name.93 set value "Savannah Springs"
 data modify storage eden:database names.village.savanna.name.94 set value "Wildthorn Village"
 data modify storage eden:database names.village.savanna.name.95 set value "Cindercrest"
 data modify storage eden:database names.village.savanna.name.96 set value "Sunset Mesa"
 data modify storage eden:database names.village.savanna.name.97 set value "Windstone"
 data modify storage eden:database names.village.savanna.name.98 set value "Lion's Peak"
 data modify storage eden:database names.village.savanna.name.99 set value "Dusty Plains"
data modify storage eden:database names.village.savanna.name.100 set value "Goldenleaf"