  data modify storage eden:database names.village.snow.name.1 set value "Frosthaven"
  data modify storage eden:database names.village.snow.name.2 set value "Snowfall Village"
  data modify storage eden:database names.village.snow.name.3 set value "Icewind"
  data modify storage eden:database names.village.snow.name.4 set value "Wintercrest"
  data modify storage eden:database names.village.snow.name.5 set value "Glacial Hollow"
  data modify storage eden:database names.village.snow.name.6 set value "Frostwood"
  data modify storage eden:database names.village.snow.name.7 set value "Icespire"
  data modify storage eden:database names.village.snow.name.8 set value "Snowpeak"
  data modify storage eden:database names.village.snow.name.9 set value "Frostfield"
 data modify storage eden:database names.village.snow.name.10 set value "Wintervale"
 data modify storage eden:database names.village.snow.name.11 set value "Glacier Ridge"
 data modify storage eden:database names.village.snow.name.12 set value "Chillbrook"
 data modify storage eden:database names.village.snow.name.13 set value "Frostbite Village"
 data modify storage eden:database names.village.snow.name.14 set value "Snowdrift"
 data modify storage eden:database names.village.snow.name.15 set value "Iceveil"
 data modify storage eden:database names.village.snow.name.16 set value "Winterstone"
 data modify storage eden:database names.village.snow.name.17 set value "Frosty Hollow"
 data modify storage eden:database names.village.snow.name.18 set value "Snowy Vale"
 data modify storage eden:database names.village.snow.name.19 set value "Icecliff"
 data modify storage eden:database names.village.snow.name.20 set value "Coldstone Village"
 data modify storage eden:database names.village.snow.name.21 set value "Frostgate"
 data modify storage eden:database names.village.snow.name.22 set value "Crystal Hollow"
 data modify storage eden:database names.village.snow.name.23 set value "Wintergate"
 data modify storage eden:database names.village.snow.name.24 set value "Snowfall Ridge"
 data modify storage eden:database names.village.snow.name.25 set value "Icebound"
 data modify storage eden:database names.village.snow.name.26 set value "Frostveil"
 data modify storage eden:database names.village.snow.name.27 set value "Glacier Falls"
 data modify storage eden:database names.village.snow.name.28 set value "Coldbrook"
 data modify storage eden:database names.village.snow.name.29 set value "Frostspire"
 data modify storage eden:database names.village.snow.name.30 set value "Snowy Hollow"
 data modify storage eden:database names.village.snow.name.31 set value "Wintergrove"
 data modify storage eden:database names.village.snow.name.32 set value "Icepeak"
 data modify storage eden:database names.village.snow.name.33 set value "Frostvale"
 data modify storage eden:database names.village.snow.name.34 set value "Snowmelt"
 data modify storage eden:database names.village.snow.name.35 set value "Crystal Vale"
 data modify storage eden:database names.village.snow.name.36 set value "Winterfell"
 data modify storage eden:database names.village.snow.name.37 set value "Snowshade"
 data modify storage eden:database names.village.snow.name.38 set value "Icy Hollow"
 data modify storage eden:database names.village.snow.name.39 set value "Frostwood Grove"
 data modify storage eden:database names.village.snow.name.40 set value "Snowfield"
 data modify storage eden:database names.village.snow.name.41 set value "Iceglade"
 data modify storage eden:database names.village.snow.name.42 set value "Chillstone"
 data modify storage eden:database names.village.snow.name.43 set value "Frosty Ridge"
 data modify storage eden:database names.village.snow.name.44 set value "Snowcrest"
 data modify storage eden:database names.village.snow.name.45 set value "Winterpine"
 data modify storage eden:database names.village.snow.name.46 set value "Glacial Crest"
 data modify storage eden:database names.village.snow.name.47 set value "Frostbrook"
 data modify storage eden:database names.village.snow.name.48 set value "Icehaven"
 data modify storage eden:database names.village.snow.name.49 set value "Snowveil Village"
 data modify storage eden:database names.village.snow.name.50 set value "Winterbluff"
 data modify storage eden:database names.village.snow.name.51 set value "Crystal Ridge"
 data modify storage eden:database names.village.snow.name.52 set value "Frostgrove"
 data modify storage eden:database names.village.snow.name.53 set value "Snowbound"
 data modify storage eden:database names.village.snow.name.54 set value "Icefall"
 data modify storage eden:database names.village.snow.name.55 set value "Wintershade"
 data modify storage eden:database names.village.snow.name.56 set value "Frostcliff"
 data modify storage eden:database names.village.snow.name.57 set value "Snowheart"
 data modify storage eden:database names.village.snow.name.58 set value "Icewood"
 data modify storage eden:database names.village.snow.name.59 set value "Winterwind"
 data modify storage eden:database names.village.snow.name.60 set value "Froststone"
 data modify storage eden:database names.village.snow.name.61 set value "Snowy Pines"
 data modify storage eden:database names.village.snow.name.62 set value "Glacier Hollow"
 data modify storage eden:database names.village.snow.name.63 set value "Chillwind"
 data modify storage eden:database names.village.snow.name.64 set value "Icepeak Village"
 data modify storage eden:database names.village.snow.name.65 set value "Frostlake"
 data modify storage eden:database names.village.snow.name.66 set value "Snowbluff"
 data modify storage eden:database names.village.snow.name.67 set value "Wintergate Village"
 data modify storage eden:database names.village.snow.name.68 set value "Crystal Snow"
 data modify storage eden:database names.village.snow.name.69 set value "Frostpine"
 data modify storage eden:database names.village.snow.name.70 set value "Snowstone"
 data modify storage eden:database names.village.snow.name.71 set value "Icefall Village"
 data modify storage eden:database names.village.snow.name.72 set value "Frostlight"
 data modify storage eden:database names.village.snow.name.73 set value "Snowglade"
 data modify storage eden:database names.village.snow.name.74 set value "Winterhaven"
 data modify storage eden:database names.village.snow.name.75 set value "Frostpeak"
 data modify storage eden:database names.village.snow.name.76 set value "Icy Ridge"
 data modify storage eden:database names.village.snow.name.77 set value "Snowshadow"
 data modify storage eden:database names.village.snow.name.78 set value "Crystal Hollow Village"
 data modify storage eden:database names.village.snow.name.79 set value "Frostwood Village"
 data modify storage eden:database names.village.snow.name.80 set value "Wintermelt"
 data modify storage eden:database names.village.snow.name.81 set value "Snowveil Ridge"
 data modify storage eden:database names.village.snow.name.82 set value "Iceheart"
 data modify storage eden:database names.village.snow.name.83 set value "Frostvale Village"
 data modify storage eden:database names.village.snow.name.84 set value "Snowbound Hollow"
 data modify storage eden:database names.village.snow.name.85 set value "Winterstone Village"
 data modify storage eden:database names.village.snow.name.86 set value "Glacier Peak"
 data modify storage eden:database names.village.snow.name.87 set value "Snowveil Crest"
 data modify storage eden:database names.village.snow.name.88 set value "Icegate"
 data modify storage eden:database names.village.snow.name.89 set value "Frostfire"
 data modify storage eden:database names.village.snow.name.90 set value "Snowpine"
 data modify storage eden:database names.village.snow.name.91 set value "Winterspire"
 data modify storage eden:database names.village.snow.name.92 set value "Icehaven Village"
 data modify storage eden:database names.village.snow.name.93 set value "Frostbluff"
 data modify storage eden:database names.village.snow.name.94 set value "Snowridge"
 data modify storage eden:database names.village.snow.name.95 set value "Crystal Hollow Ridge"
 data modify storage eden:database names.village.snow.name.96 set value "Winterstone Hollow"
 data modify storage eden:database names.village.snow.name.97 set value "Frostveil Hollow"
 data modify storage eden:database names.village.snow.name.98 set value "Snowbound Vale"
 data modify storage eden:database names.village.snow.name.99 set value "Icebound Ridge"
data modify storage eden:database names.village.snow.name.100 set value "Winterlight"