  data modify storage eden:database names.village.swamp.name.1 set value "Mirehaven"
  data modify storage eden:database names.village.swamp.name.2 set value "Marshwood"
  data modify storage eden:database names.village.swamp.name.3 set value "Bogshadow"
  data modify storage eden:database names.village.swamp.name.4 set value "Willow Hollow"
  data modify storage eden:database names.village.swamp.name.5 set value "Murkstone"
  data modify storage eden:database names.village.swamp.name.6 set value "Blackwater"
  data modify storage eden:database names.village.swamp.name.7 set value "Swamproot"
  data modify storage eden:database names.village.swamp.name.8 set value "Darkwater Village"
  data modify storage eden:database names.village.swamp.name.9 set value "Mistwood"
 data modify storage eden:database names.village.swamp.name.10 set value "Soggy Hollow"
 data modify storage eden:database names.village.swamp.name.11 set value "Marshlight"
 data modify storage eden:database names.village.swamp.name.12 set value "Creeping Vine"
 data modify storage eden:database names.village.swamp.name.13 set value "Fogbrook"
 data modify storage eden:database names.village.swamp.name.14 set value "Brackwater"
 data modify storage eden:database names.village.swamp.name.15 set value "Slimeveil"
 data modify storage eden:database names.village.swamp.name.16 set value "Muddy Waters"
 data modify storage eden:database names.village.swamp.name.17 set value "Mangrove Hollow"
 data modify storage eden:database names.village.swamp.name.18 set value "Swamp's Edge"
 data modify storage eden:database names.village.swamp.name.19 set value "Duskmire"
 data modify storage eden:database names.village.swamp.name.20 set value "Mossy Glade"
 data modify storage eden:database names.village.swamp.name.21 set value "Mudstone"
 data modify storage eden:database names.village.swamp.name.22 set value "Vinecliff"
 data modify storage eden:database names.village.swamp.name.23 set value "Misty Marsh"
 data modify storage eden:database names.village.swamp.name.24 set value "Bogmoor"
 data modify storage eden:database names.village.swamp.name.25 set value "Sogwood"
 data modify storage eden:database names.village.swamp.name.26 set value "Crooked Hollow"
 data modify storage eden:database names.village.swamp.name.27 set value "Marshveil"
 data modify storage eden:database names.village.swamp.name.28 set value "Murky Vale"
 data modify storage eden:database names.village.swamp.name.29 set value "Sludgewood"
 data modify storage eden:database names.village.swamp.name.30 set value "Darkfen"
 data modify storage eden:database names.village.swamp.name.31 set value "Wetlands Village"
 data modify storage eden:database names.village.swamp.name.32 set value "Foulwater"
 data modify storage eden:database names.village.swamp.name.33 set value "Swamproot Hollow"
 data modify storage eden:database names.village.swamp.name.34 set value "Muddy Hollow"
 data modify storage eden:database names.village.swamp.name.35 set value "Frogsong"
 data modify storage eden:database names.village.swamp.name.36 set value "Grimwater"
 data modify storage eden:database names.village.swamp.name.37 set value "Gloomy Mire"
 data modify storage eden:database names.village.swamp.name.38 set value "Mossfield"
 data modify storage eden:database names.village.swamp.name.39 set value "Thicket Hollow"
 data modify storage eden:database names.village.swamp.name.40 set value "Quagmire Village"
 data modify storage eden:database names.village.swamp.name.41 set value "Fogveil"
 data modify storage eden:database names.village.swamp.name.42 set value "Soggy Marsh"
 data modify storage eden:database names.village.swamp.name.43 set value "Fenwood"
 data modify storage eden:database names.village.swamp.name.44 set value "Rooted Hollow"
 data modify storage eden:database names.village.swamp.name.45 set value "Marshshadow"
 data modify storage eden:database names.village.swamp.name.46 set value "Blackmire"
 data modify storage eden:database names.village.swamp.name.47 set value "Bogside"
 data modify storage eden:database names.village.swamp.name.48 set value "Dreadwater"
 data modify storage eden:database names.village.swamp.name.49 set value "Slimebrook"
 data modify storage eden:database names.village.swamp.name.50 set value "Quagmire Hollow"
 data modify storage eden:database names.village.swamp.name.51 set value "Mudcliff"
 data modify storage eden:database names.village.swamp.name.52 set value "Gloomroot"
 data modify storage eden:database names.village.swamp.name.53 set value "Murkwood"
 data modify storage eden:database names.village.swamp.name.54 set value "Creeping Mire"
 data modify storage eden:database names.village.swamp.name.55 set value "Misty Hollow"
 data modify storage eden:database names.village.swamp.name.56 set value "Bramble Marsh"
 data modify storage eden:database names.village.swamp.name.57 set value "Vinewood"
 data modify storage eden:database names.village.swamp.name.58 set value "Bogshade"
 data modify storage eden:database names.village.swamp.name.59 set value "Swampstone"
 data modify storage eden:database names.village.swamp.name.60 set value "Marshfog"
 data modify storage eden:database names.village.swamp.name.61 set value "Wetland Vale"
 data modify storage eden:database names.village.swamp.name.62 set value "Duskwater"
 data modify storage eden:database names.village.swamp.name.63 set value "Mudveil"
 data modify storage eden:database names.village.swamp.name.64 set value "Shadowfen"
 data modify storage eden:database names.village.swamp.name.65 set value "Murky Waters"
 data modify storage eden:database names.village.swamp.name.66 set value "Slimehaven"
 data modify storage eden:database names.village.swamp.name.67 set value "Willow Marsh"
 data modify storage eden:database names.village.swamp.name.68 set value "Crooked Vale"
 data modify storage eden:database names.village.swamp.name.69 set value "Soggy Bog"
 data modify storage eden:database names.village.swamp.name.70 set value "Grimroot"
 data modify storage eden:database names.village.swamp.name.71 set value "Marshfall"
 data modify storage eden:database names.village.swamp.name.72 set value "Bogwood"
 data modify storage eden:database names.village.swamp.name.73 set value "Mistveil"
 data modify storage eden:database names.village.swamp.name.74 set value "Foulfen"
 data modify storage eden:database names.village.swamp.name.75 set value "Swamp's Breath"
 data modify storage eden:database names.village.swamp.name.76 set value "Mangrove Marsh"
 data modify storage eden:database names.village.swamp.name.77 set value "Murkbrook"
 data modify storage eden:database names.village.swamp.name.78 set value "Slimehill"
 data modify storage eden:database names.village.swamp.name.79 set value "Marshmire"
 data modify storage eden:database names.village.swamp.name.80 set value "Quagmire Ridge"
 data modify storage eden:database names.village.swamp.name.81 set value "Blackfen"
 data modify storage eden:database names.village.swamp.name.82 set value "Muddy Mire"
 data modify storage eden:database names.village.swamp.name.83 set value "Frogswamp"
 data modify storage eden:database names.village.swamp.name.84 set value "Gloomy Vale"
 data modify storage eden:database names.village.swamp.name.85 set value "Mossmire"
 data modify storage eden:database names.village.swamp.name.86 set value "Rooted Marsh"
 data modify storage eden:database names.village.swamp.name.87 set value "Foggy Hollow"
 data modify storage eden:database names.village.swamp.name.88 set value "Swampveil"
 data modify storage eden:database names.village.swamp.name.89 set value "Dreadmire"
 data modify storage eden:database names.village.swamp.name.90 set value "Sludgebrook"
 data modify storage eden:database names.village.swamp.name.91 set value "Creeping Vale"
 data modify storage eden:database names.village.swamp.name.92 set value "Willowwood"
 data modify storage eden:database names.village.swamp.name.93 set value "Bramble Bog"
 data modify storage eden:database names.village.swamp.name.94 set value "Misty Fen"
 data modify storage eden:database names.village.swamp.name.95 set value "Soggy Hollow Village"
 data modify storage eden:database names.village.swamp.name.96 set value "Marshshade"
 data modify storage eden:database names.village.swamp.name.97 set value "Murkveil"
 data modify storage eden:database names.village.swamp.name.98 set value "Slime Vale"
 data modify storage eden:database names.village.swamp.name.99 set value "Thicket Mire"
data modify storage eden:database names.village.swamp.name.100 set value "Shadowmire"
data modify storage eden:database names.village.swamp.name.101 set value "Snuggledown"