  data modify storage eden:database names.village.taiga.name.1 set value "Pinewatch"
  data modify storage eden:database names.village.taiga.name.2 set value "Frostpine"
  data modify storage eden:database names.village.taiga.name.3 set value "Timberwood"
  data modify storage eden:database names.village.taiga.name.4 set value "Pinecrest"
  data modify storage eden:database names.village.taiga.name.5 set value "Snowy Grove"
  data modify storage eden:database names.village.taiga.name.6 set value "Frostfall"
  data modify storage eden:database names.village.taiga.name.7 set value "Winterwood"
  data modify storage eden:database names.village.taiga.name.8 set value "Coldwind Village"
  data modify storage eden:database names.village.taiga.name.9 set value "Evergreen Hollow"
 data modify storage eden:database names.village.taiga.name.10 set value "Pinebrook"
 data modify storage eden:database names.village.taiga.name.11 set value "Frostvale"
 data modify storage eden:database names.village.taiga.name.12 set value "Timber Ridge"
 data modify storage eden:database names.village.taiga.name.13 set value "Chillwood"
 data modify storage eden:database names.village.taiga.name.14 set value "Pinewood Hollow"
 data modify storage eden:database names.village.taiga.name.15 set value "Snowveil Village"
 data modify storage eden:database names.village.taiga.name.16 set value "Cedar Hollow"
 data modify storage eden:database names.village.taiga.name.17 set value "Frostcliff"
 data modify storage eden:database names.village.taiga.name.18 set value "Timber Vale"
 data modify storage eden:database names.village.taiga.name.19 set value "Coldbrook"
 data modify storage eden:database names.village.taiga.name.20 set value "Snowdrift"
 data modify storage eden:database names.village.taiga.name.21 set value "Pinehill"
 data modify storage eden:database names.village.taiga.name.22 set value "Frostwood"
 data modify storage eden:database names.village.taiga.name.23 set value "Cedar Ridge"
 data modify storage eden:database names.village.taiga.name.24 set value "Winterpine"
 data modify storage eden:database names.village.taiga.name.25 set value "Pinehaven"
 data modify storage eden:database names.village.taiga.name.26 set value "Chillstone"
 data modify storage eden:database names.village.taiga.name.27 set value "Timbercrest"
 data modify storage eden:database names.village.taiga.name.28 set value "Coldstone Village"
 data modify storage eden:database names.village.taiga.name.29 set value "Frostpeak"
 data modify storage eden:database names.village.taiga.name.30 set value "Pinegrove"
 data modify storage eden:database names.village.taiga.name.31 set value "Snowbound"
 data modify storage eden:database names.village.taiga.name.32 set value "Cedarcrest"
 data modify storage eden:database names.village.taiga.name.33 set value "Frostshade"
 data modify storage eden:database names.village.taiga.name.34 set value "Timberfall"
 data modify storage eden:database names.village.taiga.name.35 set value "Pineveil"
 data modify storage eden:database names.village.taiga.name.36 set value "Wintervale"
 data modify storage eden:database names.village.taiga.name.37 set value "Frostburn"
 data modify storage eden:database names.village.taiga.name.38 set value "Snowy Pines"
 data modify storage eden:database names.village.taiga.name.39 set value "Timber Hollow"
 data modify storage eden:database names.village.taiga.name.40 set value "Coldshade"
 data modify storage eden:database names.village.taiga.name.41 set value "Pinebluff"
 data modify storage eden:database names.village.taiga.name.42 set value "Frostgate"
 data modify storage eden:database names.village.taiga.name.43 set value "Cedarbrook"
 data modify storage eden:database names.village.taiga.name.44 set value "Snowspire"
 data modify storage eden:database names.village.taiga.name.45 set value "Pineheart"
 data modify storage eden:database names.village.taiga.name.46 set value "Timberveil"
 data modify storage eden:database names.village.taiga.name.47 set value "Frostwood Grove"
 data modify storage eden:database names.village.taiga.name.48 set value "Cold Hollow"
 data modify storage eden:database names.village.taiga.name.49 set value "Snowridge"
 data modify storage eden:database names.village.taiga.name.50 set value "Cedarwood"
 data modify storage eden:database names.village.taiga.name.51 set value "Wintergrove"
 data modify storage eden:database names.village.taiga.name.52 set value "Frostbluff"
 data modify storage eden:database names.village.taiga.name.53 set value "Pineview"
 data modify storage eden:database names.village.taiga.name.54 set value "Timbertrail"
 data modify storage eden:database names.village.taiga.name.55 set value "Snowglen"
 data modify storage eden:database names.village.taiga.name.56 set value "Frostwood Village"
 data modify storage eden:database names.village.taiga.name.57 set value "Pinehaven Ridge"
 data modify storage eden:database names.village.taiga.name.58 set value "Coldpine"
 data modify storage eden:database names.village.taiga.name.59 set value "Timberwood Hollow"
 data modify storage eden:database names.village.taiga.name.60 set value "Snowy Hollow"
 data modify storage eden:database names.village.taiga.name.61 set value "Cedarfall"
 data modify storage eden:database names.village.taiga.name.62 set value "Frosthaven"
 data modify storage eden:database names.village.taiga.name.63 set value "Pinegate"
 data modify storage eden:database names.village.taiga.name.64 set value "Timberpeak"
 data modify storage eden:database names.village.taiga.name.65 set value "Snowshadow"
 data modify storage eden:database names.village.taiga.name.66 set value "Piney Hollow"
 data modify storage eden:database names.village.taiga.name.67 set value "Frostforge"
 data modify storage eden:database names.village.taiga.name.68 set value "Winterbluff"
 data modify storage eden:database names.village.taiga.name.69 set value "Coldspire"
 data modify storage eden:database names.village.taiga.name.70 set value "Timberbrook"
 data modify storage eden:database names.village.taiga.name.71 set value "Snowstone Village"
 data modify storage eden:database names.village.taiga.name.72 set value "Frostpine Hollow"
 data modify storage eden:database names.village.taiga.name.73 set value "Pinevale"
 data modify storage eden:database names.village.taiga.name.74 set value "Cedarvale"
 data modify storage eden:database names.village.taiga.name.75 set value "Timberburn"
 data modify storage eden:database names.village.taiga.name.76 set value "Frostglade"
 data modify storage eden:database names.village.taiga.name.77 set value "Coldheart"
 data modify storage eden:database names.village.taiga.name.78 set value "Snowwood"
 data modify storage eden:database names.village.taiga.name.79 set value "Pinehaven Vale"
 data modify storage eden:database names.village.taiga.name.80 set value "Timberwatch"
 data modify storage eden:database names.village.taiga.name.81 set value "Frostview"
 data modify storage eden:database names.village.taiga.name.82 set value "Snowveil Ridge"
 data modify storage eden:database names.village.taiga.name.83 set value "Pinewood Ridge"
 data modify storage eden:database names.village.taiga.name.84 set value "Cedarpeak"
 data modify storage eden:database names.village.taiga.name.85 set value "Wintercliff"
 data modify storage eden:database names.village.taiga.name.86 set value "Coldridge"
 data modify storage eden:database names.village.taiga.name.87 set value "Timberfall Village"
 data modify storage eden:database names.village.taiga.name.88 set value "Frostpine Grove"
 data modify storage eden:database names.village.taiga.name.89 set value "Snowgate"
 data modify storage eden:database names.village.taiga.name.90 set value "Pinecrest Village"
 data modify storage eden:database names.village.taiga.name.91 set value "Timberpine"
 data modify storage eden:database names.village.taiga.name.92 set value "Froststone"
 data modify storage eden:database names.village.taiga.name.93 set value "Coldview"
 data modify storage eden:database names.village.taiga.name.94 set value "Snowcrest"
 data modify storage eden:database names.village.taiga.name.95 set value "Pinehill Village"
 data modify storage eden:database names.village.taiga.name.96 set value "Cedarstone"
 data modify storage eden:database names.village.taiga.name.97 set value "Timberglade"
 data modify storage eden:database names.village.taiga.name.98 set value "Frostveil Village"
 data modify storage eden:database names.village.taiga.name.99 set value "Snowfall Ridge"
data modify storage eden:database names.village.taiga.name.100 set value "Pinewatch Village"