  data modify storage eden:database names.rarity_mobs.first.1 set value Aelar
  data modify storage eden:database names.rarity_mobs.first.2 set value Alden
  data modify storage eden:database names.rarity_mobs.first.3 set value Alaric
  data modify storage eden:database names.rarity_mobs.first.4 set value Alarik
  data modify storage eden:database names.rarity_mobs.first.5 set value Alastair
  data modify storage eden:database names.rarity_mobs.first.6 set value Aldric
  data modify storage eden:database names.rarity_mobs.first.7 set value Amara
  data modify storage eden:database names.rarity_mobs.first.8 set value Arian
  data modify storage eden:database names.rarity_mobs.first.9 set value Aric
 data modify storage eden:database names.rarity_mobs.first.10 set value Arion
 data modify storage eden:database names.rarity_mobs.first.11 set value Arlo
 data modify storage eden:database names.rarity_mobs.first.12 set value Asher
 data modify storage eden:database names.rarity_mobs.first.13 set value Aurelia
 data modify storage eden:database names.rarity_mobs.first.14 set value Azrael
 data modify storage eden:database names.rarity_mobs.first.15 set value Bastian
 data modify storage eden:database names.rarity_mobs.first.16 set value Caelum
 data modify storage eden:database names.rarity_mobs.first.17 set value Calista
 data modify storage eden:database names.rarity_mobs.first.18 set value Caspian
 data modify storage eden:database names.rarity_mobs.first.19 set value Cedric
 data modify storage eden:database names.rarity_mobs.first.20 set value Corbin
 data modify storage eden:database names.rarity_mobs.first.21 set value Darian
 data modify storage eden:database names.rarity_mobs.first.22 set value Draven
 data modify storage eden:database names.rarity_mobs.first.23 set value Elara
 data modify storage eden:database names.rarity_mobs.first.24 set value Eldric
 data modify storage eden:database names.rarity_mobs.first.25 set value Elowen
 data modify storage eden:database names.rarity_mobs.first.26 set value Emery
 data modify storage eden:database names.rarity_mobs.first.27 set value Enid
 data modify storage eden:database names.rarity_mobs.first.28 set value Eowyn
 data modify storage eden:database names.rarity_mobs.first.29 set value Eris
 data modify storage eden:database names.rarity_mobs.first.30 set value Evander
 data modify storage eden:database names.rarity_mobs.first.31 set value Evelina
 data modify storage eden:database names.rarity_mobs.first.32 set value Farren
 data modify storage eden:database names.rarity_mobs.first.33 set value Faelan
 data modify storage eden:database names.rarity_mobs.first.34 set value Finley
 data modify storage eden:database names.rarity_mobs.first.35 set value Freya
 data modify storage eden:database names.rarity_mobs.first.36 set value Galen
 data modify storage eden:database names.rarity_mobs.first.37 set value Gideon
 data modify storage eden:database names.rarity_mobs.first.38 set value Gryphon
 data modify storage eden:database names.rarity_mobs.first.39 set value Hadrian
 data modify storage eden:database names.rarity_mobs.first.40 set value Halcyon
 data modify storage eden:database names.rarity_mobs.first.41 set value Harlow
 data modify storage eden:database names.rarity_mobs.first.42 set value Idris
 data modify storage eden:database names.rarity_mobs.first.43 set value Ilaria
 data modify storage eden:database names.rarity_mobs.first.44 set value Isolde
 data modify storage eden:database names.rarity_mobs.first.45 set value Kaelen
 data modify storage eden:database names.rarity_mobs.first.46 set value Kieran
 data modify storage eden:database names.rarity_mobs.first.47 set value Kaelar
 data modify storage eden:database names.rarity_mobs.first.48 set value Lysander
 data modify storage eden:database names.rarity_mobs.first.49 set value Lyra
 data modify storage eden:database names.rarity_mobs.first.50 set value Magnus
 data modify storage eden:database names.rarity_mobs.first.51 set value Meliora
 data modify storage eden:database names.rarity_mobs.first.52 set value Morwen
 data modify storage eden:database names.rarity_mobs.first.53 set value Niamh
 data modify storage eden:database names.rarity_mobs.first.54 set value Nyx
 data modify storage eden:database names.rarity_mobs.first.55 set value Orin
 data modify storage eden:database names.rarity_mobs.first.56 set value Orpheus
 data modify storage eden:database names.rarity_mobs.first.57 set value Ophelia
 data modify storage eden:database names.rarity_mobs.first.58 set value Perrin
 data modify storage eden:database names.rarity_mobs.first.59 set value Phaedra
 data modify storage eden:database names.rarity_mobs.first.60 set value Quinlan
 data modify storage eden:database names.rarity_mobs.first.61 set value Roran
 data modify storage eden:database names.rarity_mobs.first.62 set value Rowan
 data modify storage eden:database names.rarity_mobs.first.63 set value Rune
 data modify storage eden:database names.rarity_mobs.first.64 set value Seraphina
 data modify storage eden:database names.rarity_mobs.first.65 set value Soren
 data modify storage eden:database names.rarity_mobs.first.66 set value Talon
 data modify storage eden:database names.rarity_mobs.first.67 set value Thalia
 data modify storage eden:database names.rarity_mobs.first.68 set value Thaddeus
 data modify storage eden:database names.rarity_mobs.first.69 set value Thorne
 data modify storage eden:database names.rarity_mobs.first.70 set value Torin
 data modify storage eden:database names.rarity_mobs.first.71 set value Tamsin
 data modify storage eden:database names.rarity_mobs.first.72 set value Ulric
 data modify storage eden:database names.rarity_mobs.first.73 set value Valerian
 data modify storage eden:database names.rarity_mobs.first.74 set value Valora
 data modify storage eden:database names.rarity_mobs.first.75 set value Vesper
 data modify storage eden:database names.rarity_mobs.first.76 set value Vallen
 data modify storage eden:database names.rarity_mobs.first.77 set value Vanya
 data modify storage eden:database names.rarity_mobs.first.78 set value Varian
 data modify storage eden:database names.rarity_mobs.first.79 set value Xander
 data modify storage eden:database names.rarity_mobs.first.80 set value Xavia
 data modify storage eden:database names.rarity_mobs.first.81 set value Xanthe
 data modify storage eden:database names.rarity_mobs.first.82 set value Xenia
 data modify storage eden:database names.rarity_mobs.first.83 set value Yara
 data modify storage eden:database names.rarity_mobs.first.84 set value Yarrow
 data modify storage eden:database names.rarity_mobs.first.85 set value Yvaine
 data modify storage eden:database names.rarity_mobs.first.86 set value Zephyr
 data modify storage eden:database names.rarity_mobs.first.87 set value Zara
 data modify storage eden:database names.rarity_mobs.first.88 set value Zephyra
 data modify storage eden:database names.rarity_mobs.first.89 set value Zevran
 data modify storage eden:database names.rarity_mobs.first.90 set value Zephyrine
 data modify storage eden:database names.rarity_mobs.first.91 set value Zadie
 data modify storage eden:database names.rarity_mobs.first.92 set value Zora
 data modify storage eden:database names.rarity_mobs.first.93 set value Zuriel
 data modify storage eden:database names.rarity_mobs.first.94 set value Ailis
 data modify storage eden:database names.rarity_mobs.first.95 set value Alistair
 data modify storage eden:database names.rarity_mobs.first.96 set value Briar
 data modify storage eden:database names.rarity_mobs.first.97 set value Branwen
 data modify storage eden:database names.rarity_mobs.first.98 set value Cadeyrn
 data modify storage eden:database names.rarity_mobs.first.99 set value Caelan
data modify storage eden:database names.rarity_mobs.first.100 set value Caelum
data modify storage eden:database names.rarity_mobs.first.101 set value Ceridwen
data modify storage eden:database names.rarity_mobs.first.102 set value Corvus
data modify storage eden:database names.rarity_mobs.first.103 set value Dariana
data modify storage eden:database names.rarity_mobs.first.104 set value Daxton
data modify storage eden:database names.rarity_mobs.first.105 set value Drystan
data modify storage eden:database names.rarity_mobs.first.106 set value Eirlys
data modify storage eden:database names.rarity_mobs.first.107 set value Eowyn
data modify storage eden:database names.rarity_mobs.first.108 set value Emrys
data modify storage eden:database names.rarity_mobs.first.109 set value Eirian
data modify storage eden:database names.rarity_mobs.first.110 set value Eleri
data modify storage eden:database names.rarity_mobs.first.111 set value Eirwen
data modify storage eden:database names.rarity_mobs.first.112 set value Elara
data modify storage eden:database names.rarity_mobs.first.113 set value Elinor
data modify storage eden:database names.rarity_mobs.first.114 set value Eowyn
data modify storage eden:database names.rarity_mobs.first.115 set value Enid
data modify storage eden:database names.rarity_mobs.first.116 set value Enora
data modify storage eden:database names.rarity_mobs.first.117 set value Eris
data modify storage eden:database names.rarity_mobs.first.118 set value Eirlys
data modify storage eden:database names.rarity_mobs.first.119 set value Elowen
data modify storage eden:database names.rarity_mobs.first.120 set value Enid
data modify storage eden:database names.rarity_mobs.first.121 set value Faelan
data modify storage eden:database names.rarity_mobs.first.122 set value Faelan
data modify storage eden:database names.rarity_mobs.first.123 set value Gwendolyn
data modify storage eden:database names.rarity_mobs.first.124 set value Gryffin
data modify storage eden:database names.rarity_mobs.first.125 set value Gwydion
data modify storage eden:database names.rarity_mobs.first.126 set value Hadrian
data modify storage eden:database names.rarity_mobs.first.127 set value Isolde
data modify storage eden:database names.rarity_mobs.first.128 set value Iseult
data modify storage eden:database names.rarity_mobs.first.129 set value Kaelan
data modify storage eden:database names.rarity_mobs.first.130 set value Kaelar
data modify storage eden:database names.rarity_mobs.first.131 set value Kaelum
data modify storage eden:database names.rarity_mobs.first.132 set value Kaiden
data modify storage eden:database names.rarity_mobs.first.133 set value Kieran
data modify storage eden:database names.rarity_mobs.first.134 set value Lachlan
data modify storage eden:database names.rarity_mobs.first.135 set value Lirael
data modify storage eden:database names.rarity_mobs.first.136 set value Lysander
data modify storage eden:database names.rarity_mobs.first.137 set value Lyra
data modify storage eden:database names.rarity_mobs.first.138 set value Morrigan
data modify storage eden:database names.rarity_mobs.first.139 set value Niamh
data modify storage eden:database names.rarity_mobs.first.140 set value Nyx
data modify storage eden:database names.rarity_mobs.first.141 set value Oisin
data modify storage eden:database names.rarity_mobs.first.142 set value Orin
data modify storage eden:database names.rarity_mobs.first.143 set value Orpheus
data modify storage eden:database names.rarity_mobs.first.144 set value Osian
data modify storage eden:database names.rarity_mobs.first.145 set value Perrin
data modify storage eden:database names.rarity_mobs.first.146 set value Phelan
data modify storage eden:database names.rarity_mobs.first.147 set value Quinlan
data modify storage eden:database names.rarity_mobs.first.148 set value Rhydian
data modify storage eden:database names.rarity_mobs.first.149 set value Rhys
data modify storage eden:database names.rarity_mobs.first.150 set value Roran
data modify storage eden:database names.rarity_mobs.first.151 set value Rowan
data modify storage eden:database names.rarity_mobs.first.152 set value Rune
data modify storage eden:database names.rarity_mobs.first.153 set value Seraphina
data modify storage eden:database names.rarity_mobs.first.154 set value Sorcha
data modify storage eden:database names.rarity_mobs.first.155 set value Soren
data modify storage eden:database names.rarity_mobs.first.156 set value Talon
data modify storage eden:database names.rarity_mobs.first.157 set value Thalia
data modify storage eden:database names.rarity_mobs.first.158 set value Thaddeus
data modify storage eden:database names.rarity_mobs.first.159 set value Thorne
data modify storage eden:database names.rarity_mobs.first.160 set value Torin
data modify storage eden:database names.rarity_mobs.first.161 set value Tamsin
data modify storage eden:database names.rarity_mobs.first.162 set value Valerian
data modify storage eden:database names.rarity_mobs.first.163 set value Valora
data modify storage eden:database names.rarity_mobs.first.164 set value Vallen
data modify storage eden:database names.rarity_mobs.first.165 set value Vanya
data modify storage eden:database names.rarity_mobs.first.166 set value Varian
data modify storage eden:database names.rarity_mobs.first.167 set value Xander
data modify storage eden:database names.rarity_mobs.first.168 set value Xanthus
data modify storage eden:database names.rarity_mobs.first.169 set value Xavia
data modify storage eden:database names.rarity_mobs.first.170 set value Xylon
data modify storage eden:database names.rarity_mobs.first.171 set value Xanthe
data modify storage eden:database names.rarity_mobs.first.172 set value Xylia
data modify storage eden:database names.rarity_mobs.first.173 set value Yara
data modify storage eden:database names.rarity_mobs.first.174 set value Yarrow
data modify storage eden:database names.rarity_mobs.first.175 set value Yvaine
data modify storage eden:database names.rarity_mobs.first.176 set value Zephyr
data modify storage eden:database names.rarity_mobs.first.177 set value Zephyrine
data modify storage eden:database names.rarity_mobs.first.178 set value Zara
data modify storage eden:database names.rarity_mobs.first.179 set value Zephyra
data modify storage eden:database names.rarity_mobs.first.180 set value Zadie
data modify storage eden:database names.rarity_mobs.first.181 set value Zora
data modify storage eden:database names.rarity_mobs.first.182 set value Zuriel
data modify storage eden:database names.rarity_mobs.first.183 set value Ailis
data modify storage eden:database names.rarity_mobs.first.184 set value Alistair
data modify storage eden:database names.rarity_mobs.first.185 set value Briar
data modify storage eden:database names.rarity_mobs.first.186 set value Branwen
data modify storage eden:database names.rarity_mobs.first.187 set value Cadeyrn
data modify storage eden:database names.rarity_mobs.first.188 set value Caelan
data modify storage eden:database names.rarity_mobs.first.189 set value Caelum
data modify storage eden:database names.rarity_mobs.first.190 set value Ceridwen
data modify storage eden:database names.rarity_mobs.first.191 set value Corvus
data modify storage eden:database names.rarity_mobs.first.192 set value Dariana
data modify storage eden:database names.rarity_mobs.first.193 set value Daxton
data modify storage eden:database names.rarity_mobs.first.194 set value Drystan
data modify storage eden:database names.rarity_mobs.first.195 set value Eirlys
data modify storage eden:database names.rarity_mobs.first.196 set value Eowyn
data modify storage eden:database names.rarity_mobs.first.197 set value Emrys
data modify storage eden:database names.rarity_mobs.first.198 set value Eirian
data modify storage eden:database names.rarity_mobs.first.199 set value Eleri
data modify storage eden:database names.rarity_mobs.first.200 set value Eirwen
data modify storage eden:database names.rarity_mobs.first.201 set value Elara
data modify storage eden:database names.rarity_mobs.first.202 set value Elinor
data modify storage eden:database names.rarity_mobs.first.203 set value Eowyn
data modify storage eden:database names.rarity_mobs.first.204 set value Enid
data modify storage eden:database names.rarity_mobs.first.205 set value Enora
data modify storage eden:database names.rarity_mobs.first.206 set value Eris
data modify storage eden:database names.rarity_mobs.first.207 set value Eirlys
data modify storage eden:database names.rarity_mobs.first.208 set value Elowen
data modify storage eden:database names.rarity_mobs.first.209 set value Enid
data modify storage eden:database names.rarity_mobs.first.210 set value Faelan
data modify storage eden:database names.rarity_mobs.first.211 set value Faelan
data modify storage eden:database names.rarity_mobs.first.212 set value Gwendolyn
data modify storage eden:database names.rarity_mobs.first.213 set value Gryffin
data modify storage eden:database names.rarity_mobs.first.214 set value Gwydion
data modify storage eden:database names.rarity_mobs.first.215 set value Hadrian
data modify storage eden:database names.rarity_mobs.first.216 set value Isolde
data modify storage eden:database names.rarity_mobs.first.217 set value Iseult
data modify storage eden:database names.rarity_mobs.first.218 set value Kaelan
data modify storage eden:database names.rarity_mobs.first.219 set value Kaelar
data modify storage eden:database names.rarity_mobs.first.220 set value Kaelum
data modify storage eden:database names.rarity_mobs.first.221 set value Kaiden
data modify storage eden:database names.rarity_mobs.first.222 set value Kieran
data modify storage eden:database names.rarity_mobs.first.223 set value Lachlan
data modify storage eden:database names.rarity_mobs.first.224 set value Lirael
data modify storage eden:database names.rarity_mobs.first.225 set value Lysander
data modify storage eden:database names.rarity_mobs.first.226 set value Lyra
data modify storage eden:database names.rarity_mobs.first.227 set value Morrigan
data modify storage eden:database names.rarity_mobs.first.228 set value Niamh
data modify storage eden:database names.rarity_mobs.first.229 set value Nyx
data modify storage eden:database names.rarity_mobs.first.230 set value Oisin
data modify storage eden:database names.rarity_mobs.first.231 set value Orin
data modify storage eden:database names.rarity_mobs.first.232 set value Orpheus
data modify storage eden:database names.rarity_mobs.first.233 set value Osian
data modify storage eden:database names.rarity_mobs.first.234 set value Perrin
data modify storage eden:database names.rarity_mobs.first.235 set value Phelan
data modify storage eden:database names.rarity_mobs.first.236 set value Quinlan
data modify storage eden:database names.rarity_mobs.first.237 set value Rhydian
data modify storage eden:database names.rarity_mobs.first.238 set value Rhys
data modify storage eden:database names.rarity_mobs.first.239 set value Roran
data modify storage eden:database names.rarity_mobs.first.240 set value Rowan
data modify storage eden:database names.rarity_mobs.first.241 set value Rune
data modify storage eden:database names.rarity_mobs.first.242 set value Seraphina
data modify storage eden:database names.rarity_mobs.first.243 set value Sorcha
data modify storage eden:database names.rarity_mobs.first.244 set value Soren
data modify storage eden:database names.rarity_mobs.first.245 set value Talon
data modify storage eden:database names.rarity_mobs.first.246 set value Thalia
data modify storage eden:database names.rarity_mobs.first.247 set value Thaddeus
data modify storage eden:database names.rarity_mobs.first.248 set value Thorne
data modify storage eden:database names.rarity_mobs.first.249 set value Torin
data modify storage eden:database names.rarity_mobs.first.250 set value Tamsin
