  data modify storage eden:database names.rarity_mobs.last.1 set value Creeperstein
  data modify storage eden:database names.rarity_mobs.last.2 set value Blockson
  data modify storage eden:database names.rarity_mobs.last.3 set value Enderforge
  data modify storage eden:database names.rarity_mobs.last.4 set value Redstoner
  data modify storage eden:database names.rarity_mobs.last.5 set value Diamondsmith
  data modify storage eden:database names.rarity_mobs.last.6 set value Villagerman
  data modify storage eden:database names.rarity_mobs.last.7 set value Axecrafter
  data modify storage eden:database names.rarity_mobs.last.8 set value Smithycraft
  data modify storage eden:database names.rarity_mobs.last.9 set value Stonemason
 data modify storage eden:database names.rarity_mobs.last.10 set value Pickaxeberg
 data modify storage eden:database names.rarity_mobs.last.11 set value Heroblock
 data modify storage eden:database names.rarity_mobs.last.12 set value Enchantor
 data modify storage eden:database names.rarity_mobs.last.13 set value Ghastly
 data modify storage eden:database names.rarity_mobs.last.14 set value Minerstone
 data modify storage eden:database names.rarity_mobs.last.15 set value Bricklayer
 data modify storage eden:database names.rarity_mobs.last.16 set value Pigmane
 data modify storage eden:database names.rarity_mobs.last.17 set value Wolfheart
 data modify storage eden:database names.rarity_mobs.last.18 set value Enderborn
 data modify storage eden:database names.rarity_mobs.last.19 set value Skybuilder
 data modify storage eden:database names.rarity_mobs.last.20 set value Blazeblade
 data modify storage eden:database names.rarity_mobs.last.21 set value Notchborn
 data modify storage eden:database names.rarity_mobs.last.22 set value Farmland
 data modify storage eden:database names.rarity_mobs.last.23 set value Archerarrow
 data modify storage eden:database names.rarity_mobs.last.24 set value Arrowcraft
 data modify storage eden:database names.rarity_mobs.last.25 set value Redstoneborn
 data modify storage eden:database names.rarity_mobs.last.26 set value Goldgatherer
 data modify storage eden:database names.rarity_mobs.last.27 set value Knightstone
 data modify storage eden:database names.rarity_mobs.last.28 set value Treefeller
 data modify storage eden:database names.rarity_mobs.last.29 set value Potionbrewer
 data modify storage eden:database names.rarity_mobs.last.30 set value Swordcraft
 data modify storage eden:database names.rarity_mobs.last.31 set value Ghastburn
 data modify storage eden:database names.rarity_mobs.last.32 set value Skyshard
 data modify storage eden:database names.rarity_mobs.last.33 set value Diamondheart
 data modify storage eden:database names.rarity_mobs.last.34 set value Spidereye
 data modify storage eden:database names.rarity_mobs.last.35 set value Ironsmith
 data modify storage eden:database names.rarity_mobs.last.36 set value Wolfstone
 data modify storage eden:database names.rarity_mobs.last.37 set value Witchcraft
 data modify storage eden:database names.rarity_mobs.last.38 set value Arrowshard
 data modify storage eden:database names.rarity_mobs.last.39 set value Enderbringer
 data modify storage eden:database names.rarity_mobs.last.40 set value Bowcraft
 data modify storage eden:database names.rarity_mobs.last.41 set value Pigmanborn
 data modify storage eden:database names.rarity_mobs.last.42 set value Creeperheart
 data modify storage eden:database names.rarity_mobs.last.43 set value Blockhammer
 data modify storage eden:database names.rarity_mobs.last.44 set value Enderforge
 data modify storage eden:database names.rarity_mobs.last.45 set value Craftmaster
 data modify storage eden:database names.rarity_mobs.last.46 set value Creeperclaw
 data modify storage eden:database names.rarity_mobs.last.47 set value Dragonborn
 data modify storage eden:database names.rarity_mobs.last.48 set value Pixelborn
 data modify storage eden:database names.rarity_mobs.last.49 set value Slimeborn
 data modify storage eden:database names.rarity_mobs.last.50 set value Goldsmith
 data modify storage eden:database names.rarity_mobs.last.51 set value Endersmith
 data modify storage eden:database names.rarity_mobs.last.52 set value Bowbreaker
 data modify storage eden:database names.rarity_mobs.last.53 set value Minerberg
 data modify storage eden:database names.rarity_mobs.last.54 set value Zombiehunter
 data modify storage eden:database names.rarity_mobs.last.55 set value Blocksmith
 data modify storage eden:database names.rarity_mobs.last.56 set value Ghasthunter
 data modify storage eden:database names.rarity_mobs.last.57 set value Oresmith
 data modify storage eden:database names.rarity_mobs.last.58 set value Pigmanhunter
 data modify storage eden:database names.rarity_mobs.last.59 set value Skyward
 data modify storage eden:database names.rarity_mobs.last.60 set value Villagercraft
 data modify storage eden:database names.rarity_mobs.last.61 set value Wolfhunter
 data modify storage eden:database names.rarity_mobs.last.62 set value Spidercraft
 data modify storage eden:database names.rarity_mobs.last.63 set value Notchclaw
 data modify storage eden:database names.rarity_mobs.last.64 set value Creeperborn
 data modify storage eden:database names.rarity_mobs.last.65 set value Diamondcrafter
 data modify storage eden:database names.rarity_mobs.last.66 set value Axeblade
 data modify storage eden:database names.rarity_mobs.last.67 set value Firestone
 data modify storage eden:database names.rarity_mobs.last.68 set value Archerstone
 data modify storage eden:database names.rarity_mobs.last.69 set value Brickcraft
 data modify storage eden:database names.rarity_mobs.last.70 set value Guardianstone
 data modify storage eden:database names.rarity_mobs.last.71 set value Dragonforge
 data modify storage eden:database names.rarity_mobs.last.72 set value Blazeheart
 data modify storage eden:database names.rarity_mobs.last.73 set value Stoneweaver
 data modify storage eden:database names.rarity_mobs.last.74 set value Skeletonbone
 data modify storage eden:database names.rarity_mobs.last.75 set value Enchantblade
 data modify storage eden:database names.rarity_mobs.last.76 set value Diamondback
 data modify storage eden:database names.rarity_mobs.last.77 set value Witchburn
 data modify storage eden:database names.rarity_mobs.last.78 set value Blockweaver
 data modify storage eden:database names.rarity_mobs.last.79 set value Goldheart
 data modify storage eden:database names.rarity_mobs.last.80 set value Creeperclaw
 data modify storage eden:database names.rarity_mobs.last.81 set value Redstoneman
 data modify storage eden:database names.rarity_mobs.last.82 set value Enderhunter
 data modify storage eden:database names.rarity_mobs.last.83 set value Swordstone
 data modify storage eden:database names.rarity_mobs.last.84 set value Pickaxeborn
 data modify storage eden:database names.rarity_mobs.last.85 set value Archerborn
 data modify storage eden:database names.rarity_mobs.last.86 set value Pigmanstone
 data modify storage eden:database names.rarity_mobs.last.87 set value Heroblock
 data modify storage eden:database names.rarity_mobs.last.88 set value Spiderforge
 data modify storage eden:database names.rarity_mobs.last.89 set value Enderblade
 data modify storage eden:database names.rarity_mobs.last.90 set value Ghasthammer
 data modify storage eden:database names.rarity_mobs.last.91 set value Treeborn
 data modify storage eden:database names.rarity_mobs.last.92 set value Villagerborn
 data modify storage eden:database names.rarity_mobs.last.93 set value Arrowforge
 data modify storage eden:database names.rarity_mobs.last.94 set value Creepercraft
 data modify storage eden:database names.rarity_mobs.last.95 set value Minerborn
 data modify storage eden:database names.rarity_mobs.last.96 set value Stonetamer
 data modify storage eden:database names.rarity_mobs.last.97 set value Skyborn
 data modify storage eden:database names.rarity_mobs.last.98 set value Wolfcraft
 data modify storage eden:database names.rarity_mobs.last.99 set value Blockhunter
data modify storage eden:database names.rarity_mobs.last.100 set value Diamondweaver
data modify storage eden:database names.rarity_mobs.last.101 set value Redstoneforge
data modify storage eden:database names.rarity_mobs.last.102 set value Witchstone
data modify storage eden:database names.rarity_mobs.last.103 set value Ironheart
data modify storage eden:database names.rarity_mobs.last.104 set value Pigmanforge
data modify storage eden:database names.rarity_mobs.last.105 set value Archerheart
data modify storage eden:database names.rarity_mobs.last.106 set value Dragonstone
data modify storage eden:database names.rarity_mobs.last.107 set value Brickborn
data modify storage eden:database names.rarity_mobs.last.108 set value Enderstone
data modify storage eden:database names.rarity_mobs.last.109 set value Skeletoncraft
data modify storage eden:database names.rarity_mobs.last.110 set value Enchantstone
data modify storage eden:database names.rarity_mobs.last.111 set value Blazeclaw
data modify storage eden:database names.rarity_mobs.last.112 set value Stonedrake
data modify storage eden:database names.rarity_mobs.last.113 set value Guardiancraft
data modify storage eden:database names.rarity_mobs.last.114 set value Diamondhammer
data modify storage eden:database names.rarity_mobs.last.115 set value Creeperforge
data modify storage eden:database names.rarity_mobs.last.116 set value Axeborn
data modify storage eden:database names.rarity_mobs.last.117 set value Zombieborn
data modify storage eden:database names.rarity_mobs.last.118 set value Blockburn
data modify storage eden:database names.rarity_mobs.last.119 set value Ghastborn
data modify storage eden:database names.rarity_mobs.last.120 set value Skyweaver
data modify storage eden:database names.rarity_mobs.last.121 set value Pickaxeheart
data modify storage eden:database names.rarity_mobs.last.122 set value Villagerheart
data modify storage eden:database names.rarity_mobs.last.123 set value Pigmanclaw
data modify storage eden:database names.rarity_mobs.last.124 set value Spiderheart
data modify storage eden:database names.rarity_mobs.last.125 set value Notchhammer
data modify storage eden:database names.rarity_mobs.last.126 set value Treehunter
data modify storage eden:database names.rarity_mobs.last.127 set value Ironborn
data modify storage eden:database names.rarity_mobs.last.128 set value Witchcraft
data modify storage eden:database names.rarity_mobs.last.129 set value Blazeclaw
data modify storage eden:database names.rarity_mobs.last.130 set value Arrowborn
data modify storage eden:database names.rarity_mobs.last.131 set value Enderborn
data modify storage eden:database names.rarity_mobs.last.132 set value Brickstone
data modify storage eden:database names.rarity_mobs.last.133 set value Archerhammer
data modify storage eden:database names.rarity_mobs.last.134 set value Skeletonborn
data modify storage eden:database names.rarity_mobs.last.135 set value Blocksmith
data modify storage eden:database names.rarity_mobs.last.136 set value Creeperheart
data modify storage eden:database names.rarity_mobs.last.137 set value Goldforge
data modify storage eden:database names.rarity_mobs.last.138 set value Skyborn
data modify storage eden:database names.rarity_mobs.last.139 set value Diamondclaw
data modify storage eden:database names.rarity_mobs.last.140 set value Stonewalker
data modify storage eden:database names.rarity_mobs.last.141 set value Guardianborn
data modify storage eden:database names.rarity_mobs.last.142 set value Redstoneheart
data modify storage eden:database names.rarity_mobs.last.143 set value Pigmanborn
data modify storage eden:database names.rarity_mobs.last.144 set value Enchanthammer
data modify storage eden:database names.rarity_mobs.last.145 set value Zombieforge
data modify storage eden:database names.rarity_mobs.last.146 set value Bowborn
data modify storage eden:database names.rarity_mobs.last.147 set value Heroblock
data modify storage eden:database names.rarity_mobs.last.148 set value Treeforge
data modify storage eden:database names.rarity_mobs.last.149 set value Enderborn
data modify storage eden:database names.rarity_mobs.last.150 set value Blazeheart
data modify storage eden:database names.rarity_mobs.last.151 set value Axestone
data modify storage eden:database names.rarity_mobs.last.152 set value Creeperhunter
data modify storage eden:database names.rarity_mobs.last.153 set value Ironforge
data modify storage eden:database names.rarity_mobs.last.154 set value Archerborn
data modify storage eden:database names.rarity_mobs.last.155 set value Pigmanstone
data modify storage eden:database names.rarity_mobs.last.156 set value Skeletonhammer
data modify storage eden:database names.rarity_mobs.last.157 set value Goldborn
data modify storage eden:database names.rarity_mobs.last.158 set value Skyforge
data modify storage eden:database names.rarity_mobs.last.159 set value Redstoneclaw
data modify storage eden:database names.rarity_mobs.last.160 set value Witchborn
data modify storage eden:database names.rarity_mobs.last.161 set value Diamondweaver
data modify storage eden:database names.rarity_mobs.last.162 set value Blockhammer
data modify storage eden:database names.rarity_mobs.last.163 set value Spiderborn
data modify storage eden:database names.rarity_mobs.last.164 set value Treeclaw
data modify storage eden:database names.rarity_mobs.last.165 set value Villagerforge
data modify storage eden:database names.rarity_mobs.last.166 set value Arrowclaw
data modify storage eden:database names.rarity_mobs.last.167 set value Stonestone
data modify storage eden:database names.rarity_mobs.last.168 set value Pickaxeborn
data modify storage eden:database names.rarity_mobs.last.169 set value Endercraft
data modify storage eden:database names.rarity_mobs.last.170 set value Brickheart
data modify storage eden:database names.rarity_mobs.last.171 set value Guardianhammer
data modify storage eden:database names.rarity_mobs.last.172 set value Heroborn
data modify storage eden:database names.rarity_mobs.last.173 set value Pigmanforge
data modify storage eden:database names.rarity_mobs.last.174 set value Creeperstone
data modify storage eden:database names.rarity_mobs.last.175 set value Ironhammer
data modify storage eden:database names.rarity_mobs.last.176 set value Skyborn
data modify storage eden:database names.rarity_mobs.last.177 set value Enchanthammer
data modify storage eden:database names.rarity_mobs.last.178 set value Zombieborn
data modify storage eden:database names.rarity_mobs.last.179 set value Witchforge
data modify storage eden:database names.rarity_mobs.last.180 set value Blockborn
data modify storage eden:database names.rarity_mobs.last.181 set value Archerstone
data modify storage eden:database names.rarity_mobs.last.182 set value Diamondheart
data modify storage eden:database names.rarity_mobs.last.183 set value Stonetamer
data modify storage eden:database names.rarity_mobs.last.184 set value Ghastborn
data modify storage eden:database names.rarity_mobs.last.185 set value Redstoneforge
data modify storage eden:database names.rarity_mobs.last.186 set value Pigmanclaw
data modify storage eden:database names.rarity_mobs.last.187 set value Skeletonstone
data modify storage eden:database names.rarity_mobs.last.188 set value Goldheart
data modify storage eden:database names.rarity_mobs.last.189 set value Skyforge
data modify storage eden:database names.rarity_mobs.last.190 set value Treehammer
data modify storage eden:database names.rarity_mobs.last.191 set value Enderclaw
data modify storage eden:database names.rarity_mobs.last.192 set value Creeperforge
data modify storage eden:database names.rarity_mobs.last.193 set value Archerborn
data modify storage eden:database names.rarity_mobs.last.194 set value Blazeclaw
data modify storage eden:database names.rarity_mobs.last.195 set value Axeborn
data modify storage eden:database names.rarity_mobs.last.196 set value Skeletonforge
data modify storage eden:database names.rarity_mobs.last.197 set value Blockclaw
data modify storage eden:database names.rarity_mobs.last.198 set value Pigmanborn
data modify storage eden:database names.rarity_mobs.last.199 set value Diamondhammer
data modify storage eden:database names.rarity_mobs.last.200 set value Witchstone
data modify storage eden:database names.rarity_mobs.last.201 set value Ironclaw
data modify storage eden:database names.rarity_mobs.last.202 set value Skyborn
data modify storage eden:database names.rarity_mobs.last.203 set value Redstoneforge
data modify storage eden:database names.rarity_mobs.last.204 set value Spiderclaw
data modify storage eden:database names.rarity_mobs.last.205 set value Enderhammer
data modify storage eden:database names.rarity_mobs.last.206 set value Heroborn
data modify storage eden:database names.rarity_mobs.last.207 set value Creeperforge
data modify storage eden:database names.rarity_mobs.last.208 set value Archerstone
data modify storage eden:database names.rarity_mobs.last.209 set value Pigmanclaw
data modify storage eden:database names.rarity_mobs.last.210 set value Blazeclaw
data modify storage eden:database names.rarity_mobs.last.211 set value Axeborn
data modify storage eden:database names.rarity_mobs.last.212 set value Skeletonforge
data modify storage eden:database names.rarity_mobs.last.213 set value Blockclaw
data modify storage eden:database names.rarity_mobs.last.214 set value Pigmanborn
data modify storage eden:database names.rarity_mobs.last.215 set value Diamondhammer
data modify storage eden:database names.rarity_mobs.last.216 set value Witchstone
data modify storage eden:database names.rarity_mobs.last.217 set value Ironclaw
data modify storage eden:database names.rarity_mobs.last.218 set value Skyborn
data modify storage eden:database names.rarity_mobs.last.219 set value Redstoneforge
data modify storage eden:database names.rarity_mobs.last.220 set value Spiderclaw
data modify storage eden:database names.rarity_mobs.last.221 set value Enderhammer
data modify storage eden:database names.rarity_mobs.last.222 set value Heroborn
data modify storage eden:database names.rarity_mobs.last.223 set value Creeperforge
data modify storage eden:database names.rarity_mobs.last.224 set value Archerstone
data modify storage eden:database names.rarity_mobs.last.225 set value Pigmanclaw
data modify storage eden:database names.rarity_mobs.last.226 set value Blazeclaw
data modify storage eden:database names.rarity_mobs.last.227 set value Axeborn
data modify storage eden:database names.rarity_mobs.last.228 set value Skeletonforge
data modify storage eden:database names.rarity_mobs.last.229 set value Blockclaw
data modify storage eden:database names.rarity_mobs.last.230 set value Pigmanborn
data modify storage eden:database names.rarity_mobs.last.231 set value Diamondhammer
data modify storage eden:database names.rarity_mobs.last.232 set value Witchstone
data modify storage eden:database names.rarity_mobs.last.233 set value Ironclaw
data modify storage eden:database names.rarity_mobs.last.234 set value Skyborn
data modify storage eden:database names.rarity_mobs.last.235 set value Redstoneforge
data modify storage eden:database names.rarity_mobs.last.236 set value Spiderclaw
data modify storage eden:database names.rarity_mobs.last.237 set value Enderhammer
data modify storage eden:database names.rarity_mobs.last.238 set value Heroborn
data modify storage eden:database names.rarity_mobs.last.239 set value Creeperforge
data modify storage eden:database names.rarity_mobs.last.240 set value Archerstone
data modify storage eden:database names.rarity_mobs.last.241 set value Pigmanclaw
data modify storage eden:database names.rarity_mobs.last.242 set value Blazeclaw
data modify storage eden:database names.rarity_mobs.last.243 set value Axeborn
data modify storage eden:database names.rarity_mobs.last.244 set value Skeletonforge
data modify storage eden:database names.rarity_mobs.last.245 set value Blockclaw
data modify storage eden:database names.rarity_mobs.last.246 set value Pigmanborn
data modify storage eden:database names.rarity_mobs.last.247 set value Diamondhammer
data modify storage eden:database names.rarity_mobs.last.248 set value Witchstone
data modify storage eden:database names.rarity_mobs.last.249 set value Ironclaw
data modify storage eden:database names.rarity_mobs.last.250 set value Skyborn