data modify storage eden:database dialogues.villager.desert.100 set value "Welcome to the sandpit we call life."
data modify storage eden:database dialogues.villager.desert.101 set value "The sun hasn’t set in my soul for years."
data modify storage eden:database dialogues.villager.desert.102 set value "Did you seriously just try to plant wheat here?"
data modify storage eden:database dialogues.villager.desert.103 set value "Oh look, another heatstroke victim with a sword."
data modify storage eden:database dialogues.villager.desert.104 set value "Careful, that’s not a mirage—it’s my home."
data modify storage eden:database dialogues.villager.desert.105 set value "No water? No problem. Just kidding, it’s a big problem."
data modify storage eden:database dialogues.villager.desert.106 set value "The sand whispers, but only I understand it."
data modify storage eden:database dialogues.villager.desert.107 set value "You call that armor? Cute."
data modify storage eden:database dialogues.villager.desert.108 set value "I once tried to ride a husk. It went poorly."
data modify storage eden:database dialogues.villager.desert.109 set value "The cacti here have better personalities than some travelers."
data modify storage eden:database dialogues.villager.desert.110 set value "Need a trade or just lost again?"
data modify storage eden:database dialogues.villager.desert.111 set value "Another hot day in paradise."
data modify storage eden:database dialogues.villager.desert.112 set value "The sand remembers more than you think."
data modify storage eden:database dialogues.villager.desert.113 set value "Even the rabbits are hostile here."
data modify storage eden:database dialogues.villager.desert.114 set value "Stay out of the temple. It bites back."
data modify storage eden:database dialogues.villager.desert.115 set value "You smell like the Nether. That’s not a compliment."
data modify storage eden:database dialogues.villager.desert.116 set value "We don’t get rain. We get disappointment."
data modify storage eden:database dialogues.villager.desert.117 set value "You ever seen a golem cry? Neither have I. Yet."
data modify storage eden:database dialogues.villager.desert.118 set value "The desert gives nothing for free."
data modify storage eden:database dialogues.villager.desert.119 set value "Another stranger with big dreams and no water."
data modify storage eden:database dialogues.villager.desert.120 set value "I traded my last joy for a saddle."
data modify storage eden:database dialogues.villager.desert.121 set value "Ever tried baking bread at 120 degrees? Easy."
data modify storage eden:database dialogues.villager.desert.122 set value "The stars here are too close for comfort."
data modify storage eden:database dialogues.villager.desert.123 set value "We don’t dig for treasure—we survive."
data modify storage eden:database dialogues.villager.desert.124 set value "Don’t let the breeze fool you. It’s mocking you."
data modify storage eden:database dialogues.villager.desert.125 set value "Heard your stomach growl. That’s adorable."
data modify storage eden:database dialogues.villager.desert.126 set value "This place builds character. Mostly broken ones."
data modify storage eden:database dialogues.villager.desert.127 set value "The oasis is a myth. Just like hope."
data modify storage eden:database dialogues.villager.desert.128 set value "You got sand in your boots? You’ll get used to it."
data modify storage eden:database dialogues.villager.desert.129 set value "We measure time in how many mobs you’ve outlived."
data modify storage eden:database dialogues.villager.desert.130 set value "The last person who rang our bell became a husk snack."
data modify storage eden:database dialogues.villager.desert.131 set value "Is that a potion or just colored sadness?"
data modify storage eden:database dialogues.villager.desert.132 set value "You brought a bed? You poor, naive soul."
data modify storage eden:database dialogues.villager.desert.133 set value "My house? It’s made of hard-earned dust."
data modify storage eden:database dialogues.villager.desert.134 set value "Sleep here if you like waking up to arrows."
data modify storage eden:database dialogues.villager.desert.135 set value "The sun doesn’t rise here. It attacks."
data modify storage eden:database dialogues.villager.desert.136 set value "Every block here screams. Quietly."
data modify storage eden:database dialogues.villager.desert.137 set value "Don’t follow the rabbits. Seriously."
data modify storage eden:database dialogues.villager.desert.138 set value "The cactus told me your future. It wasn’t good."
data modify storage eden:database dialogues.villager.desert.139 set value "I’ve seen Endermen blink. At me."
data modify storage eden:database dialogues.villager.desert.140 set value "Try not to die. It messes with the vibe."
data modify storage eden:database dialogues.villager.desert.141 set value "You breathe loud. Sand doesn’t like that."
data modify storage eden:database dialogues.villager.desert.142 set value "Ever eaten dry bread for 40 days straight?"
data modify storage eden:database dialogues.villager.desert.143 set value "You look like you’ve never met a husk. Yet."
data modify storage eden:database dialogues.villager.desert.144 set value "Our pets are scorpions. Invisible ones."
data modify storage eden:database dialogues.villager.desert.145 set value "We used to have a librarian. Then the sand took him."
data modify storage eden:database dialogues.villager.desert.146 set value "Acacia wood? That’s a luxury here."
data modify storage eden:database dialogues.villager.desert.147 set value "Sunburns are our natural armor."
data modify storage eden:database dialogues.villager.desert.148 set value "You mine diamonds, I mine reasons to care."
data modify storage eden:database dialogues.villager.desert.149 set value "Careful where you step. That’s our sacred gravel."
data modify storage eden:database dialogues.villager.desert.150 set value "Seen any water? Me neither."
data modify storage eden:database dialogues.villager.desert.151 set value "Don’t dig under the well. Just… don’t."
data modify storage eden:database dialogues.villager.desert.152 set value "You smell like overworld ambition."
data modify storage eden:database dialogues.villager.desert.153 set value "You’re from the forest? Trees sound exhausting."
data modify storage eden:database dialogues.villager.desert.154 set value "Some say the temple has traps. Others… never spoke again."
data modify storage eden:database dialogues.villager.desert.155 set value "You touch my composter, we’re enemies."
data modify storage eden:database dialogues.villager.desert.156 set value "We measure value in cactus flesh and tears."
data modify storage eden:database dialogues.villager.desert.157 set value "I’ve seen creepers try to leave this place."
data modify storage eden:database dialogues.villager.desert.158 set value "Llamas won’t survive long here. Just like optimism."
data modify storage eden:database dialogues.villager.desert.159 set value "No one cries in the desert. It’s too dry."
data modify storage eden:database dialogues.villager.desert.160 set value "The sun doesn’t rise—it declares war."
data modify storage eden:database dialogues.villager.desert.161 set value "Ever tried fishing in sand? Don’t."
data modify storage eden:database dialogues.villager.desert.162 set value "The wind is our music."
data modify storage eden:database dialogues.villager.desert.163 set value "You look thirsty. You also look dumb."
data modify storage eden:database dialogues.villager.desert.164 set value "We don’t farm for food. We farm for survival."
data modify storage eden:database dialogues.villager.desert.165 set value "Trading? Good. Begging? No."
data modify storage eden:database dialogues.villager.desert.166 set value "You brought redstone here? Cute."
data modify storage eden:database dialogues.villager.desert.167 set value "Even my shadow left me."
data modify storage eden:database dialogues.villager.desert.168 set value "I once had a dream. It died in a sandstorm."
data modify storage eden:database dialogues.villager.desert.169 set value "The desert doesn’t hate you—it just ignores you."
data modify storage eden:database dialogues.villager.desert.170 set value "Another one seeking treasure. Boring."
data modify storage eden:database dialogues.villager.desert.171 set value "Try not to sleep too close to the dunes."
data modify storage eden:database dialogues.villager.desert.172 set value "You’re lucky I’m feeling generous. And tired."
data modify storage eden:database dialogues.villager.desert.173 set value "Everything here bites, including the wind."
data modify storage eden:database dialogues.villager.desert.174 set value "We named the husks. It helps us scream at them."
data modify storage eden:database dialogues.villager.desert.175 set value "Our water is more precious than diamonds."
data modify storage eden:database dialogues.villager.desert.176 set value "Every noise after dark is probably a mistake."
data modify storage eden:database dialogues.villager.desert.177 set value "The sandstone remembers things I wish it didn’t."
data modify storage eden:database dialogues.villager.desert.178 set value "I don’t fear the dark. I fear the sand that moves in it."
data modify storage eden:database dialogues.villager.desert.179 set value "Our golem’s cranky. Like me, but heavier."
data modify storage eden:database dialogues.villager.desert.180 set value "Yes, I’m dusty. No, I don’t care."
data modify storage eden:database dialogues.villager.desert.181 set value "The temple? Yeah. It explodes sometimes."
data modify storage eden:database dialogues.villager.desert.182 set value "You think trading is easy? Try it during a raid."
data modify storage eden:database dialogues.villager.desert.183 set value "You brought cake? We haven’t had sugar in years."
data modify storage eden:database dialogues.villager.desert.184 set value "Let me guess—you got lost?"
data modify storage eden:database dialogues.villager.desert.185 set value "Another map. Another waste of paper."
data modify storage eden:database dialogues.villager.desert.186 set value "If you find bones, don’t ask questions."
data modify storage eden:database dialogues.villager.desert.187 set value "Our cats are weird. They don’t meow—they judge."
data modify storage eden:database dialogues.villager.desert.188 set value "Every villager here has a shovel and trauma."
data modify storage eden:database dialogues.villager.desert.189 set value "We celebrate silence. It means no mobs."
data modify storage eden:database dialogues.villager.desert.190 set value "Your boots are full of sand. That’s normal."
data modify storage eden:database dialogues.villager.desert.191 set value "I’ve seen the End. It’s cleaner than this."
data modify storage eden:database dialogues.villager.desert.192 set value "We salt our food with crushed hopes."
data modify storage eden:database dialogues.villager.desert.193 set value "Sand is coarse, rough, and it gets everywhere."
data modify storage eden:database dialogues.villager.desert.194 set value "Our children play with gravel. Builds toughness."
data modify storage eden:database dialogues.villager.desert.195 set value "Ever seen a phantom cry? You will."
data modify storage eden:database dialogues.villager.desert.196 set value "Build your house from sandstone. Watch it crumble."
data modify storage eden:database dialogues.villager.desert.197 set value "Furnaces run 24/7. Even when we don’t need them."
data modify storage eden:database dialogues.villager.desert.198 set value "The savanna villagers complain. Amateurs."
data modify storage eden:database dialogues.villager.desert.199 set value "You still here? Impressive."
data modify storage eden:database dialogues.villager.desert.200 set value "The desert has sunsets that could make a ghast smile."
data modify storage eden:database dialogues.villager.desert.201 set value "Sometimes the wind makes a song just for me."
data modify storage eden:database dialogues.villager.desert.202 set value "Want to race a rabbit? They’re fast but friendly."
data modify storage eden:database dialogues.villager.desert.203 set value "We may be dry, but we’re not dull."
data modify storage eden:database dialogues.villager.desert.204 set value "That cactus over there? I named him Steve."
data modify storage eden:database dialogues.villager.desert.205 set value "We host sandcastle contests every new moon."
data modify storage eden:database dialogues.villager.desert.206 set value "I once built a boat... in the sand. Still proud."
data modify storage eden:database dialogues.villager.desert.207 set value "Sunshine is our default personality."
data modify storage eden:database dialogues.villager.desert.208 set value "Need a smile? Watch our golem trip over a beetroot."
data modify storage eden:database dialogues.villager.desert.209 set value "I love when the husks walk into cactus. Comedy gold."
data modify storage eden:database dialogues.villager.desert.210 set value "The heat bakes the bread and my mood!"
data modify storage eden:database dialogues.villager.desert.211 set value "Sometimes I roll in the sand. No shame."
data modify storage eden:database dialogues.villager.desert.212 set value "Who needs oceans when you’ve got endless dunes?"
data modify storage eden:database dialogues.villager.desert.213 set value "My roof is open sky and good vibes."
data modify storage eden:database dialogues.villager.desert.214 set value "Desert life? It’s dry, but never boring."
data modify storage eden:database dialogues.villager.desert.215 set value "The rabbits dance at night. It’s a vibe."
data modify storage eden:database dialogues.villager.desert.216 set value "I saw a mirage once. It complimented me."
data modify storage eden:database dialogues.villager.desert.217 set value "I’ve got a cactus farm and an attitude."
data modify storage eden:database dialogues.villager.desert.218 set value "The sand sings lullabies if you listen right."
data modify storage eden:database dialogues.villager.desert.219 set value "Sun hats are fashion and survival."
data modify storage eden:database dialogues.villager.desert.220 set value "Water’s rare. Laughter? Less so."
data modify storage eden:database dialogues.villager.desert.221 set value "We trade stories as often as emeralds."
data modify storage eden:database dialogues.villager.desert.222 set value "Have you ever hugged a cactus? You shouldn’t, but I have."
data modify storage eden:database dialogues.villager.desert.223 set value "My crops grow slow, but they grow strong."
data modify storage eden:database dialogues.villager.desert.224 set value "It’s a good day to do nothing in the sun."
data modify storage eden:database dialogues.villager.desert.225 set value "The husks don’t bite if you wink first. Kidding."
data modify storage eden:database dialogues.villager.desert.226 set value "I’ve made peace with the sun. We high-five daily."
data modify storage eden:database dialogues.villager.desert.227 set value "We throw sandballs for fun. Just duck fast."
data modify storage eden:database dialogues.villager.desert.228 set value "My best friend is a rock. Reliable guy."
data modify storage eden:database dialogues.villager.desert.229 set value "The desert’s tough, but so are we."
data modify storage eden:database dialogues.villager.desert.230 set value "We turn boredom into creativity."
data modify storage eden:database dialogues.villager.desert.231 set value "Ever raced a tumbleweed? I lost."
data modify storage eden:database dialogues.villager.desert.232 set value "My favorite sound is cactus pops."
data modify storage eden:database dialogues.villager.desert.233 set value "We plant hope like we plant crops—deep and careful."
data modify storage eden:database dialogues.villager.desert.234 set value "I saw a baby husk do a dance once. Terrifying, but cute."
data modify storage eden:database dialogues.villager.desert.235 set value "The stars here tell the best bedtime stories."
data modify storage eden:database dialogues.villager.desert.236 set value "Sunset tea? It is just hot water and dreams."
data modify storage eden:database dialogues.villager.desert.237 set value "Yes, we have parties. No, you’re not invited. Yet."
data modify storage eden:database dialogues.villager.desert.238 set value "Ever met a desert poet? You just did."
data modify storage eden:database dialogues.villager.desert.239 set value "I make sand soup. It’s bad, but I’m proud."
data modify storage eden:database dialogues.villager.desert.240 set value "A single drop of water is more valuable than gold."
data modify storage eden:database dialogues.villager.desert.241 set value "Silence is the desert’s deepest wisdom."
data modify storage eden:database dialogues.villager.desert.242 set value "Heat burns away all lies."
data modify storage eden:database dialogues.villager.desert.243 set value "The desert asks nothing, yet teaches everything."
data modify storage eden:database dialogues.villager.desert.244 set value "Stillness is strength in the sands."
data modify storage eden:database dialogues.villager.desert.245 set value "The desert does not rush. Why should we?"
data modify storage eden:database dialogues.villager.desert.246 set value "The path is never straight, just sandy."
data modify storage eden:database dialogues.villager.desert.247 set value "Endure long enough, and you become the storm."
data modify storage eden:database dialogues.villager.desert.248 set value "Sometimes survival is the only wisdom you need."
data modify storage eden:database dialogues.villager.desert.249 set value "What thrives here has learned to bend, not break."
data modify storage eden:database dialogues.villager.desert.250 set value "Hunger sharpens more than swords."
data modify storage eden:database dialogues.villager.desert.251 set value "Kindness, like water, is never wasted."
data modify storage eden:database dialogues.villager.desert.252 set value "Each footstep writes a story in the sand."
data modify storage eden:database dialogues.villager.desert.253 set value "Not all treasures glitter. Some grow."
data modify storage eden:database dialogues.villager.desert.254 set value "Doubt dries quicker than water here."
data modify storage eden:database dialogues.villager.desert.255 set value "The desert sees you long before you see it."
data modify storage eden:database dialogues.villager.desert.256 set value "Even the sun must rest eventually."
data modify storage eden:database dialogues.villager.desert.257 set value "He who plants in sand believes in miracles."
data modify storage eden:database dialogues.villager.desert.258 set value "The wind will always tell the truth."
data modify storage eden:database dialogues.villager.desert.259 set value "The desert forgets the weak. And sometimes the strong."
data modify storage eden:database dialogues.villager.desert.260 set value "Some sand doesn’t stay where you leave it."
data modify storage eden:database dialogues.villager.desert.261 set value "We lost a traveler in the temple. Still hear him scream."
data modify storage eden:database dialogues.villager.desert.262 set value "The husks come early when the moon’s full."
data modify storage eden:database dialogues.villager.desert.263 set value "I sleep with one eye open. The sand watches."
data modify storage eden:database dialogues.villager.desert.264 set value "Don’t trust shadows that move."
data modify storage eden:database dialogues.villager.desert.265 set value "Our well’s deep enough to hold regrets."
data modify storage eden:database dialogues.villager.desert.266 set value "That sand pile wasn’t here yesterday."
data modify storage eden:database dialogues.villager.desert.267 set value "The wind howled last night. It used my name."
data modify storage eden:database dialogues.villager.desert.268 set value "My neighbor vanished. His bed’s still warm."
data modify storage eden:database dialogues.villager.desert.269 set value "When the stars blink, I hide."
data modify storage eden:database dialogues.villager.desert.270 set value "I swear the dunes breathe sometimes."
data modify storage eden:database dialogues.villager.desert.271 set value "Ever seen bones in perfect rows?"
data modify storage eden:database dialogues.villager.desert.272 set value "If the cactus flowers, run."
data modify storage eden:database dialogues.villager.desert.273 set value "No one survives three sandstorms in a row. Except me."
data modify storage eden:database dialogues.villager.desert.274 set value "The temple door only opens for blood. Probably kidding."
data modify storage eden:database dialogues.villager.desert.275 set value "The sky’s too quiet tonight."
data modify storage eden:database dialogues.villager.desert.276 set value "You hear that heartbeat? Not yours."
data modify storage eden:database dialogues.villager.desert.277 set value "A shadow passed me at noon. It wasn’t mine."
data modify storage eden:database dialogues.villager.desert.278 set value "Something’s moving under the sand."
data modify storage eden:database dialogues.villager.desert.279 set value "The wind brought voices again."
data modify storage eden:database dialogues.villager.desert.280 set value "I named all my chickens after former mayors."
data modify storage eden:database dialogues.villager.desert.281 set value "Yes, I talk to the sun. No, it doesn’t answer."
data modify storage eden:database dialogues.villager.desert.282 set value "My favorite food is sand. I’m joking. Mostly."
data modify storage eden:database dialogues.villager.desert.283 set value "I made a hat from rabbit fur and cactus juice."
data modify storage eden:database dialogues.villager.desert.284 set value "The beetroot whispers secrets."
data modify storage eden:database dialogues.villager.desert.285 set value "This robe? Made it from sadness and wool."
data modify storage eden:database dialogues.villager.desert.286 set value "I once married a cactus. We don’t talk about it."
data modify storage eden:database dialogues.villager.desert.287 set value "My bed levitates. Don’t worry about it."
data modify storage eden:database dialogues.villager.desert.288 set value "I’ve trained a rabbit to dance. He’s shy."
data modify storage eden:database dialogues.villager.desert.289 set value "Every sunrise resets my memory."
data modify storage eden:database dialogues.villager.desert.290 set value "Don’t trust that sandstone block. It judges."
data modify storage eden:database dialogues.villager.desert.291 set value "I built a throne out of nothing. Just like hope."
data modify storage eden:database dialogues.villager.desert.292 set value "Sometimes I float. Sometimes I scream."
data modify storage eden:database dialogues.villager.desert.293 set value "I’m not a villager. I’m just really committed."
data modify storage eden:database dialogues.villager.desert.294 set value "I think I dreamed you last night."
data modify storage eden:database dialogues.villager.desert.295 set value "You ever meet a sentient tumbleweed? Lucky you."
data modify storage eden:database dialogues.villager.desert.296 set value "This sand? Haunted."
data modify storage eden:database dialogues.villager.desert.297 set value "I once won a staring contest with a blaze."
data modify storage eden:database dialogues.villager.desert.298 set value "The phantoms and I are on speaking terms."
data modify storage eden:database dialogues.villager.desert.299 set value "I buried my past. Literally. Out back."
data modify storage eden:database dialogues.villager.desert.300 set value "Could you build me a cactus fence to keep the mobs out?"
data modify storage eden:database dialogues.villager.desert.301 set value "I need a better roof—sand keeps falling in my bed!"
data modify storage eden:database dialogues.villager.desert.302 set value "Can you make a proper path to the well? My feet hurt."
data modify storage eden:database dialogues.villager.desert.303 set value "A nice little farm would sure help us around here."
data modify storage eden:database dialogues.villager.desert.304 set value "Mind putting up some lanterns? It gets real dark at night."
data modify storage eden:database dialogues.villager.desert.305 set value "Think you could fix that broken house? It’s more hole than home."
data modify storage eden:database dialogues.villager.desert.306 set value "A trading hall would be neat, yeah? With space for all of us!"
data modify storage eden:database dialogues.villager.desert.307 set value "Hey, can you build a bell tower? Ours got creepered."
data modify storage eden:database dialogues.villager.desert.308 set value "I'd love a bigger house—with two chests, even!"
data modify storage eden:database dialogues.villager.desert.309 set value "Can you make me a tiny lookout hut on that dune?"
data modify storage eden:database dialogues.villager.desert.310 set value "A fishing spot by the water would be real nice."
data modify storage eden:database dialogues.villager.desert.311 set value "Build me a bench! Standing all day is rough work."
data modify storage eden:database dialogues.villager.desert.312 set value "Got time to dig out a cellar for cool storage?"
data modify storage eden:database dialogues.villager.desert.313 set value "Our well’s dry—can you dig us a new one?"
data modify storage eden:database dialogues.villager.desert.314 set value "Think you can raise the walls a bit? Husks keep peeking in."
data modify storage eden:database dialogues.villager.desert.315 set value "Could you patch that hole? The wind howls like a ghast!"
data modify storage eden:database dialogues.villager.desert.316 set value "I wouldn’t say no to a little garden with melons."
data modify storage eden:database dialogues.villager.desert.317 set value "Can you put a fence around the village? Y'know, for safety."
data modify storage eden:database dialogues.villager.desert.318 set value "I want a sandcastle. Yes, a real one."
data modify storage eden:database dialogues.villager.desert.319 set value "Build a bridge over the river—I'm tired of swimming with drowned."
data modify storage eden:database dialogues.villager.desert.320 set value "We need a stable for the horses we don’t have yet."
data modify storage eden:database dialogues.villager.desert.321 set value "I could use a tiny shack near the mines."
data modify storage eden:database dialogues.villager.desert.322 set value "Some storage huts would help—we got stuff everywhere!"
data modify storage eden:database dialogues.villager.desert.323 set value "Could you add some banners? The place looks plain."
data modify storage eden:database dialogues.villager.desert.324 set value "I want a cozy reading nook. Don’t ask why."
data modify storage eden:database dialogues.villager.desert.325 set value "Put up some signs—we keep getting lost in our own town."
data modify storage eden:database dialogues.villager.desert.326 set value "Build a little altar—we’ve got spirits to thank."
data modify storage eden:database dialogues.villager.desert.327 set value "A sandstone arch would look amazing at the entrance!"
data modify storage eden:database dialogues.villager.desert.328 set value "I’d love a window with glass—not just a hole."
data modify storage eden:database dialogues.villager.desert.329 set value "Can you build a bakery? The smell alone would be worth it."
data modify storage eden:database dialogues.villager.desert.330 set value "How about a little marketplace with some shade?"
data modify storage eden:database dialogues.villager.desert.331 set value "Put a roof on the well—I’m tired of falling in."
data modify storage eden:database dialogues.villager.desert.332 set value "Could use some stairs on that dune trail. My knees, man."
data modify storage eden:database dialogues.villager.desert.333 set value "Build me a secret room. You didn’t hear that."
data modify storage eden:database dialogues.villager.desert.334 set value "The golem wants a house too, probably."
data modify storage eden:database dialogues.villager.desert.335 set value "Make a little campfire spot so we can swap stories."
data modify storage eden:database dialogues.villager.desert.336 set value "Can you dig out a tunnel to the mines? Safer than outside."
data modify storage eden:database dialogues.villager.desert.337 set value "What if you made a tower? Just a really tall one."
data modify storage eden:database dialogues.villager.desert.338 set value "We need a brewing hut—strictly for potions, I swear."
data modify storage eden:database dialogues.villager.desert.339 set value "Ever thought about a little oasis with some chairs?"
data modify storage eden:database dialogues.villager.desert.340 set value "Make us a map room. I like knowing where I’m not going."
data modify storage eden:database dialogues.villager.desert.341 set value "We need a gate that looks cool but scares pillagers."
data modify storage eden:database dialogues.villager.desert.342 set value "Can you make a tiny shrine to the wandering trader?"
data modify storage eden:database dialogues.villager.desert.343 set value "I want a bench with a view. Somewhere to watch sunsets."
data modify storage eden:database dialogues.villager.desert.344 set value "Add some flowerpots. Empty windows are boring."
data modify storage eden:database dialogues.villager.desert.345 set value "Build a tiny museum for all our cool junk."
data modify storage eden:database dialogues.villager.desert.346 set value "Could you set up a bell on every corner? Just to be safe."
data modify storage eden:database dialogues.villager.desert.347 set value "Make a tower of sand that won’t fall. Magic, basically."
data modify storage eden:database dialogues.villager.desert.348 set value "Give the well a makeover. Maybe with glowstone?"
data modify storage eden:database dialogues.villager.desert.349 set value "Build something weird. Surprise me."