data modify storage eden:database dialogues.villager.jungle.100 set value "Careful where you step—some vines bite back."
data modify storage eden:database dialogues.villager.jungle.101 set value "You hear drums at night too, don’t you?"
data modify storage eden:database dialogues.villager.jungle.102 set value "Trade quickly—the jungle never stands still."
data modify storage eden:database dialogues.villager.jungle.103 set value "Parrots hear more than they repeat."
data modify storage eden:database dialogues.villager.jungle.104 set value "Cookies are the only way to make friends here."
data modify storage eden:database dialogues.villager.jungle.105 set value "The ocelots know things we’ve forgotten."
data modify storage eden:database dialogues.villager.jungle.106 set value "I swear that vine moved on its own."
data modify storage eden:database dialogues.villager.jungle.107 set value "Don’t touch the temple stones—they hum."
data modify storage eden:database dialogues.villager.jungle.108 set value "You smell like you've been to a dungeon."
data modify storage eden:database dialogues.villager.jungle.109 set value "Your map won’t help you past the river bend."
data modify storage eden:database dialogues.villager.jungle.110 set value "We lose more golems to moss than monsters."
data modify storage eden:database dialogues.villager.jungle.111 set value "The canopy watches, always."
data modify storage eden:database dialogues.villager.jungle.112 set value "That mossy stone wasn’t cracked yesterday."
data modify storage eden:database dialogues.villager.jungle.113 set value "Never dig near the roots—they scream."
data modify storage eden:database dialogues.villager.jungle.114 set value "I once saw a creeper dancing."
data modify storage eden:database dialogues.villager.jungle.115 set value "The monkeys don't show themselves to outsiders."
data modify storage eden:database dialogues.villager.jungle.116 set value "You brought cocoa? Now *you* can stay."
data modify storage eden:database dialogues.villager.jungle.117 set value "The vines grow faster when you’re not looking."
data modify storage eden:database dialogues.villager.jungle.118 set value "Don’t eat anything purple in the jungle."
data modify storage eden:database dialogues.villager.jungle.119 set value "Thunder sounds different under thick leaves."
data modify storage eden:database dialogues.villager.jungle.120 set value "That jungle wood is cursed—probably."
data modify storage eden:database dialogues.villager.jungle.121 set value "We follow parrots, not compasses."
data modify storage eden:database dialogues.villager.jungle.122 set value "If it glows green, walk away slowly."
data modify storage eden:database dialogues.villager.jungle.123 set value "Spiders in the canopy don’t drop string."
data modify storage eden:database dialogues.villager.jungle.124 set value "Don’t whistle near the stone faces."
data modify storage eden:database dialogues.villager.jungle.125 set value "Some trees are older than time."
data modify storage eden:database dialogues.villager.jungle.126 set value "A drowned once traded me a trident."
data modify storage eden:database dialogues.villager.jungle.127 set value "You ever been chased by your own shadow?"
data modify storage eden:database dialogues.villager.jungle.128 set value "That’s not mud—it’s memory."
data modify storage eden:database dialogues.villager.jungle.129 set value "Temples change their doors every full moon."
data modify storage eden:database dialogues.villager.jungle.130 set value "Bring melons, not questions."
data modify storage eden:database dialogues.villager.jungle.131 set value "The jungle chooses who gets out."
data modify storage eden:database dialogues.villager.jungle.132 set value "I only trade when the frogs sing."
data modify storage eden:database dialogues.villager.jungle.133 set value "Watch the water—some of it’s eyes."
data modify storage eden:database dialogues.villager.jungle.134 set value "I saw an Enderman climb a vine."
data modify storage eden:database dialogues.villager.jungle.135 set value "Don’t trust parrots with red feathers."
data modify storage eden:database dialogues.villager.jungle.136 set value "You hear a flute? That’s not us."
data modify storage eden:database dialogues.villager.jungle.137 set value "The jungle grows over lies."
data modify storage eden:database dialogues.villager.jungle.138 set value "Our cats disappear for days and come back glowing."
data modify storage eden:database dialogues.villager.jungle.139 set value "That’s not a pond—it’s a trap."
data modify storage eden:database dialogues.villager.jungle.140 set value "Creepers here don’t hiss—they whisper."
data modify storage eden:database dialogues.villager.jungle.141 set value "You see those ruins? Neither do I."
data modify storage eden:database dialogues.villager.jungle.142 set value "I traded emeralds for silence once."
data modify storage eden:database dialogues.villager.jungle.143 set value "We don’t ring bells—we shake leaves."
data modify storage eden:database dialogues.villager.jungle.144 set value "When the vines bloom purple, run."
data modify storage eden:database dialogues.villager.jungle.145 set value "I saw a witch walk through a wall."
data modify storage eden:database dialogues.villager.jungle.146 set value "The jungle heals itself, but not us."
data modify storage eden:database dialogues.villager.jungle.147 set value "Don’t build above the canopy."
data modify storage eden:database dialogues.villager.jungle.148 set value "That stone block wasn’t there yesterday."
data modify storage eden:database dialogues.villager.jungle.149 set value "We grow what we can’t explain."
data modify storage eden:database dialogues.villager.jungle.150 set value "Don’t wear gold near the sacred grove."
data modify storage eden:database dialogues.villager.jungle.151 set value "The parrots keep secrets we can’t afford."
data modify storage eden:database dialogues.villager.jungle.152 set value "The temple doesn’t like loud footsteps."
data modify storage eden:database dialogues.villager.jungle.153 set value "Every ruin has a purpose, even broken ones."
data modify storage eden:database dialogues.villager.jungle.154 set value "My brother traded with a tree once."
data modify storage eden:database dialogues.villager.jungle.155 set value "That’s not a pond—it’s breathing."
data modify storage eden:database dialogues.villager.jungle.156 set value "You lost your compass? Good."
data modify storage eden:database dialogues.villager.jungle.157 set value "We follow the vines, not the path."
data modify storage eden:database dialogues.villager.jungle.158 set value "Redstone doesn’t work right out here."
data modify storage eden:database dialogues.villager.jungle.159 set value "Don’t bring jungle saplings into the Nether."
data modify storage eden:database dialogues.villager.jungle.160 set value "You ever hear the trees laugh?"
data modify storage eden:database dialogues.villager.jungle.161 set value "If you dig at night, dig fast."
data modify storage eden:database dialogues.villager.jungle.162 set value "A parrot once told me my future."
data modify storage eden:database dialogues.villager.jungle.163 set value "The oldest vines grow over graves."
data modify storage eden:database dialogues.villager.jungle.164 set value "I saw a pig disappear into the fog."
data modify storage eden:database dialogues.villager.jungle.165 set value "The temple door only opens to silence."
data modify storage eden:database dialogues.villager.jungle.166 set value "Our golem left. Said he was “called.”"
data modify storage eden:database dialogues.villager.jungle.167 set value "That stone isn’t mossy—it’s watching."
data modify storage eden:database dialogues.villager.jungle.168 set value "You’re not lost. The jungle just moved."
data modify storage eden:database dialogues.villager.jungle.169 set value "That’s not a monkey. That’s something else."
data modify storage eden:database dialogues.villager.jungle.170 set value "Don't sleep under canopy—dreams get stuck."
data modify storage eden:database dialogues.villager.jungle.171 set value "We don’t grow wheat—we grow warnings."
data modify storage eden:database dialogues.villager.jungle.172 set value "That wasn’t lightning. That was something *worse*."
data modify storage eden:database dialogues.villager.jungle.173 set value "You got melon seeds? Let’s talk."
data modify storage eden:database dialogues.villager.jungle.174 set value "I traded my bed for peace of mind."
data modify storage eden:database dialogues.villager.jungle.175 set value "If the parrots leave, so should you."
data modify storage eden:database dialogues.villager.jungle.176 set value "Some vines hum with energy—avoid those."
data modify storage eden:database dialogues.villager.jungle.177 set value "Our well is deep enough to find echoes."
data modify storage eden:database dialogues.villager.jungle.178 set value "You’re breathing loud enough to wake the ruins."
data modify storage eden:database dialogues.villager.jungle.179 set value "The water runs uphill sometimes."
data modify storage eden:database dialogues.villager.jungle.180 set value "Don’t mine too long under the old temple."
data modify storage eden:database dialogues.villager.jungle.181 set value "We measure time by tree rings, not clocks."
data modify storage eden:database dialogues.villager.jungle.182 set value "If it looks like a melon and growls, run."
data modify storage eden:database dialogues.villager.jungle.183 set value "That tree ate our last cartographer."
data modify storage eden:database dialogues.villager.jungle.184 set value "Don't laugh at the idol. It notices."
data modify storage eden:database dialogues.villager.jungle.185 set value "Our cats follow something we don’t see."
data modify storage eden:database dialogues.villager.jungle.186 set value "If you see fog, don’t move."
data modify storage eden:database dialogues.villager.jungle.187 set value "We don’t plant—things grow on their own."
data modify storage eden:database dialogues.villager.jungle.188 set value "I once met a skeleton who could sing."
data modify storage eden:database dialogues.villager.jungle.189 set value "Don’t let the vines touch your tools."
data modify storage eden:database dialogues.villager.jungle.190 set value "You built with jungle wood? Brave."
data modify storage eden:database dialogues.villager.jungle.191 set value "That chest was full an hour ago."
data modify storage eden:database dialogues.villager.jungle.192 set value "When it rains green, stay inside."
data modify storage eden:database dialogues.villager.jungle.193 set value "Some parrots speak in riddles."
data modify storage eden:database dialogues.villager.jungle.194 set value "We never say the witch’s name aloud."
data modify storage eden:database dialogues.villager.jungle.195 set value "That emerald is humming."
data modify storage eden:database dialogues.villager.jungle.196 set value "Every root has a secret."
data modify storage eden:database dialogues.villager.jungle.197 set value "The trees bend when no one’s watching."
data modify storage eden:database dialogues.villager.jungle.198 set value "We lose more traders than we gain."
data modify storage eden:database dialogues.villager.jungle.199 set value "That bridge only appears at sunset."
data modify storage eden:database dialogues.villager.jungle.200 set value "Did the vines just move toward you?"
data modify storage eden:database dialogues.villager.jungle.201 set value "Parrots don’t lie, but they don’t help."
data modify storage eden:database dialogues.villager.jungle.202 set value "You have bones? The jaguar will like you."
data modify storage eden:database dialogues.villager.jungle.203 set value "Don't step near the hollow logs."
data modify storage eden:database dialogues.villager.jungle.204 set value "That drumbeat isn’t coming from us."
data modify storage eden:database dialogues.villager.jungle.205 set value "We don't grow old—we grow weird."
data modify storage eden:database dialogues.villager.jungle.206 set value "Don’t look directly at the stone heads."
data modify storage eden:database dialogues.villager.jungle.207 set value "My cousin lives in a tree now."
data modify storage eden:database dialogues.villager.jungle.208 set value "That totem? It wasn’t carved—it grew."
data modify storage eden:database dialogues.villager.jungle.209 set value "There’s a sound only the trees can hear."
data modify storage eden:database dialogues.villager.jungle.210 set value "Trade quickly—the moss doesn’t wait."
data modify storage eden:database dialogues.villager.jungle.211 set value "You smell like Nether ash."
data modify storage eden:database dialogues.villager.jungle.212 set value "The parrots don’t mimic—they *record*."
data modify storage eden:database dialogues.villager.jungle.213 set value "Every jungle storm hides something."
data modify storage eden:database dialogues.villager.jungle.214 set value "You dream of vines yet?"
data modify storage eden:database dialogues.villager.jungle.215 set value "That compass spins for a reason."
data modify storage eden:database dialogues.villager.jungle.216 set value "We don’t have roads—just regrets."
data modify storage eden:database dialogues.villager.jungle.217 set value "I saw a zombie reading once."
data modify storage eden:database dialogues.villager.jungle.218 set value "That golem left footprints upward."
data modify storage eden:database dialogues.villager.jungle.219 set value "You ever see moss blink?"
data modify storage eden:database dialogues.villager.jungle.220 set value "You’ll hear the jungle before it finds you."
data modify storage eden:database dialogues.villager.jungle.221 set value "The old bell rings when it wants."
data modify storage eden:database dialogues.villager.jungle.222 set value "Our moss grows from memory."
data modify storage eden:database dialogues.villager.jungle.223 set value "If it glows, it’s claimed."
data modify storage eden:database dialogues.villager.jungle.224 set value "That trader never came back."
data modify storage eden:database dialogues.villager.jungle.225 set value "We don’t prune—we apologize."
data modify storage eden:database dialogues.villager.jungle.226 set value "Don’t trust anything with too many eyes."
data modify storage eden:database dialogues.villager.jungle.227 set value "The ruins breathe deeper after midnight."
data modify storage eden:database dialogues.villager.jungle.228 set value "Don’t let the parrots follow you home."
data modify storage eden:database dialogues.villager.jungle.229 set value "I don’t trade after dusk—not anymore."
data modify storage eden:database dialogues.villager.jungle.230 set value "The jungle hates redstone."
data modify storage eden:database dialogues.villager.jungle.231 set value "You stepped on sacred roots."
data modify storage eden:database dialogues.villager.jungle.232 set value "You’ll know the shrine when it knows you."
data modify storage eden:database dialogues.villager.jungle.233 set value "That idol’s eyes follow travelers."
data modify storage eden:database dialogues.villager.jungle.234 set value "Don’t eat anything you didn’t plant."
data modify storage eden:database dialogues.villager.jungle.235 set value "The jungle drinks more than water."
data modify storage eden:database dialogues.villager.jungle.236 set value "I once caught a fish that whispered my name."
data modify storage eden:database dialogues.villager.jungle.237 set value "The witch trades in names and memories."
data modify storage eden:database dialogues.villager.jungle.238 set value "Don’t look up when it gets quiet."
data modify storage eden:database dialogues.villager.jungle.239 set value "You build fast—but the vines build faster."
data modify storage eden:database dialogues.villager.jungle.240 set value "That axe is too loud for this place."
data modify storage eden:database dialogues.villager.jungle.241 set value "I heard the jungle speak."
data modify storage eden:database dialogues.villager.jungle.242 set value "You ever seen a pig disappear into mist?"
data modify storage eden:database dialogues.villager.jungle.243 set value "The ruins weren’t always ruined."
data modify storage eden:database dialogues.villager.jungle.244 set value "We lost a farmer to a tree once."
data modify storage eden:database dialogues.villager.jungle.245 set value "Your tools won’t help you here."
data modify storage eden:database dialogues.villager.jungle.246 set value "I saw cocoa beans scream."
data modify storage eden:database dialogues.villager.jungle.247 set value "The vines grow better with blood."
data modify storage eden:database dialogues.villager.jungle.248 set value "Some trees are older than the moon."
data modify storage eden:database dialogues.villager.jungle.249 set value "You feel that? The ground’s listening."
data modify storage eden:database dialogues.villager.jungle.250 set value "Even our cats wear masks now."
data modify storage eden:database dialogues.villager.jungle.251 set value "The jungle always reclaims what it lends."
data modify storage eden:database dialogues.villager.jungle.252 set value "You bring silence? Good."
data modify storage eden:database dialogues.villager.jungle.253 set value "Don’t trust that glowing flower."
data modify storage eden:database dialogues.villager.jungle.254 set value "If it’s mossy, it’s probably watching."
data modify storage eden:database dialogues.villager.jungle.255 set value "The parrots fly in circles when danger comes."
data modify storage eden:database dialogues.villager.jungle.256 set value "Stay out of the green fog."
data modify storage eden:database dialogues.villager.jungle.257 set value "You shouldn’t have picked that flower."
data modify storage eden:database dialogues.villager.jungle.258 set value "The sun doesn't shine here the same way."
data modify storage eden:database dialogues.villager.jungle.259 set value "I heard a laugh come from the vines."
data modify storage eden:database dialogues.villager.jungle.260 set value "The jungle's awake now."
data modify storage eden:database dialogues.villager.jungle.261 set value "That vine has moved again."
data modify storage eden:database dialogues.villager.jungle.262 set value "Don’t say your name near the shrine."
data modify storage eden:database dialogues.villager.jungle.263 set value "The parrots told me you’d come."
data modify storage eden:database dialogues.villager.jungle.264 set value "Never build where the jaguar sleeps."
data modify storage eden:database dialogues.villager.jungle.265 set value "We don’t keep track of how many live here."
data modify storage eden:database dialogues.villager.jungle.266 set value "The temple door opens on its own."
data modify storage eden:database dialogues.villager.jungle.267 set value "We all have stories. The jungle has more."
data modify storage eden:database dialogues.villager.jungle.268 set value "Your footsteps are too loud."
data modify storage eden:database dialogues.villager.jungle.269 set value "I once saw obsidian cry."
data modify storage eden:database dialogues.villager.jungle.270 set value "You can’t escape the roots."
data modify storage eden:database dialogues.villager.jungle.271 set value "Trade quickly—something’s watching."
data modify storage eden:database dialogues.villager.jungle.272 set value "Don’t speak of the jungle in the Nether."
data modify storage eden:database dialogues.villager.jungle.273 set value "That’s not fog—it’s spores."
data modify storage eden:database dialogues.villager.jungle.274 set value "You blinked. The vines moved."
data modify storage eden:database dialogues.villager.jungle.275 set value "I saw an eye open on a tree once."
data modify storage eden:database dialogues.villager.jungle.276 set value "The parrots keep flying west."
data modify storage eden:database dialogues.villager.jungle.277 set value "Some ruins don’t want to be found."
data modify storage eden:database dialogues.villager.jungle.278 set value "You better hope that wasn't sacred."
data modify storage eden:database dialogues.villager.jungle.279 set value "That sound? Not thunder."
data modify storage eden:database dialogues.villager.jungle.280 set value "We don’t use doors—we use warnings."
data modify storage eden:database dialogues.villager.jungle.281 set value "Watch your back near the glowshrooms."
data modify storage eden:database dialogues.villager.jungle.282 set value "I don’t trust anyone who walks straight."
data modify storage eden:database dialogues.villager.jungle.283 set value "Don’t point at the stone face."
data modify storage eden:database dialogues.villager.jungle.284 set value "You came alone? Bold."
data modify storage eden:database dialogues.villager.jungle.285 set value "The jungle accepts, but it never forgets."
data modify storage eden:database dialogues.villager.jungle.286 set value "Don’t rest beneath twisted roots."
data modify storage eden:database dialogues.villager.jungle.287 set value "That humming? That’s not music."
data modify storage eden:database dialogues.villager.jungle.288 set value "You should leave before the rain comes."
data modify storage eden:database dialogues.villager.jungle.289 set value "The jungle likes you—for now."
data modify storage eden:database dialogues.villager.jungle.290 set value "Don't eat the purple mushrooms."
data modify storage eden:database dialogues.villager.jungle.291 set value "The parrots stopped talking. Something’s wrong."
data modify storage eden:database dialogues.villager.jungle.292 set value "You feel heavier here, don’t you?"
data modify storage eden:database dialogues.villager.jungle.293 set value "That sound means the temple’s waking."
data modify storage eden:database dialogues.villager.jungle.294 set value "The vines are listening."
data modify storage eden:database dialogues.villager.jungle.295 set value "You brought gifts, right?"
data modify storage eden:database dialogues.villager.jungle.296 set value "The canopy saw what you did."
data modify storage eden:database dialogues.villager.jungle.297 set value "You hear the footsteps too?"
data modify storage eden:database dialogues.villager.jungle.298 set value "Your torch just flickered—run."
data modify storage eden:database dialogues.villager.jungle.299 set value "We don’t say goodbye here—only good luck."
data modify storage eden:database dialogues.villager.jungle.300 set value "Can you build me a treehouse? Ground’s too creepy."
data modify storage eden:database dialogues.villager.jungle.301 set value "I need a bridge across that river—I’m tired of swimming."
data modify storage eden:database dialogues.villager.jungle.302 set value "Could you carve out a safe path through the vines?"
data modify storage eden:database dialogues.villager.jungle.303 set value "I’d love a lookout tower—too many creepers in the leaves."
data modify storage eden:database dialogues.villager.jungle.304 set value "Can you make a bamboo fence to keep out ocelots?"
data modify storage eden:database dialogues.villager.jungle.305 set value "We need a proper dock—boats keep floating away."
data modify storage eden:database dialogues.villager.jungle.306 set value "A raised hut would be great—ground’s too soggy."
data modify storage eden:database dialogues.villager.jungle.307 set value "Make me a farm up in the trees—jungle style!"
data modify storage eden:database dialogues.villager.jungle.308 set value "Can you build a nether portal hut so we don’t attract piglins?"
data modify storage eden:database dialogues.villager.jungle.309 set value "I’d like a quiet meditation spot near the parrots."
data modify storage eden:database dialogues.villager.jungle.310 set value "Got time to put up some tiki torches? Too many shadows."
data modify storage eden:database dialogues.villager.jungle.311 set value "Think you could make a mossy shrine with vines and glow berries?"
data modify storage eden:database dialogues.villager.jungle.312 set value "I want a ladder system—stairs are too old-school."
data modify storage eden:database dialogues.villager.jungle.313 set value "Build a little hut for brewing—there’s magic in the jungle!"
data modify storage eden:database dialogues.villager.jungle.314 set value "Could you give me a platform just for cocoa farming?"
data modify storage eden:database dialogues.villager.jungle.315 set value "Let’s get a canopy walkway going—no more falling."
data modify storage eden:database dialogues.villager.jungle.316 set value "Make me a waterfall hideout. Just trust me."
data modify storage eden:database dialogues.villager.jungle.317 set value "A jungle bathhouse would be awesome—vines and all."
data modify storage eden:database dialogues.villager.jungle.318 set value "I need a big leaf roof. Yes, I know that’s not a block."
data modify storage eden:database dialogues.villager.jungle.319 set value "Could use some lanterns on the jungle paths—gets spooky fast."
data modify storage eden:database dialogues.villager.jungle.320 set value "Build a bonfire spot! Perfect for late-night drum circles."
data modify storage eden:database dialogues.villager.jungle.321 set value "A zipline would be cool. Or, uh, a safe-ish version."
data modify storage eden:database dialogues.villager.jungle.322 set value "We need a safe pen for our pandas—yes, all of them."
data modify storage eden:database dialogues.villager.jungle.323 set value "Can you make a hanging garden? Jungle's got style."
data modify storage eden:database dialogues.villager.jungle.324 set value "Add a wooden signpost—I keep looping in circles."
data modify storage eden:database dialogues.villager.jungle.325 set value "I want a mushroom lounge. Don’t ask questions."
data modify storage eden:database dialogues.villager.jungle.326 set value "Got time to build a hidden tree vault? For... reasons."
data modify storage eden:database dialogues.villager.jungle.327 set value "A tall watchtower would help spot pillagers from miles away."
data modify storage eden:database dialogues.villager.jungle.328 set value "Let’s build a little café. Jungle smoothies, maybe?"
data modify storage eden:database dialogues.villager.jungle.329 set value "Can you carve me a cave home behind the waterfall?"
data modify storage eden:database dialogues.villager.jungle.330 set value "Put a bell up high—where the parrots hang out."
data modify storage eden:database dialogues.villager.jungle.331 set value "I need a treetop sleeping pod—no more creeper wake-ups!"
data modify storage eden:database dialogues.villager.jungle.332 set value "We need a boat launch. Current’s too strong for swimming."
data modify storage eden:database dialogues.villager.jungle.333 set value "Mind building a ceremonial fire ring? Just for show. Probably."
data modify storage eden:database dialogues.villager.jungle.334 set value "Add some benches near the cocoa trees—snack break zone."
data modify storage eden:database dialogues.villager.jungle.335 set value "Build me a vine-covered tower. A tall one. Epic."
data modify storage eden:database dialogues.villager.jungle.336 set value "We could use a little open-air library. Jungle lore, y’know."
data modify storage eden:database dialogues.villager.jungle.337 set value "Can you make a tree nursery? Gotta keep the jungle strong."
data modify storage eden:database dialogues.villager.jungle.338 set value "A zip-bridge from tree to tree would be real handy."
data modify storage eden:database dialogues.villager.jungle.339 set value "Put some banners up! Our village needs flair."
data modify storage eden:database dialogues.villager.jungle.340 set value "I want a little drum stage—parrot concerts, maybe?"
data modify storage eden:database dialogues.villager.jungle.341 set value "Could you fix that overgrown ruin? Might be treasure in there."
data modify storage eden:database dialogues.villager.jungle.342 set value "Let’s build a treetop plaza—hangout spot in the sky!"
data modify storage eden:database dialogues.villager.jungle.343 set value "I need a hidden nook for enchanting. Very hush-hush."
data modify storage eden:database dialogues.villager.jungle.344 set value "Build a chill-out spot with melons and bamboo snacks."
data modify storage eden:database dialogues.villager.jungle.345 set value "Some leaf sculptures would make this place pop!"
data modify storage eden:database dialogues.villager.jungle.346 set value "A jungle sauna sounds cozy. Make it steamy."
data modify storage eden:database dialogues.villager.jungle.347 set value "I want a mossy meditation platform under the moonlight."
data modify storage eden:database dialogues.villager.jungle.348 set value "Can you dig out a storage cave and make it look cool?"
data modify storage eden:database dialogues.villager.jungle.349 set value "Surprise me—just make it leafy, mysterious, and a little weird."