data modify storage eden:database dialogues.villager.plains.100 set value "The wheat's looking good this season."
data modify storage eden:database dialogues.villager.plains.101 set value "Mind the scarecrow—he’s doing his best."
data modify storage eden:database dialogues.villager.plains.102 set value "Sun’s high, crops are dry, time to water."
data modify storage eden:database dialogues.villager.plains.103 set value "A good shovel is worth more than gold."
data modify storage eden:database dialogues.villager.plains.104 set value "If you see a pillager, don’t wave."
data modify storage eden:database dialogues.villager.plains.105 set value "Nothing like the smell of fresh hay."
data modify storage eden:database dialogues.villager.plains.106 set value "The cows have been jumpy lately."
data modify storage eden:database dialogues.villager.plains.107 set value "Sunrise here always feels safe."
data modify storage eden:database dialogues.villager.plains.108 set value "We don’t trust foxes near the henhouse."
data modify storage eden:database dialogues.villager.plains.109 set value "A strong fence is a peaceful night's sleep."
data modify storage eden:database dialogues.villager.plains.110 set value "Trade fair, trade often—that’s our way."
data modify storage eden:database dialogues.villager.plains.111 set value "Don’t step on the crops, friend."
data modify storage eden:database dialogues.villager.plains.112 set value "Some folks think the bell keeps monsters away."
data modify storage eden:database dialogues.villager.plains.113 set value "Rain's good luck for carrots, bad for boots."
data modify storage eden:database dialogues.villager.plains.114 set value "I once saw a creeper get scared of a cat."
data modify storage eden:database dialogues.villager.plains.115 set value "The plains roll on forever—until they don’t."
data modify storage eden:database dialogues.villager.plains.116 set value "Stick to the path and you’ll do fine."
data modify storage eden:database dialogues.villager.plains.117 set value "We plant potatoes because they listen."
data modify storage eden:database dialogues.villager.plains.118 set value "There’s a rhythm to the harvest."
data modify storage eden:database dialogues.villager.plains.119 set value "The wind talks if you stand still long enough."
data modify storage eden:database dialogues.villager.plains.120 set value "Our iron golem’s got a name, you know."
data modify storage eden:database dialogues.villager.plains.121 set value "These boots? Handmade from tanned leather."
data modify storage eden:database dialogues.villager.plains.122 set value "Don’t trust wandering traders before noon."
data modify storage eden:database dialogues.villager.plains.123 set value "We rotate crops—helps the soil and the soul."
data modify storage eden:database dialogues.villager.plains.124 set value "If it squeals in the dark, it ain’t a pig."
data modify storage eden:database dialogues.villager.plains.125 set value "You ever try milking a mooshroom?"
data modify storage eden:database dialogues.villager.plains.126 set value "Campfires keep stories warm and mobs out."
data modify storage eden:database dialogues.villager.plains.127 set value "Nothing beats fresh bread on a foggy morning."
data modify storage eden:database dialogues.villager.plains.128 set value "You see clouds, I see weather warnings."
data modify storage eden:database dialogues.villager.plains.129 set value "We had a library once—until lightning struck."
data modify storage eden:database dialogues.villager.plains.130 set value "Never argue with a farmer holding a hoe."
data modify storage eden:database dialogues.villager.plains.131 set value "We don’t like it when strangers break fences."
data modify storage eden:database dialogues.villager.plains.132 set value "It’s the little chores that keep you alive."
data modify storage eden:database dialogues.villager.plains.133 set value "You can hear wolves at night—sometimes closer."
data modify storage eden:database dialogues.villager.plains.134 set value "A good crop can make up for a bad moon."
data modify storage eden:database dialogues.villager.plains.135 set value "The grass hums when storms roll in."
data modify storage eden:database dialogues.villager.plains.136 set value "I know every chicken by name here."
data modify storage eden:database dialogues.villager.plains.137 set value "The bell rings when danger’s close—or dinner’s ready."
data modify storage eden:database dialogues.villager.plains.138 set value "Bartering is tradition. So is being stubborn."
data modify storage eden:database dialogues.villager.plains.139 set value "The fields feed more than stomachs."
data modify storage eden:database dialogues.villager.plains.140 set value "Don’t whistle after dark—it calls them."
data modify storage eden:database dialogues.villager.plains.141 set value "Sunflowers always face east—just like old Thom."
data modify storage eden:database dialogues.villager.plains.142 set value "There’s a slime patch east of the creek."
data modify storage eden:database dialogues.villager.plains.143 set value "Stay off the pasture path after midnight."
data modify storage eden:database dialogues.villager.plains.144 set value "Nothing grows on the hill for a reason."
data modify storage eden:database dialogues.villager.plains.145 set value "Our well is older than the village itself."
data modify storage eden:database dialogues.villager.plains.146 set value "Trade me wheat and I’ll tell you a secret."
data modify storage eden:database dialogues.villager.plains.147 set value "Even scarecrows need a name."
data modify storage eden:database dialogues.villager.plains.148 set value "Don't leave your bed too far from the bell."
data modify storage eden:database dialogues.villager.plains.149 set value "I don’t trust fences that swing open alone."
data modify storage eden:database dialogues.villager.plains.150 set value "We bury broken tools under the apple tree."
data modify storage eden:database dialogues.villager.plains.151 set value "The plains seem calm—until they’re not."
data modify storage eden:database dialogues.villager.plains.152 set value "Sometimes the crops whisper old songs."
data modify storage eden:database dialogues.villager.plains.153 set value "We once had a priest who talked to sheep."
data modify storage eden:database dialogues.villager.plains.154 set value "If your cow won’t stop staring, move camps."
data modify storage eden:database dialogues.villager.plains.155 set value "A cat will always find you before a creeper does."
data modify storage eden:database dialogues.villager.plains.156 set value "You can tell the weather by the pigs’ tails."
data modify storage eden:database dialogues.villager.plains.157 set value "Pillagers hate rain—lucky for us."
data modify storage eden:database dialogues.villager.plains.158 set value "Every scarecrow wears an old hat with a tale."
data modify storage eden:database dialogues.villager.plains.159 set value "The river runs red in spring—not blood, just berries."
data modify storage eden:database dialogues.villager.plains.160 set value "If your hoe glows green, stop digging."
data modify storage eden:database dialogues.villager.plains.161 set value "Never ignore the old oak’s shadow."
data modify storage eden:database dialogues.villager.plains.162 set value "We salt the paths before fog rolls in."
data modify storage eden:database dialogues.villager.plains.163 set value "A witch once gave us a year of good wheat."
data modify storage eden:database dialogues.villager.plains.164 set value "Sleep with one eye open if you heard bells twice."
data modify storage eden:database dialogues.villager.plains.165 set value "Rainwater’s fine—if it hasn’t shimmered first."
data modify storage eden:database dialogues.villager.plains.166 set value "Lightning struck our stables three times last month."
data modify storage eden:database dialogues.villager.plains.167 set value "We say thanks before cutting the first stalk."
data modify storage eden:database dialogues.villager.plains.168 set value "If the wind changes mid-sentence, stop talking."
data modify storage eden:database dialogues.villager.plains.169 set value "You brought beets? I suppose I can forgive you."
data modify storage eden:database dialogues.villager.plains.170 set value "The plains remember who trampled them."
data modify storage eden:database dialogues.villager.plains.171 set value "The scarecrow’s scarf belonged to a hero."
data modify storage eden:database dialogues.villager.plains.172 set value "You ever feed the horses apples with golden spots?"
data modify storage eden:database dialogues.villager.plains.173 set value "When the dogs stop barking, get inside."
data modify storage eden:database dialogues.villager.plains.174 set value "We don’t grow pumpkins without asking the old man."
data modify storage eden:database dialogues.villager.plains.175 set value "That patch never grows anything, and we don’t ask why."
data modify storage eden:database dialogues.villager.plains.176 set value "You ever seen a fox walk backward?"
data modify storage eden:database dialogues.villager.plains.177 set value "Don’t trade on an empty stomach or a full moon."
data modify storage eden:database dialogues.villager.plains.178 set value "A creeper in tall grass is a silent goodbye."
data modify storage eden:database dialogues.villager.plains.179 set value "We burn hay in fall to keep the spirits warm."
data modify storage eden:database dialogues.villager.plains.180 set value "Sunsets mean more when the wind is still."
data modify storage eden:database dialogues.villager.plains.181 set value "Don’t pick the red flower near the church."
data modify storage eden:database dialogues.villager.plains.182 set value "We measure time in how long bread takes to rise."
data modify storage eden:database dialogues.villager.plains.183 set value "Some fields grow dreams instead of wheat."
data modify storage eden:database dialogues.villager.plains.184 set value "The horses never go near the boundary stones."
data modify storage eden:database dialogues.villager.plains.185 set value "Our cats come and go, but they always return with news."
data modify storage eden:database dialogues.villager.plains.186 set value "A rabbit ran through the corn and vanished."
data modify storage eden:database dialogues.villager.plains.187 set value "We don't eat meat that doesn’t cast a shadow."
data modify storage eden:database dialogues.villager.plains.188 set value "The windmill hasn’t turned in years—and yet it works."
data modify storage eden:database dialogues.villager.plains.189 set value "If the scarecrow faces west, trouble’s brewing."
data modify storage eden:database dialogues.villager.plains.190 set value "There’s a bell tone only the elders hear."
data modify storage eden:database dialogues.villager.plains.191 set value "A boy once vanished chasing a butterfly at dusk."
data modify storage eden:database dialogues.villager.plains.192 set value "We don’t plow under the twin oaks—ever."
data modify storage eden:database dialogues.villager.plains.193 set value "Strangers bring coin. Trouble brings itself."
data modify storage eden:database dialogues.villager.plains.194 set value "Trade quick, eat slow—that’s how we live."
data modify storage eden:database dialogues.villager.plains.195 set value "Horses get spooked when the clouds sit low."
data modify storage eden:database dialogues.villager.plains.196 set value "We keep our haylofts locked for good reason."
data modify storage eden:database dialogues.villager.plains.197 set value "A shadow moved through the wheat last night."
data modify storage eden:database dialogues.villager.plains.198 set value "That house hasn’t had a fire lit in years."
data modify storage eden:database dialogues.villager.plains.199 set value "No one remembers planting the orchard."
data modify storage eden:database dialogues.villager.plains.200 set value "I once found a skeleton with a wheat hat."
data modify storage eden:database dialogues.villager.plains.201 set value "Morning dew hides secrets in the fields."
data modify storage eden:database dialogues.villager.plains.202 set value "A fox’s shadow never lies."
data modify storage eden:database dialogues.villager.plains.203 set value "Old Thom’s scarecrow still guards the wheat."
data modify storage eden:database dialogues.villager.plains.204 set value "Wolves howl louder when the moon is full."
data modify storage eden:database dialogues.villager.plains.205 set value "Don’t follow the road past the old barn."
data modify storage eden:database dialogues.villager.plains.206 set value "The harvest festival always feels like magic."
data modify storage eden:database dialogues.villager.plains.207 set value "A well-aimed arrow saves more than a sword."
data modify storage eden:database dialogues.villager.plains.208 set value "Cats watch over the livestock with sharp eyes."
data modify storage eden:database dialogues.villager.plains.209 set value "We store our secrets in old oak barrels."
data modify storage eden:database dialogues.villager.plains.210 set value "Lightning once split the tallest tree in half."
data modify storage eden:database dialogues.villager.plains.211 set value "Beware the silence after a rainstorm."
data modify storage eden:database dialogues.villager.plains.212 set value "A good harvest can calm a restless heart."
data modify storage eden:database dialogues.villager.plains.213 set value "Don’t leave your doors unlocked at dusk."
data modify storage eden:database dialogues.villager.plains.214 set value "The river’s song changes with the seasons."
data modify storage eden:database dialogues.villager.plains.215 set value "Mushrooms grow in the shadows of forgotten barns."
data modify storage eden:database dialogues.villager.plains.216 set value "The scarecrow’s hat blew off last autumn."
data modify storage eden:database dialogues.villager.plains.217 set value "There’s a fox den near the old millstone."
data modify storage eden:database dialogues.villager.plains.218 set value "We say a prayer before planting the first seed."
data modify storage eden:database dialogues.villager.plains.219 set value "The wind can carry a whisper all the way home."
data modify storage eden:database dialogues.villager.plains.220 set value "We always harvest by the light of the moon."
data modify storage eden:database dialogues.villager.plains.221 set value "A storm is brewing beyond the western hills."
data modify storage eden:database dialogues.villager.plains.222 set value "If you find a cracked hoe, it’s bad luck."
data modify storage eden:database dialogues.villager.plains.223 set value "The barn owl watches over us at night."
data modify storage eden:database dialogues.villager.plains.224 set value "Don’t trust strangers bearing shiny trinkets."
data modify storage eden:database dialogues.villager.plains.225 set value "The wheat bends but never breaks."
data modify storage eden:database dialogues.villager.plains.226 set value "You can tell a good farmer by their boots."
data modify storage eden:database dialogues.villager.plains.227 set value "The old well sings when the wind is right."
data modify storage eden:database dialogues.villager.plains.228 set value "Beware the crook in the road by the sycamore."
data modify storage eden:database dialogues.villager.plains.229 set value "The bells ring louder when danger is near."
data modify storage eden:database dialogues.villager.plains.230 set value "We keep the harvest safe in old wooden crates."
data modify storage eden:database dialogues.villager.plains.231 set value "The chickens don’t cross the path after dark."
data modify storage eden:database dialogues.villager.plains.232 set value "A shadow fell across the field last night."
data modify storage eden:database dialogues.villager.plains.233 set value "Foxes steal more than just eggs around here."
data modify storage eden:database dialogues.villager.plains.234 set value "The scarecrow’s eyes glow at midnight."
data modify storage eden:database dialogues.villager.plains.235 set value "We hide gold beneath the stone by the creek."
data modify storage eden:database dialogues.villager.plains.236 set value "The harvest moon shines bright on the plains."
data modify storage eden:database dialogues.villager.plains.237 set value "Old fences tell stories if you listen closely."
data modify storage eden:database dialogues.villager.plains.238 set value "A quiet farm is a safe farm."
data modify storage eden:database dialogues.villager.plains.239 set value "Never ignore the crackling in the dry grass."
data modify storage eden:database dialogues.villager.plains.240 set value "The mill’s wheel hasn’t stopped turning in years."
data modify storage eden:database dialogues.villager.plains.241 set value "A good harvest keeps the village alive."
data modify storage eden:database dialogues.villager.plains.242 set value "We respect the land; it gives us life."
data modify storage eden:database dialogues.villager.plains.243 set value "The morning sun warms the soil just right."
data modify storage eden:database dialogues.villager.plains.244 set value "Foxes howl when the moon hides behind clouds."
data modify storage eden:database dialogues.villager.plains.245 set value "The scarecrow’s hat never stays on long."
data modify storage eden:database dialogues.villager.plains.246 set value "Beware the eyes that shine in the dark."
data modify storage eden:database dialogues.villager.plains.247 set value "A single seed holds the promise of many."
data modify storage eden:database dialogues.villager.plains.248 set value "The wind whispers secrets through the wheat."
data modify storage eden:database dialogues.villager.plains.249 set value "Farmers talk to the soil when they think no one’s listening."
data modify storage eden:database dialogues.villager.plains.250 set value "The barn doors creak even when no one is near."
data modify storage eden:database dialogues.villager.plains.251 set value "A storm can change everything in a heartbeat."
data modify storage eden:database dialogues.villager.plains.252 set value "The horses know when danger is near before we do."
data modify storage eden:database dialogues.villager.plains.253 set value "Old Thom’s barn holds more than just hay."
data modify storage eden:database dialogues.villager.plains.254 set value "The sun sets slower here, like it’s saying goodbye."
data modify storage eden:database dialogues.villager.plains.255 set value "The river carries more than just water downstream."
data modify storage eden:database dialogues.villager.plains.256 set value "The scarecrow watches, even when we don’t."
data modify storage eden:database dialogues.villager.plains.257 set value "Every harvest is a story waiting to be told."
data modify storage eden:database dialogues.villager.plains.258 set value "The windmill’s song soothes the restless nights."
data modify storage eden:database dialogues.villager.plains.259 set value "A quiet night can be the most dangerous."
data modify storage eden:database dialogues.villager.plains.260 set value "The fields are never truly empty after dark."
data modify storage eden:database dialogues.villager.plains.261 set value "The glow of fireflies marks the safe paths."
data modify storage eden:database dialogues.villager.plains.262 set value "We keep our secrets locked away with the grain."
data modify storage eden:database dialogues.villager.plains.263 set value "The old oak tree remembers everything."
data modify storage eden:database dialogues.villager.plains.264 set value "The crops sway like they’re dancing in the breeze."
data modify storage eden:database dialogues.villager.plains.265 set value "Don’t trust the quiet spots in the forest."
data modify storage eden:database dialogues.villager.plains.266 set value "The moonlight makes the wheat shimmer like gold."
data modify storage eden:database dialogues.villager.plains.267 set value "The bell tolls for those who listen carefully."
data modify storage eden:database dialogues.villager.plains.268 set value "Foxes run faster when the sun goes down."
data modify storage eden:database dialogues.villager.plains.269 set value "The scarecrow’s shadow stretches far at dusk."
data modify storage eden:database dialogues.villager.plains.270 set value "The river’s edge hides more than just stones."
data modify storage eden:database dialogues.villager.plains.271 set value "We plant hope with every seed we sow."
data modify storage eden:database dialogues.villager.plains.272 set value "A single crow can warn of coming storms."
data modify storage eden:database dialogues.villager.plains.273 set value "The wind carries laughter and whispers alike."
data modify storage eden:database dialogues.villager.plains.274 set value "The fields grow quiet when the night falls."
data modify storage eden:database dialogues.villager.plains.275 set value "The horses’ hooves tell stories on the dirt roads."
data modify storage eden:database dialogues.villager.plains.276 set value "The barn’s creak can sound like a ghost’s sigh."
data modify storage eden:database dialogues.villager.plains.277 set value "The harvest’s bounty is a gift and a promise."
data modify storage eden:database dialogues.villager.plains.278 set value "The moon watches over us just as the sun does."
data modify storage eden:database dialogues.villager.plains.279 set value "A rustle in the grass can mean many things."
data modify storage eden:database dialogues.villager.plains.280 set value "The scarecrow keeps its silent vigil through the night."
data modify storage eden:database dialogues.villager.plains.281 set value "The old fence stands strong against time and weather."
data modify storage eden:database dialogues.villager.plains.282 set value "The river’s murmur can soothe the weariest soul."
data modify storage eden:database dialogues.villager.plains.283 set value "The fields bloom bright under the midday sun."
data modify storage eden:database dialogues.villager.plains.284 set value "The wind carries the scent of fresh earth."
data modify storage eden:database dialogues.villager.plains.285 set value "The horses neigh softly when dawn breaks."
data modify storage eden:database dialogues.villager.plains.286 set value "The barn doors creak open with the morning breeze."
data modify storage eden:database dialogues.villager.plains.287 set value "The harvest moon lights the way home."
data modify storage eden:database dialogues.villager.plains.288 set value "The scarecrow’s gaze never falters, even in the dark."
data modify storage eden:database dialogues.villager.plains.289 set value "The river’s reflection holds a thousand stories."
data modify storage eden:database dialogues.villager.plains.290 set value "The fields whisper tales of seasons long past."
data modify storage eden:database dialogues.villager.plains.291 set value "The wind hums a tune only the old remember."
data modify storage eden:database dialogues.villager.plains.292 set value "The horses’ shadows dance in the setting sun."
data modify storage eden:database dialogues.villager.plains.293 set value "The barn stands as a guardian over the plains."
data modify storage eden:database dialogues.villager.plains.294 set value "The harvest is the village’s heartbeat and hope."
data modify storage eden:database dialogues.villager.plains.295 set value "The moon’s glow turns the fields silver at night."
data modify storage eden:database dialogues.villager.plains.296 set value "The scarecrow stands tall, a silent protector."
data modify storage eden:database dialogues.villager.plains.297 set value "The river’s song is the lullaby of the plains."
data modify storage eden:database dialogues.villager.plains.298 set value "The fields are alive with the promise of tomorrow."
data modify storage eden:database dialogues.villager.plains.299 set value "The wind carries our stories across the plains."
data modify storage eden:database dialogues.villager.plains.300 set value "Could you build me a bigger barn? The cows are cramped."
data modify storage eden:database dialogues.villager.plains.301 set value "Mind putting up a windmill? Even if it doesn’t spin, it’ll look neat."
data modify storage eden:database dialogues.villager.plains.302 set value "Think you could lay a path through the wheat fields?"
data modify storage eden:database dialogues.villager.plains.303 set value "I’d love a fence—zombies keep knocking at my door."
data modify storage eden:database dialogues.villager.plains.304 set value "Can you build a scarecrow? Just for the vibes."
data modify storage eden:database dialogues.villager.plains.305 set value "A little pond with ducks—er, chickens—would be perfect."
data modify storage eden:database dialogues.villager.plains.306 set value "I need a grain silo, even if we don’t use it."
data modify storage eden:database dialogues.villager.plains.307 set value "Build me a wraparound porch. I want to sit and do nothing."
data modify storage eden:database dialogues.villager.plains.308 set value "Could you fix the roof before it caves in again?"
data modify storage eden:database dialogues.villager.plains.309 set value "Some lantern posts along the road would be super helpful."
data modify storage eden:database dialogues.villager.plains.310 set value "Can we get a town center or something? I keep losing people."
data modify storage eden:database dialogues.villager.plains.311 set value "A stable for horses would be nice, even imaginary ones."
data modify storage eden:database dialogues.villager.plains.312 set value "I’d love a bakery—smell of bread keeps me sane."
data modify storage eden:database dialogues.villager.plains.313 set value "Can you build a windbreak wall? The wind here howls."
data modify storage eden:database dialogues.villager.plains.314 set value "Mind making me a cozy attic space? I’ve got secret stuff."
data modify storage eden:database dialogues.villager.plains.315 set value "I want a picket fence. Fancy, huh?"
data modify storage eden:database dialogues.villager.plains.316 set value "Build a big sign with the village name on it or something cool."
data modify storage eden:database dialogues.villager.plains.317 set value "Can you dig me a root cellar? My potatoes need a home."
data modify storage eden:database dialogues.villager.plains.318 set value "Add some hay bales around—I like the rustic look."
data modify storage eden:database dialogues.villager.plains.319 set value "I need a bench by the wheat field. Watching it sway is calming."
data modify storage eden:database dialogues.villager.plains.320 set value "Some flower boxes under the windows would be nice."
data modify storage eden:database dialogues.villager.plains.321 set value "We should build a village hall, even if no one shows up."
data modify storage eden:database dialogues.villager.plains.322 set value "I want a picnic spot near the tree line."
data modify storage eden:database dialogues.villager.plains.323 set value "Build a little stage. Talent shows are underrated."
data modify storage eden:database dialogues.villager.plains.324 set value "Can you make a stone well that doesn’t look so... square?"
data modify storage eden:database dialogues.villager.plains.325 set value "A silo-shaped watchtower? Best of both worlds."
data modify storage eden:database dialogues.villager.plains.326 set value "Let’s get a water trough for the animals."
data modify storage eden:database dialogues.villager.plains.327 set value "Can you build a wooden bridge over the stream?"
data modify storage eden:database dialogues.villager.plains.328 set value "A small library with cozy corners would be amazing."
data modify storage eden:database dialogues.villager.plains.329 set value "I need a tool shed. My tools are everywhere."
data modify storage eden:database dialogues.villager.plains.330 set value "Let’s build a gazebo! No clue what for, but it sounds nice."
data modify storage eden:database dialogues.villager.plains.331 set value "Can you set up a trading stall for me? Gotta show off my carrots."
data modify storage eden:database dialogues.villager.plains.332 set value "How about a tree-lined path from here to the next village?"
data modify storage eden:database dialogues.villager.plains.333 set value "Can you make me a sunroom? I like light but not skeletons."
data modify storage eden:database dialogues.villager.plains.334 set value "Add a smokehouse. It doesn’t need to work—just look smoky."
data modify storage eden:database dialogues.villager.plains.335 set value "I want a big old farmhouse. Two floors, one dream."
data modify storage eden:database dialogues.villager.plains.336 set value "Can you build a bell tower that actually has a bell?"
data modify storage eden:database dialogues.villager.plains.337 set value "We need a compost station that doesn’t smell."
data modify storage eden:database dialogues.villager.plains.338 set value "Make a sitting circle for evening chats. Or gossip."
data modify storage eden:database dialogues.villager.plains.339 set value "Could you decorate the town with banners? Something cheery."
data modify storage eden:database dialogues.villager.plains.340 set value "I need a garden plot. Preferably not where the pigs hang out."
data modify storage eden:database dialogues.villager.plains.341 set value "Can you build a chicken coop that’s not an eyesore?"
data modify storage eden:database dialogues.villager.plains.342 set value "Let’s get a stone fence going—classy and durable."
data modify storage eden:database dialogues.villager.plains.343 set value "I want a mini maze made of hedges. Don’t judge me."
data modify storage eden:database dialogues.villager.plains.344 set value "Build a monument to wheat. For real. It deserves it."
data modify storage eden:database dialogues.villager.plains.345 set value "Make a hilltop lookout. Gotta spot those pillagers early."
data modify storage eden:database dialogues.villager.plains.346 set value "A horse track would be fun, even if no one races."
data modify storage eden:database dialogues.villager.plains.347 set value "Build a nice dock at the lake, even if we don’t fish."
data modify storage eden:database dialogues.villager.plains.348 set value "I want a tree with a swing. Just one."
data modify storage eden:database dialogues.villager.plains.349 set value "Surprise me! As long as it’s flat, friendly, and full of wheat."