data modify storage eden:database dialogues.villager.savanna.100 set value "The sun bakes my crops and my soul alike."
data modify storage eden:database dialogues.villager.savanna.101 set value "Stolen again… third creeper this week."
data modify storage eden:database dialogues.villager.savanna.102 set value "If you touch my composter, I will scream."
data modify storage eden:database dialogues.villager.savanna.103 set value "This isn’t a village—it’s a skeleton buffet."
data modify storage eden:database dialogues.villager.savanna.104 set value "Trade? Only if you brought emeralds and respect."
data modify storage eden:database dialogues.villager.savanna.105 set value "I saw a witch once. Still recovering."
data modify storage eden:database dialogues.villager.savanna.106 set value "My cow wandered off and joined a raid. Brave fool."
data modify storage eden:database dialogues.villager.savanna.107 set value "It’s hot. Like nether-hot."
data modify storage eden:database dialogues.villager.savanna.108 set value "Go ahead, sleep in my bed… again."
data modify storage eden:database dialogues.villager.savanna.109 set value "I had dreams once. Then the pillagers came."
data modify storage eden:database dialogues.villager.savanna.110 set value "No, I don’t want to be a librarian. Stop placing lecterns."
data modify storage eden:database dialogues.villager.savanna.111 set value "You brought a goat here? WHY?"
data modify storage eden:database dialogues.villager.savanna.112 set value "Ever try to hoe dry dirt? It’s an emotional experience."
data modify storage eden:database dialogues.villager.savanna.113 set value "This biome is cursed. The cats know it."
data modify storage eden:database dialogues.villager.savanna.114 set value "Leave my melons alone, wanderer."
data modify storage eden:database dialogues.villager.savanna.115 set value "I used to farm. Now I fear the night."
data modify storage eden:database dialogues.villager.savanna.116 set value "You think gold is rare? Try peace."
data modify storage eden:database dialogues.villager.savanna.117 set value "Stop ringing the bell. You’re scaring the elders."
data modify storage eden:database dialogues.villager.savanna.118 set value "The iron golem won’t protect you from me."
data modify storage eden:database dialogues.villager.savanna.119 set value "If I had a totem every time I got ignored…"
data modify storage eden:database dialogues.villager.savanna.120 set value "Even the wandering trader looks down on us."
data modify storage eden:database dialogues.villager.savanna.121 set value "My hut has more sand than bed now."
data modify storage eden:database dialogues.villager.savanna.122 set value "Go ahead. Build another portal near our village."
data modify storage eden:database dialogues.villager.savanna.123 set value "That’s not a hat. That’s my profession."
data modify storage eden:database dialogues.villager.savanna.124 set value "One more llama spit and I riot."
data modify storage eden:database dialogues.villager.savanna.125 set value "Sunrise. Again. Joyless as ever."
data modify storage eden:database dialogues.villager.savanna.126 set value "We had a cleric. He joined the Illagers."
data modify storage eden:database dialogues.villager.savanna.127 set value "You know what doesn’t grow in the savanna? Hope."
data modify storage eden:database dialogues.villager.savanna.128 set value "I can’t remember the last time it rained."
data modify storage eden:database dialogues.villager.savanna.129 set value "Is this even a well or just a dry hole of despair?"
data modify storage eden:database dialogues.villager.savanna.130 set value "You brought phantoms, didn’t you?"
data modify storage eden:database dialogues.villager.savanna.131 set value "I once had 12 pigs. Now I have silence."
data modify storage eden:database dialogues.villager.savanna.132 set value "If you want a deal, you better bring carrots."
data modify storage eden:database dialogues.villager.savanna.133 set value "We don’t trade with people wearing skulls."
data modify storage eden:database dialogues.villager.savanna.134 set value "Your enchanted pants won’t impress me."
data modify storage eden:database dialogues.villager.savanna.135 set value "This is acacia country. Learn to love orange."
data modify storage eden:database dialogues.villager.savanna.136 set value "Even the cacti look tired."
data modify storage eden:database dialogues.villager.savanna.137 set value "Another day, another creeper in the fields."
data modify storage eden:database dialogues.villager.savanna.138 set value "I’d fish, but the water tastes like regret."
data modify storage eden:database dialogues.villager.savanna.139 set value "Don’t punch the golem unless you want a fast trip to spawn."
data modify storage eden:database dialogues.villager.savanna.140 set value "Sleep? Only if the zombies let me."
data modify storage eden:database dialogues.villager.savanna.141 set value "Stop looking in my chest. That’s private hay."
data modify storage eden:database dialogues.villager.savanna.142 set value "If you’re looking for joy, dig deeper."
data modify storage eden:database dialogues.villager.savanna.143 set value "My father was a mason. He died building that ugly path."
data modify storage eden:database dialogues.villager.savanna.144 set value "The acacia planks whisper at night."
data modify storage eden:database dialogues.villager.savanna.145 set value "I envy the wandering trader. At least he wanders."
data modify storage eden:database dialogues.villager.savanna.146 set value "You brought a jukebox? We don’t dance here."
data modify storage eden:database dialogues.villager.savanna.147 set value "You think it’s hard surviving? Try farming on dust."
data modify storage eden:database dialogues.villager.savanna.148 set value "This biome is where armor goes to rust."
data modify storage eden:database dialogues.villager.savanna.149 set value "My job block? Stolen. Again."
data modify storage eden:database dialogues.villager.savanna.150 set value "The bell tolls for someone. Probably me."
data modify storage eden:database dialogues.villager.savanna.151 set value "We don’t get snow here, just regret."
data modify storage eden:database dialogues.villager.savanna.152 set value "Even the sheep are angry now."
data modify storage eden:database dialogues.villager.savanna.153 set value "I saw Herobrine. Or maybe it was just heatstroke."
data modify storage eden:database dialogues.villager.savanna.154 set value "If you break another door, I swear…"
data modify storage eden:database dialogues.villager.savanna.155 set value "No, I don’t want to follow you to your base."
data modify storage eden:database dialogues.villager.savanna.156 set value "You think emeralds grow on trees? WRONG biome."
data modify storage eden:database dialogues.villager.savanna.157 set value "There’s no magic here, only sand and pain."
data modify storage eden:database dialogues.villager.savanna.158 set value "Even the creepers look bored."
data modify storage eden:database dialogues.villager.savanna.159 set value "Trade? I only deal in sighs now."
data modify storage eden:database dialogues.villager.savanna.160 set value "I had a llama once. She left me."
data modify storage eden:database dialogues.villager.savanna.161 set value "Your cape doesn’t make you a hero here."
data modify storage eden:database dialogues.villager.savanna.162 set value "You ever seen a spider sunbathe? I have. It haunts me."
data modify storage eden:database dialogues.villager.savanna.163 set value "There’s no endgame in the savanna—just heat."
data modify storage eden:database dialogues.villager.savanna.164 set value "My kids learned to sprint before they could craft."
data modify storage eden:database dialogues.villager.savanna.165 set value "If I had redstone, I’d make a sadness machine."
data modify storage eden:database dialogues.villager.savanna.166 set value "The cats here don’t purr. They hiss truths."
data modify storage eden:database dialogues.villager.savanna.167 set value "Yes, the ground’s cracked. So is my spirit."
data modify storage eden:database dialogues.villager.savanna.168 set value "We don’t build walls. We dig holes to hide in."
data modify storage eden:database dialogues.villager.savanna.169 set value "I once saw a raid wipe out an entire village… oh wait, that was this one."
data modify storage eden:database dialogues.villager.savanna.170 set value "Even the golem wants to leave."
data modify storage eden:database dialogues.villager.savanna.171 set value "This isn’t dirt. It’s future disappointment."
data modify storage eden:database dialogues.villager.savanna.172 set value "My scarecrow ran away."
data modify storage eden:database dialogues.villager.savanna.173 set value "Every sunrise just reminds me I’m still here."
data modify storage eden:database dialogues.villager.savanna.174 set value "Go mine somewhere else, trespasser."
data modify storage eden:database dialogues.villager.savanna.175 set value "Acacia is life. Accept it."
data modify storage eden:database dialogues.villager.savanna.176 set value "We don’t sing. We grunt in key."
data modify storage eden:database dialogues.villager.savanna.177 set value "Villagers in plains have it easy. They have grass."
data modify storage eden:database dialogues.villager.savanna.178 set value "Yes, I’m wearing the same robe. No, I don’t care."
data modify storage eden:database dialogues.villager.savanna.179 set value "This biome eats dreams."
data modify storage eden:database dialogues.villager.savanna.180 set value "Lightning struck my house. I called it a blessing."
data modify storage eden:database dialogues.villager.savanna.181 set value "I named my pickaxe 'Hope'. It broke yesterday."
data modify storage eden:database dialogues.villager.savanna.182 set value "Only thing we trade in now is sarcasm."
data modify storage eden:database dialogues.villager.savanna.183 set value "The wind whispers ‘move’… but I can’t."
data modify storage eden:database dialogues.villager.savanna.184 set value "My crops vanished. So did my will."
data modify storage eden:database dialogues.villager.savanna.185 set value "That bell doesn’t mean salvation—it means hide."
data modify storage eden:database dialogues.villager.savanna.186 set value "I once had a farm. Now it’s an enderman hangout."
data modify storage eden:database dialogues.villager.savanna.187 set value "Even the donkeys look tired here."
data modify storage eden:database dialogues.villager.savanna.188 set value "Our well is deep. So is my discontent."
data modify storage eden:database dialogues.villager.savanna.189 set value "Wanna build? Bring your own blocks."
data modify storage eden:database dialogues.villager.savanna.190 set value "Don’t mine at night. Don’t trade at night. Don’t be here at night."
data modify storage eden:database dialogues.villager.savanna.191 set value "You’re lucky you have fast travel. We have slow despair."
data modify storage eden:database dialogues.villager.savanna.192 set value "Every emerald costs me a memory."
data modify storage eden:database dialogues.villager.savanna.193 set value "Once I saw a flower bloom. Once."
data modify storage eden:database dialogues.villager.savanna.194 set value "Go ahead, take my wheat. Everyone else has."
data modify storage eden:database dialogues.villager.savanna.195 set value "This biome was born from lava and sarcasm."
data modify storage eden:database dialogues.villager.savanna.196 set value "The nether’s more welcoming than this place."
data modify storage eden:database dialogues.villager.savanna.197 set value "Why farm when creepers do the harvesting?"
data modify storage eden:database dialogues.villager.savanna.198 set value "I envy the drowned. At least they’re cool."
data modify storage eden:database dialogues.villager.savanna.199 set value "Stay a night, they said. It'll be fun, they said…"
data modify storage eden:database dialogues.villager.savanna.200 set value "Did you just punch my cow?"
data modify storage eden:database dialogues.villager.savanna.201 set value "Rain? Never heard of it."
data modify storage eden:database dialogues.villager.savanna.202 set value "I trade beets for emeralds. It’s not a great life, but it’s mine."
data modify storage eden:database dialogues.villager.savanna.203 set value "If you’re looking for shade, try another village."
data modify storage eden:database dialogues.villager.savanna.204 set value "This robe? Custom… made by accident."
data modify storage eden:database dialogues.villager.savanna.205 set value "Go ahead. Sleep here. We’ll just watch."
data modify storage eden:database dialogues.villager.savanna.206 set value "Once I tried to fish. Caught sand."
data modify storage eden:database dialogues.villager.savanna.207 set value "Ever eaten dried kelp for a week? I have questions."
data modify storage eden:database dialogues.villager.savanna.208 set value "Hey, no tools in the crops, okay?"
data modify storage eden:database dialogues.villager.savanna.209 set value "You ever hear an enderman cry? Chilling."
data modify storage eden:database dialogues.villager.savanna.210 set value "I once made a redstone lamp. Then it exploded."
data modify storage eden:database dialogues.villager.savanna.211 set value "Call this a farm? More like an accident with seeds."
data modify storage eden:database dialogues.villager.savanna.212 set value "We have one rule here: don’t dig straight down. Everyone ignores it."
data modify storage eden:database dialogues.villager.savanna.213 set value "The stonecutter watches us. Don’t ask why."
data modify storage eden:database dialogues.villager.savanna.214 set value "I saw you looking at our pigs. Don’t."
data modify storage eden:database dialogues.villager.savanna.215 set value "Careful, traveler. The llamas spit first, ask later."
data modify storage eden:database dialogues.villager.savanna.216 set value "The cactus told me your fortune. It’s not good."
data modify storage eden:database dialogues.villager.savanna.217 set value "My kid says he wants to be a blaze. I support him."
data modify storage eden:database dialogues.villager.savanna.218 set value "You smell like the Nether."
data modify storage eden:database dialogues.villager.savanna.219 set value "Golems don’t forget. Neither do I."
data modify storage eden:database dialogues.villager.savanna.220 set value "You ever seen a creeper do a cartwheel? Me neither, but I dream about it."
data modify storage eden:database dialogues.villager.savanna.221 set value "I used to believe in heroes. Then you came along."
data modify storage eden:database dialogues.villager.savanna.222 set value "Even my pickaxe is tired."
data modify storage eden:database dialogues.villager.savanna.223 set value "That chest has nothing. Just broken promises."
data modify storage eden:database dialogues.villager.savanna.224 set value "Want to trade? I’ve got disappointment in bulk."
data modify storage eden:database dialogues.villager.savanna.225 set value "If you take one more hay bale, I’m calling the golem."
data modify storage eden:database dialogues.villager.savanna.226 set value "Sometimes I pretend I’m a tree. It’s relaxing."
data modify storage eden:database dialogues.villager.savanna.227 set value "The bees know things. Don’t mess with them."
data modify storage eden:database dialogues.villager.savanna.228 set value "One day, I’ll escape… maybe tomorrow."
data modify storage eden:database dialogues.villager.savanna.229 set value "The acacia trees whisper when you’re not looking."
data modify storage eden:database dialogues.villager.savanna.230 set value "Oh, another traveler. How original."
data modify storage eden:database dialogues.villager.savanna.231 set value "You think you know pain? Try sleeping through phantoms."
data modify storage eden:database dialogues.villager.savanna.232 set value "My dreams are square, and so is my luck."
data modify storage eden:database dialogues.villager.savanna.233 set value "Don’t dig near the hill. It’s cursed. Ask no more."
data modify storage eden:database dialogues.villager.savanna.234 set value "The sheep? Yeah, they’re planning something."
data modify storage eden:database dialogues.villager.savanna.235 set value "My cousin became a cartographer. We never saw him again."
data modify storage eden:database dialogues.villager.savanna.236 set value "You call that a sword? Cute."
data modify storage eden:database dialogues.villager.savanna.237 set value "Every emerald has a story. Mine are mostly sad."
data modify storage eden:database dialogues.villager.savanna.238 set value "Got any string? I owe the cat mafia."
data modify storage eden:database dialogues.villager.savanna.239 set value "This isn’t a village. It’s a training ground for suffering."
data modify storage eden:database dialogues.villager.savanna.240 set value "Why do you smell like gunpowder and regret?"
data modify storage eden:database dialogues.villager.savanna.241 set value "We don’t talk about the ravager incident."
data modify storage eden:database dialogues.villager.savanna.242 set value "No, I don’t want to follow you. Ever."
data modify storage eden:database dialogues.villager.savanna.243 set value "My chickens have names. Don’t ask what they are."
data modify storage eden:database dialogues.villager.savanna.244 set value "A creeper ruined my house and my week."
data modify storage eden:database dialogues.villager.savanna.245 set value "I saw a trader ride a llama into lava. Beautiful."
data modify storage eden:database dialogues.villager.savanna.246 set value "Life’s just sand, sleep, and sorrow."
data modify storage eden:database dialogues.villager.savanna.247 set value "Go ahead. Ring the bell. See what happens."
data modify storage eden:database dialogues.villager.savanna.248 set value "You know what’s fun? Silence. Try it."
data modify storage eden:database dialogues.villager.savanna.249 set value "That potion smells like doom."
data modify storage eden:database dialogues.villager.savanna.250 set value "You ever feel like you’re being watched? You are."
data modify storage eden:database dialogues.villager.savanna.251 set value "Every night I dream of emeralds. And explosions."
data modify storage eden:database dialogues.villager.savanna.252 set value "Build us a wall, traveler. Or at least a fence."
data modify storage eden:database dialogues.villager.savanna.253 set value "That isn’t a hat. It’s a job title."
data modify storage eden:database dialogues.villager.savanna.254 set value "Why are you squatting like that? Is that a thing?"
data modify storage eden:database dialogues.villager.savanna.255 set value "We’re not lost. We’re just… very stationary."
data modify storage eden:database dialogues.villager.savanna.256 set value "I once kissed a frog. Didn’t become a prince, just got warts."
data modify storage eden:database dialogues.villager.savanna.257 set value "You mine it, you place it. That’s the rule."
data modify storage eden:database dialogues.villager.savanna.258 set value "Want to know the secret of the acacia? Too bad."
data modify storage eden:database dialogues.villager.savanna.259 set value "My house has four walls and no joy."
data modify storage eden:database dialogues.villager.savanna.260 set value "I traded my bed for a boat. Still a bad deal."
data modify storage eden:database dialogues.villager.savanna.261 set value "The sky’s been orange for ten years. No one questions it."
data modify storage eden:database dialogues.villager.savanna.262 set value "You want XP? Earn it, scrub."
data modify storage eden:database dialogues.villager.savanna.263 set value "I had a twin. He joined the Illagers. We don’t talk."
data modify storage eden:database dialogues.villager.savanna.264 set value "Put that block back. Now."
data modify storage eden:database dialogues.villager.savanna.265 set value "I can’t read, but I know you’re trouble."
data modify storage eden:database dialogues.villager.savanna.266 set value "No, I’m not lost. This is where I cry every morning."
data modify storage eden:database dialogues.villager.savanna.267 set value "Don’t eat raw chicken. Learned that the hard way."
data modify storage eden:database dialogues.villager.savanna.268 set value "Do I look like a guy with extra beds?"
data modify storage eden:database dialogues.villager.savanna.269 set value "The hay tastes better when you’re not crying."
data modify storage eden:database dialogues.villager.savanna.270 set value "The wind once stole my hat. I never forgave it."
data modify storage eden:database dialogues.villager.savanna.271 set value "Ever hugged a creeper? Me neither, but I’m curious."
data modify storage eden:database dialogues.villager.savanna.272 set value "This robe? Inherited. From someone who vanished."
data modify storage eden:database dialogues.villager.savanna.273 set value "You’re not from around here. You smell too… wet."
data modify storage eden:database dialogues.villager.savanna.274 set value "If you break it, you place it. And you explain it."
data modify storage eden:database dialogues.villager.savanna.275 set value "My legs are cubes. My pain is not."
data modify storage eden:database dialogues.villager.savanna.276 set value "Don’t feed the cows sugarcane. It gets weird."
data modify storage eden:database dialogues.villager.savanna.277 set value "Who needs diamonds when you have bitter sarcasm?"
data modify storage eden:database dialogues.villager.savanna.278 set value "Every day’s a furnace in this place."
data modify storage eden:database dialogues.villager.savanna.279 set value "My hobbies include staring and not dying."
data modify storage eden:database dialogues.villager.savanna.280 set value "No, I don’t want to hear about your ‘builds.’"
data modify storage eden:database dialogues.villager.savanna.281 set value "I saw the End once. Still can’t unsee it."
data modify storage eden:database dialogues.villager.savanna.282 set value "I’ll trade you six sighs for a baked potato."
data modify storage eden:database dialogues.villager.savanna.283 set value "Don’t worry, we accept all forms of pain here."
data modify storage eden:database dialogues.villager.savanna.284 set value "This well is dry. Like my humor."
data modify storage eden:database dialogues.villager.savanna.285 set value "The cats stole my fish. Again."
data modify storage eden:database dialogues.villager.savanna.286 set value "Sometimes I dig for fun. Usually I regret it."
data modify storage eden:database dialogues.villager.savanna.287 set value "You bring nothing but footsteps and dust."
data modify storage eden:database dialogues.villager.savanna.288 set value "Even the water here’s sarcastic."
data modify storage eden:database dialogues.villager.savanna.289 set value "It’s not a village if no one’s screaming."
data modify storage eden:database dialogues.villager.savanna.290 set value "Trade? Sure. I’ll take your will to live."
data modify storage eden:database dialogues.villager.savanna.291 set value "My nose twitches when danger’s near. It’s always twitching."
data modify storage eden:database dialogues.villager.savanna.292 set value "Ever stared at the sun until it blinked first?"
data modify storage eden:database dialogues.villager.savanna.293 set value "You think this is hard? Try spawning here."
data modify storage eden:database dialogues.villager.savanna.294 set value "I once had hope. Then I joined this server."
data modify storage eden:database dialogues.villager.savanna.295 set value "Even my shadow looks tired."
data modify storage eden:database dialogues.villager.savanna.296 set value "You call that a portal? Amateur."
data modify storage eden:database dialogues.villager.savanna.297 set value "Every raid leaves a scar. Most are emotional."
data modify storage eden:database dialogues.villager.savanna.298 set value "That’s not redstone—it’s villager tears."
data modify storage eden:database dialogues.villager.savanna.299 set value "If you’re gonna grief, at least be creative about it."
data modify storage eden:database dialogues.villager.savanna.300 set value "Can you build me a shady hut? The sun’s cooking my crops!"
data modify storage eden:database dialogues.villager.savanna.301 set value "I’d love a tall watchtower—flat land makes it easy to spot trouble."
data modify storage eden:database dialogues.villager.savanna.302 set value "Mind fixing my roof? Acacia planks don’t last forever, y’know."
data modify storage eden:database dialogues.villager.savanna.303 set value "We need a fenced pen—my livestock keep wandering off."
data modify storage eden:database dialogues.villager.savanna.304 set value "Could you build a proper road through the tall grass?"
data modify storage eden:database dialogues.villager.savanna.305 set value "A watering hole would be nice—just for vibes."
data modify storage eden:database dialogues.villager.savanna.306 set value "I want a bigger porch so I can nap in the breeze."
data modify storage eden:database dialogues.villager.savanna.307 set value "Can you raise my house a little? Termites are getting bold."
data modify storage eden:database dialogues.villager.savanna.308 set value "Let’s build a big central fire pit for storytelling nights."
data modify storage eden:database dialogues.villager.savanna.309 set value "Build a little lookout hut on that hill over there."
data modify storage eden:database dialogues.villager.savanna.310 set value "I need a bigger crop field—my wheat’s jealous of the grass."
data modify storage eden:database dialogues.villager.savanna.311 set value "Can you put up a wall? Hyenas—uh, zombies—are getting too close."
data modify storage eden:database dialogues.villager.savanna.312 set value "A windmill would look real good out here."
data modify storage eden:database dialogues.villager.savanna.313 set value "Can you plant a few trees? Savanna’s pretty, but shady it ain’t."
data modify storage eden:database dialogues.villager.savanna.314 set value "I need a shed for tools—and maybe a snack stash."
data modify storage eden:database dialogues.villager.savanna.315 set value "Build me a stall to sell my melons, please!"
data modify storage eden:database dialogues.villager.savanna.316 set value "I want a goat pen. No goats yet, but soon."
data modify storage eden:database dialogues.villager.savanna.317 set value "A raised walkway would help—those grass blocks are uneven."
data modify storage eden:database dialogues.villager.savanna.318 set value "Can we get some lanterns up? Night gets real weird."
data modify storage eden:database dialogues.villager.savanna.319 set value "Add a rain catcher. Yes, I know it never rains here."
data modify storage eden:database dialogues.villager.savanna.320 set value "Can you build a training ring? Iron golem needs a hobby."
data modify storage eden:database dialogues.villager.savanna.321 set value "I’d like a tall flagpole. Gotta mark our territory!"
data modify storage eden:database dialogues.villager.savanna.322 set value "Build a hill shrine. Something cool with leaves and stone."
data modify storage eden:database dialogues.villager.savanna.323 set value "I want a deck where I can watch the sun set."
data modify storage eden:database dialogues.villager.savanna.324 set value "Let’s get a gathering spot in the middle of town."
data modify storage eden:database dialogues.villager.savanna.325 set value "How about a stable? These plains beg for horses."
data modify storage eden:database dialogues.villager.savanna.326 set value "Can you dig out a cool cave spot beneath my house?"
data modify storage eden:database dialogues.villager.savanna.327 set value "I need a smokehouse, even if I just burn grass."
data modify storage eden:database dialogues.villager.savanna.328 set value "A food stand would be nice—roasted beetroot, anyone?"
data modify storage eden:database dialogues.villager.savanna.329 set value "Build me a cozy nook to read maps and stare at clouds."
data modify storage eden:database dialogues.villager.savanna.330 set value "Can you set up a cactus barrier? Just for style."
data modify storage eden:database dialogues.villager.savanna.331 set value "Let’s build an acacia gate that looks really fancy."
data modify storage eden:database dialogues.villager.savanna.332 set value "I want a tower made of every kind of log. Why not?"
data modify storage eden:database dialogues.villager.savanna.333 set value "Build a drum circle! Gotta keep the spirits entertained."
data modify storage eden:database dialogues.villager.savanna.334 set value "We need a hill fort. For looks. (And pillagers.)"
data modify storage eden:database dialogues.villager.savanna.335 set value "Could you lay down some paths between the huts?"
data modify storage eden:database dialogues.villager.savanna.336 set value "A little arena for games would be fun—pig races?"
data modify storage eden:database dialogues.villager.savanna.337 set value "Add a row of flags to make the village feel grand."
data modify storage eden:database dialogues.villager.savanna.338 set value "I want a raised garden—tired of creepers in my carrots."
data modify storage eden:database dialogues.villager.savanna.339 set value "Can we build a shrine to the wandering trader? Just in case."
data modify storage eden:database dialogues.villager.savanna.340 set value "Make me a water tower. It doesn't have to work."
data modify storage eden:database dialogues.villager.savanna.341 set value "Can you make my house look less like a box?"
data modify storage eden:database dialogues.villager.savanna.342 set value "Let’s build a clay oven or something—get that rustic feel."
data modify storage eden:database dialogues.villager.savanna.343 set value "A nice stone arch at the village entrance would be classy."
data modify storage eden:database dialogues.villager.savanna.344 set value "I’d love a bench under that lone tree. You know the one."
data modify storage eden:database dialogues.villager.savanna.345 set value "We need a bell post that doesn’t fall every creeper night."
data modify storage eden:database dialogues.villager.savanna.346 set value "Could you set up a dance floor? Flat land’s perfect for it!"
data modify storage eden:database dialogues.villager.savanna.347 set value "Build a giant acacia tree. Just for show."
data modify storage eden:database dialogues.villager.savanna.348 set value "Make a map board—we keep walking in circles."
data modify storage eden:database dialogues.villager.savanna.349 set value "Surprise me! Just make it orange, dry, and a little dramatic."