data modify storage eden:database dialogues.villager.snow.100 set value "The snow crunches underfoot like whispered secrets."
data modify storage eden:database dialogues.villager.snow.101 set value "Icicles hang like frozen daggers from the eaves."
data modify storage eden:database dialogues.villager.snow.102 set value "Frostbite waits for those who wander too far."
data modify storage eden:database dialogues.villager.snow.103 set value "Keep your fires burning, or the cold will steal your breath."
data modify storage eden:database dialogues.villager.snow.104 set value "The northern winds carry stories of old battles."
data modify storage eden:database dialogues.villager.snow.105 set value "A snowstorm can bury secrets deep beneath the ice."
data modify storage eden:database dialogues.villager.snow.106 set value "Watch for the tracks of wolves in the fresh snow."
data modify storage eden:database dialogues.villager.snow.107 set value "The frozen river is both friend and foe."
data modify storage eden:database dialogues.villager.snow.108 set value "Snowflakes dance like tiny diamonds in the moonlight."
data modify storage eden:database dialogues.villager.snow.109 set value "When the aurora shines, the spirits are near."
data modify storage eden:database dialogues.villager.snow.110 set value "The cold bites deeper when you forget your cloak."
data modify storage eden:database dialogues.villager.snow.111 set value "Frozen branches snap like brittle bones."
data modify storage eden:database dialogues.villager.snow.112 set value "A warm hearth is worth more than gold in these parts."
data modify storage eden:database dialogues.villager.snow.113 set value "The snow muffles footsteps, but not the heartbeats."
data modify storage eden:database dialogues.villager.snow.114 set value "Winter nights are long—tell stories to pass the time."
data modify storage eden:database dialogues.villager.snow.115 set value "The ice caves hold both beauty and danger."
data modify storage eden:database dialogues.villager.snow.116 set value "Snow drifts hide holes that swallow the unwary."
data modify storage eden:database dialogues.villager.snow.117 set value "The frozen tundra teaches patience and resilience."
data modify storage eden:database dialogues.villager.snow.118 set value "Icicles drip like slow tears from the roof."
data modify storage eden:database dialogues.villager.snow.119 set value "Keep your boots dry, or the cold will claim your toes."
data modify storage eden:database dialogues.villager.snow.120 set value "Snow owls watch silently from frozen branches."
data modify storage eden:database dialogues.villager.snow.121 set value "The snow hides the paths only the old know."
data modify storage eden:database dialogues.villager.snow.122 set value "A frozen lake can be a mirror to your soul."
data modify storage eden:database dialogues.villager.snow.123 set value "The cold wind carries the scent of pine and frost."
data modify storage eden:database dialogues.villager.snow.124 set value "You can hear the ice crack before the fall."
data modify storage eden:database dialogues.villager.snow.125 set value "The snowstorm’s howl is a warning and a lullaby."
data modify storage eden:database dialogues.villager.snow.126 set value "A scarf wrapped tight saves more than warmth."
data modify storage eden:database dialogues.villager.snow.127 set value "Frozen footprints tell tales of travelers long gone."
data modify storage eden:database dialogues.villager.snow.128 set value "The cold reveals the strength hidden beneath skin."
data modify storage eden:database dialogues.villager.snow.129 set value "Beware the ice that glimmers too perfectly."
data modify storage eden:database dialogues.villager.snow.130 set value "The snow reflects the stars like a thousand eyes."
data modify storage eden:database dialogues.villager.snow.131 set value "Snowflakes never fall the same way twice."
data modify storage eden:database dialogues.villager.snow.132 set value "The frost etches patterns only nature can design."
data modify storage eden:database dialogues.villager.snow.133 set value "A warm cup of stew can thaw the coldest heart."
data modify storage eden:database dialogues.villager.snow.134 set value "The northern lights paint the sky with ghostly colors."
data modify storage eden:database dialogues.villager.snow.135 set value "Cold nights are for dreaming by the fire."
data modify storage eden:database dialogues.villager.snow.136 set value "The snow holds the footprints of many forgotten journeys."
data modify storage eden:database dialogues.villager.snow.137 set value "Ice cracks like whispered warnings beneath your feet."
data modify storage eden:database dialogues.villager.snow.138 set value "Frozen trees stand like silent sentinels."
data modify storage eden:database dialogues.villager.snow.139 set value "A fur cloak is as precious as any treasure."
data modify storage eden:database dialogues.villager.snow.140 set value "Snowstorms can hide the path to home."
data modify storage eden:database dialogues.villager.snow.141 set value "The cold tests both body and spirit."
data modify storage eden:database dialogues.villager.snow.142 set value "When the ice breaks, the river sings a new song."
data modify storage eden:database dialogues.villager.snow.143 set value "Keep close to the fire, and closer to friends."
data modify storage eden:database dialogues.villager.snow.144 set value "The snow-covered plains seem endless and silent."
data modify storage eden:database dialogues.villager.snow.145 set value "Frosty breath shows the path of your journey."
data modify storage eden:database dialogues.villager.snow.146 set value "The frozen wind can carry distant voices."
data modify storage eden:database dialogues.villager.snow.147 set value "Snowflakes settle softly on the old wooden roofs."
data modify storage eden:database dialogues.villager.snow.148 set value "The winter moon glows with a cold, pale light."
data modify storage eden:database dialogues.villager.snow.149 set value "Footprints in the snow are stories waiting to be told."
data modify storage eden:database dialogues.villager.snow.150 set value "The chill in the air sharpens the senses."
data modify storage eden:database dialogues.villager.snow.151 set value "Ice crystals sparkle like stars on the ground."
data modify storage eden:database dialogues.villager.snow.152 set value "The cold winds whisper secrets from distant lands."
data modify storage eden:database dialogues.villager.snow.153 set value "The frozen forest hides many mysteries."
data modify storage eden:database dialogues.villager.snow.154 set value "The warmth of friendship outshines the coldest night."
data modify storage eden:database dialogues.villager.snow.155 set value "Snow blankets the earth like a soft, cold quilt."
data modify storage eden:database dialogues.villager.snow.156 set value "The icy river flows beneath the winter’s grip."
data modify storage eden:database dialogues.villager.snow.157 set value "A frozen branch can break under the slightest touch."
data modify storage eden:database dialogues.villager.snow.158 set value "The cold night sky is filled with shimmering stars."
data modify storage eden:database dialogues.villager.snow.159 set value "Snow hides both beauty and danger in its depths."
data modify storage eden:database dialogues.villager.snow.160 set value "The crackling fire is a friend against the chill."
data modify storage eden:database dialogues.villager.snow.161 set value "Frost covers the fields like a sparkling blanket."
data modify storage eden:database dialogues.villager.snow.162 set value "The howling wind carries the stories of the past."
data modify storage eden:database dialogues.villager.snow.163 set value "Keep your cloak tight when the cold bites hard."
data modify storage eden:database dialogues.villager.snow.164 set value "The frozen ground can be treacherous beneath your feet."
data modify storage eden:database dialogues.villager.snow.165 set value "Snowflakes settle silently on the old village rooftops."
data modify storage eden:database dialogues.villager.snow.166 set value "The cold air sharpens the scent of pine and earth."
data modify storage eden:database dialogues.villager.snow.167 set value "The stars shine brighter against the winter sky."
data modify storage eden:database dialogues.villager.snow.168 set value "Ice sparkles like glass under the moon’s pale light."
data modify storage eden:database dialogues.villager.snow.169 set value "The snow hides footprints of creatures both big and small."
data modify storage eden:database dialogues.villager.snow.170 set value "Winter’s silence is broken only by the crackling fire."
data modify storage eden:database dialogues.villager.snow.171 set value "The cold tests your resolve with every icy breath."
data modify storage eden:database dialogues.villager.snow.172 set value "The frozen river glistens like a ribbon of glass."
data modify storage eden:database dialogues.villager.snow.173 set value "Snowdrifts can hide the old paths we once knew."
data modify storage eden:database dialogues.villager.snow.174 set value "A warm hearth brings comfort to even the coldest night."
data modify storage eden:database dialogues.villager.snow.175 set value "The snow crunches softly beneath heavy boots."
data modify storage eden:database dialogues.villager.snow.176 set value "The winter wind carries the scent of distant fires."
data modify storage eden:database dialogues.villager.snow.177 set value "Icicles hang like frozen swords from every roof."
data modify storage eden:database dialogues.villager.snow.178 set value "The frozen trees stand silent against the biting cold."
data modify storage eden:database dialogues.villager.snow.179 set value "The snow sparkles like a thousand tiny stars."
data modify storage eden:database dialogues.villager.snow.180 set value "A cold night is best spent by the roaring fire."
data modify storage eden:database dialogues.villager.snow.181 set value "The frost etches delicate patterns on the windows."
data modify storage eden:database dialogues.villager.snow.182 set value "The snow blankets the earth in quiet beauty."
data modify storage eden:database dialogues.villager.snow.183 set value "The cold wind whispers ancient songs through the trees."
data modify storage eden:database dialogues.villager.snow.184 set value "Footsteps echo softly in the snow-covered village."
data modify storage eden:database dialogues.villager.snow.185 set value "The frozen ground crunches beneath every careful step."
data modify storage eden:database dialogues.villager.snow.186 set value "Snowflakes drift gently from the pale winter sky."
data modify storage eden:database dialogues.villager.snow.187 set value "The winter moon glows like a pale lantern in the night."
data modify storage eden:database dialogues.villager.snow.188 set value "Icicles catch the sunlight and shine like crystals."
data modify storage eden:database dialogues.villager.snow.189 set value "The cold air is filled with the scent of pine and smoke."
data modify storage eden:database dialogues.villager.snow.190 set value "A snowstorm can blanket the world in quiet white."
data modify storage eden:database dialogues.villager.snow.191 set value "Frozen branches creak softly in the winter breeze."
data modify storage eden:database dialogues.villager.snow.192 set value "The cold is a test of strength and spirit."
data modify storage eden:database dialogues.villager.snow.193 set value "The snow hides both danger and wonder in its folds."
data modify storage eden:database dialogues.villager.snow.194 set value "Keep your firewood close and your heart warm."
data modify storage eden:database dialogues.villager.snow.195 set value "The frozen river sings a quiet song beneath the ice."
data modify storage eden:database dialogues.villager.snow.196 set value "Snowflakes sparkle like stars fallen from the sky."
data modify storage eden:database dialogues.villager.snow.197 set value "The cold night sky is alive with shimmering stars."
data modify storage eden:database dialogues.villager.snow.198 set value "The frost bites sharp, but the warmth of friendship is sharper."
data modify storage eden:database dialogues.villager.snow.199 set value "A winter's tale is best told beside a crackling fire."
data modify storage eden:database dialogues.villager.snow.200 set value "The winter wind howls like a wild beast across the plains."
data modify storage eden:database dialogues.villager.snow.201 set value "Keep your lantern lit; the cold shadows can be treacherous."
data modify storage eden:database dialogues.villager.snow.202 set value "Frozen lakes hide secrets beneath their glassy surface."
data modify storage eden:database dialogues.villager.snow.203 set value "Snowdrifts pile high, hiding the old village paths."
data modify storage eden:database dialogues.villager.snow.204 set value "A woolen cloak is your best friend in the cold night."
data modify storage eden:database dialogues.villager.snow.205 set value "Frost paints the world in shimmering white every dawn."
data modify storage eden:database dialogues.villager.snow.206 set value "Beware the icy winds that can sap your strength quickly."
data modify storage eden:database dialogues.villager.snow.207 set value "The frozen woods are alive with the whisper of hidden creatures."
data modify storage eden:database dialogues.villager.snow.208 set value "A warm fire can turn even the coldest night bearable."
data modify storage eden:database dialogues.villager.snow.209 set value "The crunch of snow beneath your boots is the only sound for miles."
data modify storage eden:database dialogues.villager.snow.210 set value "The aurora dances, lighting the sky with ghostly colors."
data modify storage eden:database dialogues.villager.snow.211 set value "Watch for frozen ponds; one wrong step and you might fall through."
data modify storage eden:database dialogues.villager.snow.212 set value "Icicles grow sharp and long, like nature’s own daggers."
data modify storage eden:database dialogues.villager.snow.213 set value "The snow covers the earth like a thick, cold blanket."
data modify storage eden:database dialogues.villager.snow.214 set value "The wind whispers old stories carried from distant mountains."
data modify storage eden:database dialogues.villager.snow.215 set value "Snowflakes fall quietly, each one unique and fragile."
data modify storage eden:database dialogues.villager.snow.216 set value "Frostbite comes slowly but leaves a painful mark."
data modify storage eden:database dialogues.villager.snow.217 set value "The frozen forest holds many secrets beneath its white coat."
data modify storage eden:database dialogues.villager.snow.218 set value "A hearty stew warms the soul in these frozen lands."
data modify storage eden:database dialogues.villager.snow.219 set value "The stars shine brighter against the cold, clear sky."
data modify storage eden:database dialogues.villager.snow.220 set value "Snow crunches softly underfoot as you tread carefully."
data modify storage eden:database dialogues.villager.snow.221 set value "Cold winds carry the scent of pine and distant fires."
data modify storage eden:database dialogues.villager.snow.222 set value "The frozen river flows silently beneath its icy crust."
data modify storage eden:database dialogues.villager.snow.223 set value "The warmth of a friend is the best defense against cold."
data modify storage eden:database dialogues.villager.snow.224 set value "Snow-covered hills roll endlessly under the pale sun."
data modify storage eden:database dialogues.villager.snow.225 set value "Frozen branches creak as the wind shakes them fiercely."
data modify storage eden:database dialogues.villager.snow.226 set value "The cold sharpens the senses like a finely honed blade."
data modify storage eden:database dialogues.villager.snow.227 set value "A scarf wrapped tight can keep the chill at bay."
data modify storage eden:database dialogues.villager.snow.228 set value "The icy moon casts long shadows over the snowfields."
data modify storage eden:database dialogues.villager.snow.229 set value "Footprints in fresh snow tell tales of recent travelers."
data modify storage eden:database dialogues.villager.snow.230 set value "The snow sparkles like tiny stars under the moonlight."
data modify storage eden:database dialogues.villager.snow.231 set value "Cold nights are best spent by the roaring fire."
data modify storage eden:database dialogues.villager.snow.232 set value "Frozen ground can be slippery and dangerous if you’re not careful."
data modify storage eden:database dialogues.villager.snow.233 set value "Icicles drip slowly, freezing and thawing with each day."
data modify storage eden:database dialogues.villager.snow.234 set value "The chill in the air reminds us to treasure warmth."
data modify storage eden:database dialogues.villager.snow.235 set value "Snow hides the signs of danger beneath its white veil."
data modify storage eden:database dialogues.villager.snow.236 set value "The cold tests your courage as much as your strength."
data modify storage eden:database dialogues.villager.snow.237 set value "The frozen trees stand tall like silent guardians."
data modify storage eden:database dialogues.villager.snow.238 set value "The night sky gleams with frost-bitten stars."
data modify storage eden:database dialogues.villager.snow.239 set value "The snow drifts shift with every gust of wind."
data modify storage eden:database dialogues.villager.snow.240 set value "A warm cloak can be a lifesaver in this frozen land."
data modify storage eden:database dialogues.villager.snow.241 set value "The frozen tundra stretches endlessly beneath the cold sky."
data modify storage eden:database dialogues.villager.snow.242 set value "Snowflakes melt on your tongue like tiny crystals."
data modify storage eden:database dialogues.villager.snow.243 set value "The cold wind carries the scent of frost-covered pine."
data modify storage eden:database dialogues.villager.snow.244 set value "A fire’s glow is the brightest light in these dark nights."
data modify storage eden:database dialogues.villager.snow.245 set value "Frozen footprints mark the passage of silent hunters."
data modify storage eden:database dialogues.villager.snow.246 set value "The icy air bites through even the thickest furs."
data modify storage eden:database dialogues.villager.snow.247 set value "The snow muffles the sounds of the wilderness."
data modify storage eden:database dialogues.villager.snow.248 set value "Keep your boots dry, or you’ll feel the cold in your bones."
data modify storage eden:database dialogues.villager.snow.249 set value "The frozen river is both a path and a trap."
data modify storage eden:database dialogues.villager.snow.250 set value "The cold stars shine down on the silent village."
data modify storage eden:database dialogues.villager.snow.251 set value "Snowflakes drift down like whispered blessings from the sky."
data modify storage eden:database dialogues.villager.snow.252 set value "The frost etches delicate patterns on every windowpane."
data modify storage eden:database dialogues.villager.snow.253 set value "The cold night air carries the howl of distant wolves."
data modify storage eden:database dialogues.villager.snow.254 set value "Frozen trees stand like frozen sentinels in the night."
data modify storage eden:database dialogues.villager.snow.255 set value "The snow crunches beneath your feet like a steady drum."
data modify storage eden:database dialogues.villager.snow.256 set value "A woolen scarf can be the difference between warmth and frostbite."
data modify storage eden:database dialogues.villager.snow.257 set value "The winter sun is pale but strong in the clear sky."
data modify storage eden:database dialogues.villager.snow.258 set value "The icy ground can hide dangerous cracks and holes."
data modify storage eden:database dialogues.villager.snow.259 set value "Snow blankets the earth, silencing all but the strongest winds."
data modify storage eden:database dialogues.villager.snow.260 set value "The cold night stars seem closer than ever."
data modify storage eden:database dialogues.villager.snow.261 set value "Keep your firewood close, the cold waits for no one."
data modify storage eden:database dialogues.villager.snow.262 set value "The frozen forest hides creatures both curious and fierce."
data modify storage eden:database dialogues.villager.snow.263 set value "The snow is soft but can hide sharp rocks beneath."
data modify storage eden:database dialogues.villager.snow.264 set value "The winter wind carries the scent of faraway mountains."
data modify storage eden:database dialogues.villager.snow.265 set value "The frost glistens on every branch like tiny jewels."
data modify storage eden:database dialogues.villager.snow.266 set value "A warm heart is the best armor against the cold."
data modify storage eden:database dialogues.villager.snow.267 set value "The snow crunches like whispered footsteps in the night."
data modify storage eden:database dialogues.villager.snow.268 set value "The icy moonlight turns the world into a silver dream."
data modify storage eden:database dialogues.villager.snow.269 set value "Frozen rivers flow silently beneath their glassy skins."
data modify storage eden:database dialogues.villager.snow.270 set value "Snowflakes dance lazily through the crisp winter air."
data modify storage eden:database dialogues.villager.snow.271 set value "The cold tests your strength and your will to carry on."
data modify storage eden:database dialogues.villager.snow.272 set value "Icicles hang like frozen daggers from every rooftop."
data modify storage eden:database dialogues.villager.snow.273 set value "The frozen ground crunches underfoot like brittle bones."
data modify storage eden:database dialogues.villager.snow.274 set value "A fire’s warmth is the light that guides through the cold."
data modify storage eden:database dialogues.villager.snow.275 set value "The snow covers the world in silent, shimmering white."
data modify storage eden:database dialogues.villager.snow.276 set value "The cold wind howls like a lonely wolf in the night."
data modify storage eden:database dialogues.villager.snow.277 set value "Footprints in the snow tell stories of travelers long gone."
data modify storage eden:database dialogues.villager.snow.278 set value "Frozen trees stand tall, their branches heavy with ice."
data modify storage eden:database dialogues.villager.snow.279 set value "The cold night sky is full of sparkling frost-bitten stars."
data modify storage eden:database dialogues.villager.snow.280 set value "Snowflakes fall gently, each one a unique frozen gem."
data modify storage eden:database dialogues.villager.snow.281 set value "Keep your cloak tight and your fire burning bright."
data modify storage eden:database dialogues.villager.snow.282 set value "The frozen tundra stretches out, endless and unforgiving."
data modify storage eden:database dialogues.villager.snow.283 set value "Snow hides the dangers that lie beneath its cold white veil."
data modify storage eden:database dialogues.villager.snow.284 set value "The cold sharpens the senses and toughens the spirit."
data modify storage eden:database dialogues.villager.snow.285 set value "A warm meal is a rare treasure in the frozen north."
data modify storage eden:database dialogues.villager.snow.286 set value "The frozen river gleams like a ribbon of glass under the moon."
data modify storage eden:database dialogues.villager.snow.287 set value "Snow crunches softly, marking your careful journey."
data modify storage eden:database dialogues.villager.snow.288 set value "The cold air carries the scent of pine, ice, and distant fires."
data modify storage eden:database dialogues.villager.snow.289 set value "Icicles drip slowly, telling the story of winter’s grip."
data modify storage eden:database dialogues.villager.snow.290 set value "The winter moon glows pale and cold above the silent village."
data modify storage eden:database dialogues.villager.snow.291 set value "Snowflakes sparkle like tiny stars scattered across the ground."
data modify storage eden:database dialogues.villager.snow.292 set value "The cold night sky shines with frost-bitten stars above."
data modify storage eden:database dialogues.villager.snow.293 set value "Frozen footprints mark the path of silent hunters in the night."
data modify storage eden:database dialogues.villager.snow.294 set value "A woolen scarf can be the difference between warmth and frostbite."
data modify storage eden:database dialogues.villager.snow.295 set value "The winter wind carries the whisper of ancient mountain tales."
data modify storage eden:database dialogues.villager.snow.296 set value "The snow muffles all sounds but the crackling of the fire."
data modify storage eden:database dialogues.villager.snow.297 set value "Cold nights demand strong hearts and warm hands."
data modify storage eden:database dialogues.villager.snow.298 set value "The frozen ground hides dangers for the unwary traveler."
data modify storage eden:database dialogues.villager.snow.299 set value "A winter’s tale is best shared beside a blazing hearth."
data modify storage eden:database dialogues.villager.snow.300 set value "Mind building me a house with a real roof? Snow keeps sneaking in."
data modify storage eden:database dialogues.villager.snow.301 set value "Can you dig out the path again? It’s buried again."
data modify storage eden:database dialogues.villager.snow.302 set value "I’d love a big stone fireplace—my toes are frozen."
data modify storage eden:database dialogues.villager.snow.303 set value "Build me a shed for firewood—I keep losing it in the snow."
data modify storage eden:database dialogues.villager.snow.304 set value "We need a tall torch post—can’t see anything in a whiteout."
data modify storage eden:database dialogues.villager.snow.305 set value "Think you could make a hot spring hut? Just for warming up."
data modify storage eden:database dialogues.villager.snow.306 set value "Can you build a proper stable? The horses are shivering!"
data modify storage eden:database dialogues.villager.snow.307 set value "A snowball arena would be amazing. Just sayin’."
data modify storage eden:database dialogues.villager.snow.308 set value "Can you raise the fence? Strays keep getting in at night."
data modify storage eden:database dialogues.villager.snow.309 set value "I’d love a bigger chimney—mine’s more smoke than heat."
data modify storage eden:database dialogues.villager.snow.310 set value "Make a walkway with slabs—ice keeps tripping me up."
data modify storage eden:database dialogues.villager.snow.311 set value "We need a bell tower tall enough to hear through a blizzard."
data modify storage eden:database dialogues.villager.snow.312 set value "Could you build a cozy inn? Somewhere to defrost."
data modify storage eden:database dialogues.villager.snow.313 set value "Build me a cabin with double insulation. Whatever that means."
data modify storage eden:database dialogues.villager.snow.314 set value "A lantern line down the main road would help a ton."
data modify storage eden:database dialogues.villager.snow.315 set value "Build a lookout so we can spot strays before they bite."
data modify storage eden:database dialogues.villager.snow.316 set value "I want a snow golem hut. They deserve it."
data modify storage eden:database dialogues.villager.snow.317 set value "Can you make a warm underground room? Just in case."
data modify storage eden:database dialogues.villager.snow.318 set value "We need a proper bakery—warm bread fixes cold days."
data modify storage eden:database dialogues.villager.snow.319 set value "Build a little sauna. No mobs allowed."
data modify storage eden:database dialogues.villager.snow.320 set value "Some benches by the firepit would be great."
data modify storage eden:database dialogues.villager.snow.321 set value "Could you add a roof to the well? Keeps freezing over."
data modify storage eden:database dialogues.villager.snow.322 set value "A cozy market with campfires would be awesome."
data modify storage eden:database dialogues.villager.snow.323 set value "Make me a big window—I want to watch the snowfall in peace."
data modify storage eden:database dialogues.villager.snow.324 set value "Build a totem post—helps me find the village in the snow."
data modify storage eden:database dialogues.villager.snow.325 set value "Let’s make a sled track! For, uh, science."
data modify storage eden:database dialogues.villager.snow.326 set value "Can you dig a snow shelter? Just for emergencies."
data modify storage eden:database dialogues.villager.snow.327 set value "Build a cozy reading hut—nothing beats books and cocoa."
data modify storage eden:database dialogues.villager.snow.328 set value "I need a better floor. This packed ice is rough on the feet."
data modify storage eden:database dialogues.villager.snow.329 set value "Add some spruce trees around—makes the place feel alive."
data modify storage eden:database dialogues.villager.snow.330 set value "A stone wall might help keep out the wolves."
data modify storage eden:database dialogues.villager.snow.331 set value "I want a big stew pot over a fire. Just for the look of it."
data modify storage eden:database dialogues.villager.snow.332 set value "Could you make a snow sculpture garden? Something majestic."
data modify storage eden:database dialogues.villager.snow.333 set value "Build a little reindeer stable—even if we don’t have reindeer."
data modify storage eden:database dialogues.villager.snow.334 set value "Let’s get a big central fire—somewhere everyone can warm up."
data modify storage eden:database dialogues.villager.snow.335 set value "I need a bunkhouse for when visitors drop by."
data modify storage eden:database dialogues.villager.snow.336 set value "Build a chimney that actually works, please."
data modify storage eden:database dialogues.villager.snow.337 set value "Add some ice lanterns! They look awesome at night."
data modify storage eden:database dialogues.villager.snow.338 set value "Make a storage cave—it’s cold enough for natural refrigeration!"
data modify storage eden:database dialogues.villager.snow.339 set value "Let’s build a frost shrine—gotta respect the snow spirits."
data modify storage eden:database dialogues.villager.snow.340 set value "Could you build a sled ramp off the hill? For fun... and speed."
data modify storage eden:database dialogues.villager.snow.341 set value "Make me a lodge with wool carpets. No more freezing feet."
data modify storage eden:database dialogues.villager.snow.342 set value "Build an ice fishing hut on the lake!"
data modify storage eden:database dialogues.villager.snow.343 set value "A small greenhouse would really help our food situation."
data modify storage eden:database dialogues.villager.snow.344 set value "Add some snow fences—they’re great windbreaks."
data modify storage eden:database dialogues.villager.snow.345 set value "I want a pinecone pile. Okay, or just a spruce log stack."
data modify storage eden:database dialogues.villager.snow.346 set value "Let’s put up icicle decorations! Snow holidays are coming."
data modify storage eden:database dialogues.villager.snow.347 set value "Can you make a tunnel between houses? Tired of frostbite."
data modify storage eden:database dialogues.villager.snow.348 set value "A bell made of ice would be epic. Loud, too."
data modify storage eden:database dialogues.villager.snow.349 set value "Surprise me—but make it cozy, warm, and snow-proof!"