data modify storage eden:database names.villager.deep_blue.first.1 set value Aetherius
data modify storage eden:database names.villager.deep_blue.first.2 set value Caelestius
data modify storage eden:database names.villager.deep_blue.first.3 set value Cerebrus
data modify storage eden:database names.villager.deep_blue.first.4 set value Cygnus
data modify storage eden:database names.villager.deep_blue.first.5 set value Draco
data modify storage eden:database names.villager.deep_blue.first.6 set value Equus
data modify storage eden:database names.villager.deep_blue.first.7 set value Feles
data modify storage eden:database names.villager.deep_blue.first.8 set value Gladius
data modify storage eden:database names.villager.deep_blue.first.9 set value Hydra
data modify storage eden:database names.villager.deep_blue.first.10 set value Ignis
data modify storage eden:database names.villager.deep_blue.first.11 set value Leo
data modify storage eden:database names.villager.deep_blue.first.12 set value Luna
data modify storage eden:database names.villager.deep_blue.first.13 set value Marinus
data modify storage eden:database names.villager.deep_blue.first.14 set value Nix
data modify storage eden:database names.villager.deep_blue.first.15 set value Oceanus
data modify storage eden:database names.villager.deep_blue.first.16 set value Phoenix
data modify storage eden:database names.villager.deep_blue.first.17 set value Python
data modify storage eden:database names.villager.deep_blue.first.18 set value Quasar
data modify storage eden:database names.villager.deep_blue.first.19 set value Raven
data modify storage eden:database names.villager.deep_blue.first.20 set value Sol
data modify storage eden:database names.villager.deep_blue.first.21 set value Taurus
data modify storage eden:database names.villager.deep_blue.first.22 set value Umbra
data modify storage eden:database names.villager.deep_blue.first.23 set value Ventus
data modify storage eden:database names.villager.deep_blue.first.24 set value Vulpes
data modify storage eden:database names.villager.deep_blue.first.25 set value Astra
data modify storage eden:database names.villager.deep_blue.first.26 set value Boreas
data modify storage eden:database names.villager.deep_blue.first.27 set value Caligo
data modify storage eden:database names.villager.deep_blue.first.28 set value Delphinus
data modify storage eden:database names.villager.deep_blue.first.29 set value Equinox
data modify storage eden:database names.villager.deep_blue.first.30 set value Frigus
data modify storage eden:database names.villager.deep_blue.first.31 set value Gemini
data modify storage eden:database names.villager.deep_blue.first.32 set value Helix
data modify storage eden:database names.villager.deep_blue.first.33 set value Ignis
data modify storage eden:database names.villager.deep_blue.first.34 set value Lacerta
data modify storage eden:database names.villager.deep_blue.first.35 set value Lyra
data modify storage eden:database names.villager.deep_blue.first.36 set value Nimbus
data modify storage eden:database names.villager.deep_blue.first.37 set value Orion
data modify storage eden:database names.villager.deep_blue.first.38 set value Pavo
data modify storage eden:database names.villager.deep_blue.first.39 set value Quetzalcoatlus
data modify storage eden:database names.villager.deep_blue.first.40 set value Remus
data modify storage eden:database names.villager.deep_blue.first.41 set value Sirius
data modify storage eden:database names.villager.deep_blue.first.42 set value Taurus
data modify storage eden:database names.villager.deep_blue.first.43 set value Ursa
data modify storage eden:database names.villager.deep_blue.first.44 set value Volcano
data modify storage eden:database names.villager.deep_blue.first.45 set value Xiphias
data modify storage eden:database names.villager.deep_blue.first.46 set value Yggdrasil
data modify storage eden:database names.villager.deep_blue.first.47 set value Zephyrus
data modify storage eden:database names.villager.deep_blue.first.48 set value Aquila
data modify storage eden:database names.villager.deep_blue.first.49 set value Corvus
data modify storage eden:database names.villager.deep_blue.first.50 set value Solaris
data modify storage eden:database names.villager.deep_blue.first.51 set value Maris
data modify storage eden:database names.villager.deep_blue.first.52 set value Aquamarinus
data modify storage eden:database names.villager.deep_blue.first.53 set value Aether
data modify storage eden:database names.villager.deep_blue.first.54 set value Lucius
data modify storage eden:database names.villager.deep_blue.first.55 set value Lux
data modify storage eden:database names.villager.deep_blue.first.56 set value Aelius
data modify storage eden:database names.villager.deep_blue.first.57 set value Umbra