# Copper particle
execute at @s if score @s copper_trim matches 1 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_head anchored feet rotated ~ 0 positioned ^ ^ ^-.13 run particle minecraft:ash ~ ~1.6 ~ .2 .03 .2 0.01 1 normal
execute at @s if score @s copper_trim matches 1 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_chest anchored feet rotated ~ 0 positioned ^ ^ ^-.13 run particle minecraft:ash ~ ~1.2 ~ .2 .03 .2 0.01 1 normal
execute at @s if score @s copper_trim matches 1 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_legs anchored feet rotated ~ 0 positioned ^ ^ ^-.13 run particle minecraft:ash ~ ~.7 ~ .2 .03 .2 0.01 1 normal
execute at @s if score @s copper_trim matches 1 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_feet anchored feet rotated ~ 0 positioned ^ ^ ^-.13 run particle minecraft:ash ~ ~.3 ~ .2 .03 .2 0.01 1 normal

execute at @s if score @s copper_trim matches 2 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_head anchored feet rotated ~ 0 positioned ^ ^ ^-.1 run particle minecraft:ash ~ ~1.3 ~ .17 .03 .17 0.01 1 normal
execute at @s if score @s copper_trim matches 2 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_chest anchored feet rotated ~ 0 positioned ^ ^ ^-.1 run particle minecraft:ash ~ ~1 ~ .17 .03 .17 0.01 1 normal
execute at @s if score @s copper_trim matches 2 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_legs anchored feet rotated ~ 0 positioned ^ ^ ^-.1 run particle minecraft:ash ~ ~.6 ~ .17 .03 .17 0.01 1 normal
execute at @s if score @s copper_trim matches 2 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_feet anchored feet rotated ~ 0 positioned ^ ^ ^-.1 run particle minecraft:ash ~ ~.3 ~ .17 .03 .17 0.01 1 normal

execute at @s if score @s copper_trim matches 3 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_head anchored feet rotated ~ 0 positioned ^ ^ ^-.05 run particle minecraft:ash ~ ~1 ~ .12 .03 .12 0.01 1 normal
execute at @s if score @s copper_trim matches 3 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_chest anchored feet rotated ~ 0 positioned ^ ^ ^-.05 run particle minecraft:ash ~ ~.8 ~ .12 .03 .12 0.01 1 normal
execute at @s if score @s copper_trim matches 3 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_legs anchored feet rotated ~ 0 positioned ^ ^ ^-.05 run particle minecraft:ash ~ ~.5 ~ .12 .03 .12 0.01 1 normal
execute at @s if score @s copper_trim matches 3 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_feet anchored feet rotated ~ 0 positioned ^ ^ ^-.05 run particle minecraft:ash ~ ~.2 ~ .12 .03 .12 0.01 1 normal

execute at @s if score @s copper_trim matches 4 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_head anchored feet rotated ~ 0 positioned ^ ^ ^-.03 run particle minecraft:ash ~ ~.7 ~ .07 .03 .07 0.01 1 normal
execute at @s if score @s copper_trim matches 4 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_chest anchored feet rotated ~ 0 positioned ^ ^ ^-.03 run particle minecraft:ash ~ ~.5 ~ .07 .03 .07 0.01 1 normal
execute at @s if score @s copper_trim matches 4 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_legs anchored feet rotated ~ 0 positioned ^ ^ ^-.03 run particle minecraft:ash ~ ~.2 ~ .07 .03 .07 0.01 1 normal
execute at @s if score @s copper_trim matches 4 if predicate trim_effects:rarity/particle if predicate trim_effects:trim/copper_trim/copper_feet anchored feet rotated ~ 0 positioned ^ ^ ^-.03 run particle minecraft:ash ~ ~.1 ~ .07 .03 .07 0.01 1 normal
