$dialog show @s \
{\
  "type":"minecraft:confirmation",\
  "body":[\
    {\
      "type":"minecraft:item",\
      "item":{\
      "id": "minecraft:smithing_table",\
        "components":{\
          "minecraft:tooltip_display":{\
            "hide_tooltip":true\
          }\
        }\
      },\
      "description":{\
        "translate":"menu.mob_manager.misc.description",\
        "fallback":"Configure Miscellaneous Settings:"\
      }\
    }\
  ],\
  "inputs":[\
    {\
      "type":"minecraft:number_range",\
      "key":"mobheads",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.mob_equipment.mobheads",\
        "fallback":"Chance For Mobs Wearing Mobheads"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(mobheads_initial)\
    },\
    {\
      "type":"minecraft:number_range",\
      "key":"playerheads",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.mob_equipment.playerheads",\
        "fallback":"Chance For Mobs Wearing Playerheads"\
      },\
      "label_format":"options.percent_value",\
      "start":0,\
      "end":100,\
      "step":1,\
      "initial":$(playerheads_initial)\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"leathercolor",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.leathercolor",\
        "fallback":"Random Leather Armor Color"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(leathercolor_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"trim",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.trim",\
        "fallback":"Random Armor Trims"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(trim_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"bannershield",\
      "width": 256,\
      "label":{\
        "translate":"option.mob_manager.bannershield",\
        "fallback":"Random Shield Banners"\
      },\
      "options":[\
        {\
          "id":"enabled",\
          "display":{\
            "translate":"option.mob_manager.enabled",\
            "fallback":"Enabled",\
            "color":"green"\
          }\
        },\
        {\
          "id":"disabled",\
          "display":{\
            "translate":"option.mob_manager.disabled",\
            "fallback":"Disabled",\
            "color":"red"\
          },\
          "initial":$(bannershield_initial)\
        }\
      ]\
    },\
    {\
      "type":"minecraft:single_option",\
      "key":"vex_equip",\
      "width": 256,\
      "label":{\
        "translate":"menu.mob_manager.option.vex_equip",\
        "fallback":"Vex Weapon"\
      },\
      "options":[\
        {\
          "id":"air",\
          "display":{\
            "translate":"option.mob_manager.none",\
            "fallback":"None",\
            "color":"white"\
          }\
        },\
        {\
          "id":"stick",\
          "display":{\
            "translate":"item.minecraft.stick",\
            "color":"white"\
          },\
          "initial":$(vex_equip_stick_initial)\
        },\
        {\
          "id":"wooden_sword",\
          "display":{\
            "translate":"item.minecraft.wooden_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_wooden_sword_initial)\
        },\
        {\
          "id":"stone_sword",\
          "display":{\
            "translate":"item.minecraft.stone_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_stone_sword_initial)\
        },\
        {\
          "id":"iron_sword",\
          "display":{\
            "translate":"item.minecraft.iron_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_iron_sword_initial)\
        },\
        {\
          "id":"copper_sword",\
          "display":{\
            "translate":"item.minecraft.copper_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_copper_sword_initial)\
        },\
        {\
          "id":"golden_sword",\
          "display":{\
            "translate":"item.minecraft.golden_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_golden_sword_initial)\
        },\
        {\
          "id":"diamond_sword",\
          "display":{\
            "translate":"item.minecraft.diamond_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_diamond_sword_initial)\
        },\
        {\
          "id":"netherite_sword",\
          "display":{\
            "translate":"item.minecraft.netherite_sword",\
            "color":"white"\
          },\
          "initial":$(vex_equip_netherite_sword_initial)\
        }\
      ]\
    }\
  ],\
  "can_close_with_escape":true,\
  "pause":true,\
  "after_action":"close",\
  "external_title":{\
    "translate":"menu.mob_manager.misc_settings.title",\
    "fallback":"Miscellaneous"\
  },\
  "title":{\
    "translate":"menu.mob_manager.main.title",\
    "fallback":"Nice Mob Manager"\
  },\
  "yes":{\
    "label":{\
      "translate":"option.mob_manager.confirm",\
      "fallback":"Confirm"\
    },\
    "action":{\
      "type":"minecraft:dynamic/run_command",\
      "template":"$(command_template)"\
    }\
  },\
  "no":{\
    "label":{\
      "translate":"gui.back"\
    },\
    "action":{\
      "type":"minecraft:show_dialog",\
      "dialog":"mob_manager:mob_equipment"\
    }\
  }\
}