$data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip:$(vex_equip),leathercolor:$(leathercolor),trim:$(trim),bannershield:$(bannershield)}

execute if data storage eden:settings mob_manager.mob_equipment.misc{leathercolor:"enabled"} run data modify storage eden:settings mob_manager.mob_equipment.misc.leathercolor_initial set value "false"
execute unless data storage eden:settings mob_manager.mob_equipment.misc{leathercolor:"enabled"} run data modify storage eden:settings mob_manager.mob_equipment.misc.leathercolor_initial set value "true"

execute if data storage eden:settings mob_manager.mob_equipment.misc{trim:"enabled"} run data modify storage eden:settings mob_manager.mob_equipment.misc.trim_initial set value "false"
execute unless data storage eden:settings mob_manager.mob_equipment.misc{trim:"enabled"} run data modify storage eden:settings mob_manager.mob_equipment.misc.trim_initial set value "true"

execute if data storage eden:settings mob_manager.mob_equipment.misc{bannershield:"enabled"} run data modify storage eden:settings mob_manager.mob_equipment.misc.bannershield_initial set value "false"
execute unless data storage eden:settings mob_manager.mob_equipment.misc{bannershield:"enabled"} run data modify storage eden:settings mob_manager.mob_equipment.misc.bannershield_initial set value "true"

$data modify storage eden:settings mob_manager.mob_equipment.misc.playerheads_initial set value $(playerheads)
execute store result storage eden:settings mob_manager.mob_equipment.misc.playerheads float 0.01 run data get storage eden:settings mob_manager.mob_equipment.misc.playerheads_initial

$data modify storage eden:settings mob_manager.mob_equipment.misc.mobheads_initial set value $(mobheads)
execute store result storage eden:settings mob_manager.mob_equipment.misc.mobheads float 0.01 run data get storage eden:settings mob_manager.mob_equipment.misc.mobheads_initial

execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"air"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"stick"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"true",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"wooden_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"true",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"stone_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"true",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"iron_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"true",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"golden_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"true",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"diamond_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"true",vex_equip_netherite_sword_initial:"false"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"netherite_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"false",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"true"}
execute if data storage eden:settings mob_manager.mob_equipment.misc{vex_equip:"copper_sword"} run data modify storage eden:settings mob_manager.mob_equipment.misc merge value {vex_equip_copper_sword_initial:"true",vex_equip_stick_initial:"false",vex_equip_wooden_sword_initial:"false",vex_equip_stone_sword_initial:"false",vex_equip_iron_sword_initial:"false",vex_equip_golden_sword_initial:"false",vex_equip_diamond_sword_initial:"false",vex_equip_netherite_sword_initial:"false"}

dialog show @s mob_manager:mob_equipment