data modify storage eden:database names.villager.deep_blue.last.1 set value "the Hydrographer"
data modify storage eden:database names.villager.deep_blue.last.2 set value "the Ichthyologist"
data modify storage eden:database names.villager.deep_blue.last.3 set value "the Marine Biologist"
data modify storage eden:database names.villager.deep_blue.last.4 set value "the Oceanographer"
data modify storage eden:database names.villager.deep_blue.last.5 set value "the Geologist"
data modify storage eden:database names.villager.deep_blue.last.6 set value "the Seismologist"
data modify storage eden:database names.villager.deep_blue.last.7 set value "the Meteorologist"
data modify storage eden:database names.villager.deep_blue.last.8 set value "the Climatologist"
data modify storage eden:database names.villager.deep_blue.last.9 set value "the Astrophysicist"
data modify storage eden:database names.villager.deep_blue.last.10 set value "the Astronomer"
data modify storage eden:database names.villager.deep_blue.last.11 set value "the Naval Architect"
data modify storage eden:database names.villager.deep_blue.last.12 set value "the Marine Engineer"
data modify storage eden:database names.villager.deep_blue.last.13 set value "the Acoustical Engineer"
data modify storage eden:database names.villager.deep_blue.last.14 set value "the Electrical Engineer"
data modify storage eden:database names.villager.deep_blue.last.15 set value "the Mechanical Engineer"
data modify storage eden:database names.villager.deep_blue.last.16 set value "the Civil Engineer"
data modify storage eden:database names.villager.deep_blue.last.17 set value "the Environmental Engineer"
data modify storage eden:database names.villager.deep_blue.last.18 set value "the Biomedical Engineer"
data modify storage eden:database names.villager.deep_blue.last.19 set value "the Data Analyst"
data modify storage eden:database names.villager.deep_blue.last.20 set value "the Marine Veterinarian"
data modify storage eden:database names.villager.deep_blue.last.21 set value "the Underwater Physician"
data modify storage eden:database names.villager.deep_blue.last.22 set value "the Hyperbaric Medicine Specialist"
data modify storage eden:database names.villager.deep_blue.last.23 set value "the Pharmacologist"
data modify storage eden:database names.villager.deep_blue.last.24 set value "the Toxicologist"
data modify storage eden:database names.villager.deep_blue.last.25 set value "the Underwater Explorer"
data modify storage eden:database names.villager.deep_blue.last.26 set value "the Underwater Archaeologist"
data modify storage eden:database names.villager.deep_blue.last.27 set value "the Cave Diver"
data modify storage eden:database names.villager.deep_blue.last.28 set value "the Deep-Sea Diver"
data modify storage eden:database names.villager.deep_blue.last.29 set value "the ROV Pilot"
data modify storage eden:database names.villager.deep_blue.last.30 set value "the Marine Educator"
data modify storage eden:database names.villager.deep_blue.last.31 set value "the Science Communicator"
data modify storage eden:database names.villager.deep_blue.last.32 set value "the Librarian"
data modify storage eden:database names.villager.deep_blue.last.33 set value "the Archivist"
data modify storage eden:database names.villager.deep_blue.last.34 set value "the Pearl Diver"
data modify storage eden:database names.villager.deep_blue.last.35 set value "the Coral Farmer"
data modify storage eden:database names.villager.deep_blue.last.36 set value "the Sponge Diver"
data modify storage eden:database names.villager.deep_blue.last.37 set value "the Fisherman"
data modify storage eden:database names.villager.deep_blue.last.38 set value "the Ship Captain"
data modify storage eden:database names.villager.deep_blue.last.39 set value "the Underwater Photographer"
data modify storage eden:database names.villager.deep_blue.last.40 set value "the Underwater Filmmaker"
data modify storage eden:database names.villager.deep_blue.last.41 set value "the Marine Artist"
data modify storage eden:database names.villager.deep_blue.last.42 set value "the Marine Musician"
data modify storage eden:database names.villager.deep_blue.last.43 set value "the Marine Writer"
data modify storage eden:database names.villager.deep_blue.last.44 set value "the Marine Philosopher"
data modify storage eden:database names.villager.deep_blue.last.45 set value "the Marine Historian"
data modify storage eden:database names.villager.deep_blue.last.46 set value "the Redstone Engineer"
data modify storage eden:database names.villager.deep_blue.last.47 set value "the Redstone Architect"
data modify storage eden:database names.villager.deep_blue.last.48 set value "the Redstone Technician"
data modify storage eden:database names.villager.deep_blue.last.49 set value "the Redstone Inventor"
data modify storage eden:database names.villager.deep_blue.last.50 set value "the Redstone Theorist"