  data modify storage eden:database names.villager.snow.last.1 set value Snowfall
  data modify storage eden:database names.villager.snow.last.2 set value Frostwalker
  data modify storage eden:database names.villager.snow.last.3 set value Icicleforge
  data modify storage eden:database names.villager.snow.last.4 set value Glaciershade
  data modify storage eden:database names.villager.snow.last.5 set value Winterfell
  data modify storage eden:database names.villager.snow.last.6 set value Chillwind
  data modify storage eden:database names.villager.snow.last.7 set value Iceheart
  data modify storage eden:database names.villager.snow.last.8 set value Snowglen
  data modify storage eden:database names.villager.snow.last.9 set value Frostweaver
 data modify storage eden:database names.villager.snow.last.10 set value Whiteveil
 data modify storage eden:database names.villager.snow.last.11 set value Crystalflame
 data modify storage eden:database names.villager.snow.last.12 set value Snowthorn
 data modify storage eden:database names.villager.snow.last.13 set value Iceshade
 data modify storage eden:database names.villager.snow.last.14 set value Frostgaze
 data modify storage eden:database names.villager.snow.last.15 set value Frostshadow
 data modify storage eden:database names.villager.snow.last.16 set value Glacierbreeze
 data modify storage eden:database names.villager.snow.last.17 set value Snowshadow
 data modify storage eden:database names.villager.snow.last.18 set value Wintergaze
 data modify storage eden:database names.villager.snow.last.19 set value Snowcap
 data modify storage eden:database names.villager.snow.last.20 set value Icevein
 data modify storage eden:database names.villager.snow.last.21 set value Frostcrest
 data modify storage eden:database names.villager.snow.last.22 set value Frostblade
 data modify storage eden:database names.villager.snow.last.23 set value Snowgazer
 data modify storage eden:database names.villager.snow.last.24 set value Chillwhisper
 data modify storage eden:database names.villager.snow.last.25 set value Glacialveil
 data modify storage eden:database names.villager.snow.last.26 set value Iceman
 data modify storage eden:database names.villager.snow.last.27 set value Snowstone
 data modify storage eden:database names.villager.snow.last.28 set value Frostveil
 data modify storage eden:database names.villager.snow.last.29 set value Iceflare
 data modify storage eden:database names.villager.snow.last.30 set value Wintertide
 data modify storage eden:database names.villager.snow.last.31 set value Snowflame
 data modify storage eden:database names.villager.snow.last.32 set value Frostbloom
 data modify storage eden:database names.villager.snow.last.33 set value Icewhisper
 data modify storage eden:database names.villager.snow.last.34 set value Glacialshade
 data modify storage eden:database names.villager.snow.last.35 set value Snowmist
 data modify storage eden:database names.villager.snow.last.36 set value Winterstone
 data modify storage eden:database names.villager.snow.last.37 set value Frosttide
 data modify storage eden:database names.villager.snow.last.38 set value Icewarden
 data modify storage eden:database names.villager.snow.last.39 set value Snowfall
 data modify storage eden:database names.villager.snow.last.40 set value Winterforge
 data modify storage eden:database names.villager.snow.last.41 set value Chillstone
 data modify storage eden:database names.villager.snow.last.42 set value Frostglen
 data modify storage eden:database names.villager.snow.last.43 set value Snowveil
 data modify storage eden:database names.villager.snow.last.44 set value Icebloom
 data modify storage eden:database names.villager.snow.last.45 set value Frostspark
 data modify storage eden:database names.villager.snow.last.46 set value Winterwatch
 data modify storage eden:database names.villager.snow.last.47 set value Snowflare
 data modify storage eden:database names.villager.snow.last.48 set value Chillveil
 data modify storage eden:database names.villager.snow.last.49 set value Frostmantle
 data modify storage eden:database names.villager.snow.last.50 set value Icetide
 data modify storage eden:database names.villager.snow.last.51 set value Glaciershade
 data modify storage eden:database names.villager.snow.last.52 set value Snowclaw
 data modify storage eden:database names.villager.snow.last.53 set value Frostroot
 data modify storage eden:database names.villager.snow.last.54 set value Winterwhisper
 data modify storage eden:database names.villager.snow.last.55 set value Iceglow
 data modify storage eden:database names.villager.snow.last.56 set value Snowywind
 data modify storage eden:database names.villager.snow.last.57 set value Glacialthorn
 data modify storage eden:database names.villager.snow.last.58 set value Frostdancer
 data modify storage eden:database names.villager.snow.last.59 set value Winterblaze
 data modify storage eden:database names.villager.snow.last.60 set value Snowshade
 data modify storage eden:database names.villager.snow.last.61 set value Icefrost
 data modify storage eden:database names.villager.snow.last.62 set value Snowstorm
 data modify storage eden:database names.villager.snow.last.63 set value Winterveil
 data modify storage eden:database names.villager.snow.last.64 set value Glacialveil
 data modify storage eden:database names.villager.snow.last.65 set value Chillbreeze
 data modify storage eden:database names.villager.snow.last.66 set value Frostwhisper
 data modify storage eden:database names.villager.snow.last.67 set value Icethorn
 data modify storage eden:database names.villager.snow.last.68 set value Snowrider
 data modify storage eden:database names.villager.snow.last.69 set value Frostshard
 data modify storage eden:database names.villager.snow.last.70 set value Icekeeper
 data modify storage eden:database names.villager.snow.last.71 set value Winterveil
 data modify storage eden:database names.villager.snow.last.72 set value Snowdrift
 data modify storage eden:database names.villager.snow.last.73 set value Chillmist
 data modify storage eden:database names.villager.snow.last.74 set value Frostgleam
 data modify storage eden:database names.villager.snow.last.75 set value Snowfall
 data modify storage eden:database names.villager.snow.last.76 set value Glacierbloom
 data modify storage eden:database names.villager.snow.last.77 set value Icewatcher
 data modify storage eden:database names.villager.snow.last.78 set value Snowblaze
 data modify storage eden:database names.villager.snow.last.79 set value Frostbound
 data modify storage eden:database names.villager.snow.last.80 set value Winterbloom
 data modify storage eden:database names.villager.snow.last.81 set value Snowflare
 data modify storage eden:database names.villager.snow.last.82 set value Frostveil
 data modify storage eden:database names.villager.snow.last.83 set value Icegazer
 data modify storage eden:database names.villager.snow.last.84 set value Snowtide
 data modify storage eden:database names.villager.snow.last.85 set value Winterwatcher
 data modify storage eden:database names.villager.snow.last.86 set value Chillwatch
 data modify storage eden:database names.villager.snow.last.87 set value Snowglow
 data modify storage eden:database names.villager.snow.last.88 set value Frostthorn
 data modify storage eden:database names.villager.snow.last.89 set value Iceveil
 data modify storage eden:database names.villager.snow.last.90 set value Snowbringer
 data modify storage eden:database names.villager.snow.last.91 set value Wintertide
 data modify storage eden:database names.villager.snow.last.92 set value Snowcloak
 data modify storage eden:database names.villager.snow.last.93 set value Frostbringer
 data modify storage eden:database names.villager.snow.last.94 set value Icewhisper
 data modify storage eden:database names.villager.snow.last.95 set value Snowkeeper
 data modify storage eden:database names.villager.snow.last.96 set value Frostfall
 data modify storage eden:database names.villager.snow.last.97 set value Glacialveil
 data modify storage eden:database names.villager.snow.last.98 set value Chillshade
 data modify storage eden:database names.villager.snow.last.99 set value Snowcrest
data modify storage eden:database names.villager.snow.last.100 set value Frostfall
data modify storage eden:database names.villager.snow.last.101 set value Iceveil
data modify storage eden:database names.villager.snow.last.102 set value Winterflame
data modify storage eden:database names.villager.snow.last.103 set value Snowflare
data modify storage eden:database names.villager.snow.last.104 set value Glacialheart
data modify storage eden:database names.villager.snow.last.105 set value Frostcloak
data modify storage eden:database names.villager.snow.last.106 set value Chillblaze
data modify storage eden:database names.villager.snow.last.107 set value Snowwhisper
data modify storage eden:database names.villager.snow.last.108 set value Winterveil
data modify storage eden:database names.villager.snow.last.109 set value Iceblaze
data modify storage eden:database names.villager.snow.last.110 set value Snowcrest
data modify storage eden:database names.villager.snow.last.111 set value Frostveil
data modify storage eden:database names.villager.snow.last.112 set value Chillheart
data modify storage eden:database names.villager.snow.last.113 set value Icewhisper
data modify storage eden:database names.villager.snow.last.114 set value Snowglen
data modify storage eden:database names.villager.snow.last.115 set value Winterbreeze
data modify storage eden:database names.villager.snow.last.116 set value Froststone
data modify storage eden:database names.villager.snow.last.117 set value Snowshadow
data modify storage eden:database names.villager.snow.last.118 set value Glacialclaw
data modify storage eden:database names.villager.snow.last.119 set value Frostshade
data modify storage eden:database names.villager.snow.last.120 set value Iceflare
data modify storage eden:database names.villager.snow.last.121 set value Winterfrost
data modify storage eden:database names.villager.snow.last.122 set value Snowrider
data modify storage eden:database names.villager.snow.last.123 set value Chillveil
data modify storage eden:database names.villager.snow.last.124 set value Froststorm
data modify storage eden:database names.villager.snow.last.125 set value Icewhisper
data modify storage eden:database names.villager.snow.last.126 set value Snowstorm
data modify storage eden:database names.villager.snow.last.127 set value Wintercrest
data modify storage eden:database names.villager.snow.last.128 set value Frostgazer
data modify storage eden:database names.villager.snow.last.129 set value Glacialwatch
data modify storage eden:database names.villager.snow.last.130 set value Iceforge
data modify storage eden:database names.villager.snow.last.131 set value Snowveil
data modify storage eden:database names.villager.snow.last.132 set value Frostclaw
data modify storage eden:database names.villager.snow.last.133 set value Winterveil
data modify storage eden:database names.villager.snow.last.134 set value Snowheart
data modify storage eden:database names.villager.snow.last.135 set value Frostshard
data modify storage eden:database names.villager.snow.last.136 set value Icecloak
data modify storage eden:database names.villager.snow.last.137 set value Glacialstone
data modify storage eden:database names.villager.snow.last.138 set value Snowblaze
data modify storage eden:database names.villager.snow.last.139 set value Winterwhisper
data modify storage eden:database names.villager.snow.last.140 set value Frostkeeper
data modify storage eden:database names.villager.snow.last.141 set value Chillthorn
data modify storage eden:database names.villager.snow.last.142 set value Snowgaze
data modify storage eden:database names.villager.snow.last.143 set value Frostwarden
data modify storage eden:database names.villager.snow.last.144 set value Icewind
data modify storage eden:database names.villager.snow.last.145 set value Snowveil
data modify storage eden:database names.villager.snow.last.146 set value Wintershard
data modify storage eden:database names.villager.snow.last.147 set value Frostdancer
data modify storage eden:database names.villager.snow.last.148 set value Glacialblaze
data modify storage eden:database names.villager.snow.last.149 set value Snowbloom
data modify storage eden:database names.villager.snow.last.150 set value Iceveil
data modify storage eden:database names.villager.snow.last.151 set value Froststorm
data modify storage eden:database names.villager.snow.last.152 set value Chillveil
data modify storage eden:database names.villager.snow.last.153 set value Snowclaw
data modify storage eden:database names.villager.snow.last.154 set value Wintertide
data modify storage eden:database names.villager.snow.last.155 set value Icecrest
data modify storage eden:database names.villager.snow.last.156 set value Snowwatch
data modify storage eden:database names.villager.snow.last.157 set value Frostbound
data modify storage eden:database names.villager.snow.last.158 set value Glacialshadow
data modify storage eden:database names.villager.snow.last.159 set value Snowflare
data modify storage eden:database names.villager.snow.last.160 set value Winterveil
data modify storage eden:database names.villager.snow.last.161 set value Chillshade
data modify storage eden:database names.villager.snow.last.162 set value Frostveil
data modify storage eden:database names.villager.snow.last.163 set value Icegazer
data modify storage eden:database names.villager.snow.last.164 set value Snowstorm
data modify storage eden:database names.villager.snow.last.165 set value Glacialveil
data modify storage eden:database names.villager.snow.last.166 set value Winterbloom
data modify storage eden:database names.villager.snow.last.167 set value Snowheart
data modify storage eden:database names.villager.snow.last.168 set value Frostveil
data modify storage eden:database names.villager.snow.last.169 set value Icewhisper
data modify storage eden:database names.villager.snow.last.170 set value Snowrider
data modify storage eden:database names.villager.snow.last.171 set value Winterstone
data modify storage eden:database names.villager.snow.last.172 set value Chillwind
data modify storage eden:database names.villager.snow.last.173 set value Frostfall
data modify storage eden:database names.villager.snow.last.174 set value Snowveil
data modify storage eden:database names.villager.snow.last.175 set value Iceclaw
data modify storage eden:database names.villager.snow.last.176 set value Glacialcrest
data modify storage eden:database names.villager.snow.last.177 set value Frostglen
data modify storage eden:database names.villager.snow.last.178 set value Snowflare
data modify storage eden:database names.villager.snow.last.179 set value Winterwhisper
data modify storage eden:database names.villager.snow.last.180 set value Chillshadow
data modify storage eden:database names.villager.snow.last.181 set value Frostveil
data modify storage eden:database names.villager.snow.last.182 set value Icewhisper
data modify storage eden:database names.villager.snow.last.183 set value Snowgaze
data modify storage eden:database names.villager.snow.last.184 set value Wintershade
data modify storage eden:database names.villager.snow.last.185 set value Glacialstorm
data modify storage eden:database names.villager.snow.last.186 set value Frostshade
data modify storage eden:database names.villager.snow.last.187 set value Icegaze
data modify storage eden:database names.villager.snow.last.188 set value Snowfall
data modify storage eden:database names.villager.snow.last.189 set value Winterveil
data modify storage eden:database names.villager.snow.last.190 set value Chillstone
data modify storage eden:database names.villager.snow.last.191 set value Frostblaze
data modify storage eden:database names.villager.snow.last.192 set value Snowclaw
data modify storage eden:database names.villager.snow.last.193 set value Glacialveil
data modify storage eden:database names.villager.snow.last.194 set value Icefall
data modify storage eden:database names.villager.snow.last.195 set value Snowtide
data modify storage eden:database names.villager.snow.last.196 set value Wintergaze
data modify storage eden:database names.villager.snow.last.197 set value Frostveil
data modify storage eden:database names.villager.snow.last.198 set value Chillbreeze
data modify storage eden:database names.villager.snow.last.199 set value Snowstorm
data modify storage eden:database names.villager.snow.last.200 set value Iceveil
data modify storage eden:database names.villager.snow.last.201 set value Froststone
data modify storage eden:database names.villager.snow.last.202 set value Winterblaze
data modify storage eden:database names.villager.snow.last.203 set value Snowrider
data modify storage eden:database names.villager.snow.last.204 set value Glacialwhisper
data modify storage eden:database names.villager.snow.last.205 set value Chillstorm
data modify storage eden:database names.villager.snow.last.206 set value Iceflare
data modify storage eden:database names.villager.snow.last.207 set value Snowfall
data modify storage eden:database names.villager.snow.last.208 set value Frostfall
data modify storage eden:database names.villager.snow.last.209 set value Winterveil
data modify storage eden:database names.villager.snow.last.210 set value Snowshade
data modify storage eden:database names.villager.snow.last.211 set value Glacialgaze
data modify storage eden:database names.villager.snow.last.212 set value Iceclaw
data modify storage eden:database names.villager.snow.last.213 set value Frostwatch
data modify storage eden:database names.villager.snow.last.214 set value Snowstorm
data modify storage eden:database names.villager.snow.last.215 set value Wintershade
data modify storage eden:database names.villager.snow.last.216 set value Chillveil
data modify storage eden:database names.villager.snow.last.217 set value Frostveil
data modify storage eden:database names.villager.snow.last.218 set value Icewatcher
data modify storage eden:database names.villager.snow.last.219 set value Snowglen
data modify storage eden:database names.villager.snow.last.220 set value Glacialshadow
data modify storage eden:database names.villager.snow.last.221 set value Frostheart
data modify storage eden:database names.villager.snow.last.222 set value Snowveil
data modify storage eden:database names.villager.snow.last.223 set value Wintergaze
data modify storage eden:database names.villager.snow.last.224 set value Chillglen
data modify storage eden:database names.villager.snow.last.225 set value Frostblaze
data modify storage eden:database names.villager.snow.last.226 set value Icewhisper
data modify storage eden:database names.villager.snow.last.227 set value Snowfall
data modify storage eden:database names.villager.snow.last.228 set value Glacialbreeze
data modify storage eden:database names.villager.snow.last.229 set value Winterveil
data modify storage eden:database names.villager.snow.last.230 set value Chillflare
data modify storage eden:database names.villager.snow.last.231 set value Froststone
data modify storage eden:database names.villager.snow.last.232 set value Snowstorm
data modify storage eden:database names.villager.snow.last.233 set value Iceclaw
data modify storage eden:database names.villager.snow.last.234 set value Wintershade
data modify storage eden:database names.villager.snow.last.235 set value Frostveil
data modify storage eden:database names.villager.snow.last.236 set value Glacialheart
data modify storage eden:database names.villager.snow.last.237 set value Snowrider
data modify storage eden:database names.villager.snow.last.238 set value Chillveil
data modify storage eden:database names.villager.snow.last.239 set value Icebloom
data modify storage eden:database names.villager.snow.last.240 set value Snowveil
data modify storage eden:database names.villager.snow.last.241 set value Winterstorm
data modify storage eden:database names.villager.snow.last.242 set value Frostwatch
data modify storage eden:database names.villager.snow.last.243 set value Iceflare
data modify storage eden:database names.villager.snow.last.244 set value Snowshade
data modify storage eden:database names.villager.snow.last.245 set value Glacialveil
data modify storage eden:database names.villager.snow.last.246 set value Winterclaw
data modify storage eden:database names.villager.snow.last.247 set value Frostveil
data modify storage eden:database names.villager.snow.last.248 set value Snowfall
data modify storage eden:database names.villager.snow.last.249 set value Chillstone
data modify storage eden:database names.villager.snow.last.250 set value Iceheart
data modify storage eden:database names.villager.snow.last.251 set value Glacialstorm
data modify storage eden:database names.villager.snow.last.252 set value Wintergaze
data modify storage eden:database names.villager.snow.last.253 set value Snowwatch
data modify storage eden:database names.villager.snow.last.254 set value Frostshade
data modify storage eden:database names.villager.snow.last.255 set value Iceclaw
data modify storage eden:database names.villager.snow.last.256 set value Chillveil
data modify storage eden:database names.villager.snow.last.257 set value Snowstorm
data modify storage eden:database names.villager.snow.last.258 set value Winterveil
data modify storage eden:database names.villager.snow.last.259 set value Frostglen
data modify storage eden:database names.villager.snow.last.260 set value Glacialwatch
data modify storage eden:database names.villager.snow.last.261 set value Icewhisper
data modify storage eden:database names.villager.snow.last.262 set value Snowflare
data modify storage eden:database names.villager.snow.last.263 set value Winterstone
data modify storage eden:database names.villager.snow.last.264 set value Chillshadow
data modify storage eden:database names.villager.snow.last.265 set value Froststorm
data modify storage eden:database names.villager.snow.last.266 set value Snowbloom
data modify storage eden:database names.villager.snow.last.267 set value Iceveil
data modify storage eden:database names.villager.snow.last.268 set value Glacialveil
data modify storage eden:database names.villager.snow.last.269 set value Winterfall
data modify storage eden:database names.villager.snow.last.270 set value Snowclaw
data modify storage eden:database names.villager.snow.last.271 set value Frostgazer
data modify storage eden:database names.villager.snow.last.272 set value Iceclaw
data modify storage eden:database names.villager.snow.last.273 set value Winterveil
data modify storage eden:database names.villager.snow.last.274 set value Chillwind
data modify storage eden:database names.villager.snow.last.275 set value Frostwatch
data modify storage eden:database names.villager.snow.last.276 set value Snowstorm
data modify storage eden:database names.villager.snow.last.277 set value Glacialbreeze
data modify storage eden:database names.villager.snow.last.278 set value Icegaze
data modify storage eden:database names.villager.snow.last.279 set value Wintershade
data modify storage eden:database names.villager.snow.last.280 set value Frostveil
data modify storage eden:database names.villager.snow.last.281 set value Chillbreeze
data modify storage eden:database names.villager.snow.last.282 set value Snowfall
data modify storage eden:database names.villager.snow.last.283 set value Iceblaze
data modify storage eden:database names.villager.snow.last.284 set value Glacialshadow
data modify storage eden:database names.villager.snow.last.285 set value Frostveil
data modify storage eden:database names.villager.snow.last.286 set value Wintergaze
data modify storage eden:database names.villager.snow.last.287 set value Snowshade
data modify storage eden:database names.villager.snow.last.288 set value Chillveil
data modify storage eden:database names.villager.snow.last.289 set value Iceglen
data modify storage eden:database names.villager.snow.last.290 set value Glacialheart
data modify storage eden:database names.villager.snow.last.291 set value Snowstorm
data modify storage eden:database names.villager.snow.last.292 set value Winterfall
data modify storage eden:database names.villager.snow.last.293 set value Frostshade
data modify storage eden:database names.villager.snow.last.294 set value Snowrider
data modify storage eden:database names.villager.snow.last.295 set value Iceveil
data modify storage eden:database names.villager.snow.last.296 set value Glacialclaw
data modify storage eden:database names.villager.snow.last.297 set value Chillshadow
data modify storage eden:database names.villager.snow.last.298 set value Frostbloom
data modify storage eden:database names.villager.snow.last.299 set value Winterveil
data modify storage eden:database names.villager.snow.last.300 set value Snowfall
data modify storage eden:database names.villager.snow.last.301 set value Iceflare
data modify storage eden:database names.villager.snow.last.302 set value Glacialstorm
data modify storage eden:database names.villager.snow.last.303 set value Frostgaze
data modify storage eden:database names.villager.snow.last.304 set value Chillveil
data modify storage eden:database names.villager.snow.last.305 set value Snowbloom
data modify storage eden:database names.villager.snow.last.306 set value Wintershade
data modify storage eden:database names.villager.snow.last.307 set value Icewatcher
data modify storage eden:database names.villager.snow.last.308 set value Glacialveil
data modify storage eden:database names.villager.snow.last.309 set value Froststorm
data modify storage eden:database names.villager.snow.last.310 set value Snowshade
data modify storage eden:database names.villager.snow.last.311 set value Chillclaw
data modify storage eden:database names.villager.snow.last.312 set value Wintergaze
data modify storage eden:database names.villager.snow.last.313 set value Iceveil
data modify storage eden:database names.villager.snow.last.314 set value Glacialheart
data modify storage eden:database names.villager.snow.last.315 set value Frostfall
data modify storage eden:database names.villager.snow.last.316 set value Snowfall
data modify storage eden:database names.villager.snow.last.317 set value Chillshadow
data modify storage eden:database names.villager.snow.last.318 set value Winterfall
data modify storage eden:database names.villager.snow.last.319 set value Iceblaze
data modify storage eden:database names.villager.snow.last.320 set value Glacialveil
data modify storage eden:database names.villager.snow.last.321 set value Frostveil
data modify storage eden:database names.villager.snow.last.322 set value Snowstone
data modify storage eden:database names.villager.snow.last.323 set value Chillveil
data modify storage eden:database names.villager.snow.last.324 set value Wintershade
data modify storage eden:database names.villager.snow.last.325 set value Icegazer
data modify storage eden:database names.villager.snow.last.326 set value Glacialstorm
data modify storage eden:database names.villager.snow.last.327 set value Frostbloom
data modify storage eden:database names.villager.snow.last.328 set value Snowfall
data modify storage eden:database names.villager.snow.last.329 set value Winterveil
data modify storage eden:database names.villager.snow.last.330 set value Iceflare
data modify storage eden:database names.villager.snow.last.331 set value Chillbreeze
data modify storage eden:database names.villager.snow.last.332 set value Frostglen
data modify storage eden:database names.villager.snow.last.333 set value Snowshade
data modify storage eden:database names.villager.snow.last.334 set value Glacialveil
data modify storage eden:database names.villager.snow.last.335 set value Winterfall
data modify storage eden:database names.villager.snow.last.336 set value Iceclaw
data modify storage eden:database names.villager.snow.last.337 set value Snowstorm
data modify storage eden:database names.villager.snow.last.338 set value Chillgaze
data modify storage eden:database names.villager.snow.last.339 set value Frostwatch
data modify storage eden:database names.villager.snow.last.340 set value Wintergaze
data modify storage eden:database names.villager.snow.last.341 set value Iceveil
data modify storage eden:database names.villager.snow.last.342 set value Glacialfall
data modify storage eden:database names.villager.snow.last.343 set value Snowfall
data modify storage eden:database names.villager.snow.last.344 set value Frostbloom
data modify storage eden:database names.villager.snow.last.345 set value Wintershade
data modify storage eden:database names.villager.snow.last.346 set value Iceblaze
data modify storage eden:database names.villager.snow.last.347 set value Chillveil
data modify storage eden:database names.villager.snow.last.348 set value Glacialgaze
data modify storage eden:database names.villager.snow.last.349 set value Snowstorm
data modify storage eden:database names.villager.snow.last.350 set value Winterveil
data modify storage eden:database names.villager.snow.last.351 set value Frostshade
data modify storage eden:database names.villager.snow.last.352 set value Icefall
data modify storage eden:database names.villager.snow.last.353 set value Glacialstorm
data modify storage eden:database names.villager.snow.last.354 set value Snowbloom
data modify storage eden:database names.villager.snow.last.355 set value Chillshade
data modify storage eden:database names.villager.snow.last.356 set value Winterfall
data modify storage eden:database names.villager.snow.last.357 set value Frostveil
data modify storage eden:database names.villager.snow.last.358 set value Icegaze
data modify storage eden:database names.villager.snow.last.359 set value Snowfall
data modify storage eden:database names.villager.snow.last.360 set value Glacialshadow
data modify storage eden:database names.villager.snow.last.361 set value Wintershade
data modify storage eden:database names.villager.snow.last.362 set value Chillfall
data modify storage eden:database names.villager.snow.last.363 set value Frostwatch
data modify storage eden:database names.villager.snow.last.364 set value Snowstorm
data modify storage eden:database names.villager.snow.last.365 set value Iceclaw
data modify storage eden:database names.villager.snow.last.366 set value Glacialveil
data modify storage eden:database names.villager.snow.last.367 set value Winterfall
data modify storage eden:database names.villager.snow.last.368 set value Snowveil
data modify storage eden:database names.villager.snow.last.369 set value Chillgaze
data modify storage eden:database names.villager.snow.last.370 set value Frostshade
data modify storage eden:database names.villager.snow.last.371 set value Icebloom
data modify storage eden:database names.villager.snow.last.372 set value Glacialstorm
data modify storage eden:database names.villager.snow.last.373 set value Winterveil
data modify storage eden:database names.villager.snow.last.374 set value Snowrider
data modify storage eden:database names.villager.snow.last.375 set value Chillstorm
data modify storage eden:database names.villager.snow.last.376 set value Petalblush
data modify storage eden:database names.villager.snow.last.377 set value Butterbottom
data modify storage eden:database names.villager.snow.last.378 set value Blockwright
data modify storage eden:database names.villager.snow.last.379 set value Jasper
data modify storage eden:database names.villager.snow.last.380 set value Stonehammer